const db = {
    home: {
        title: "Dinner Table",
        subtitle: "No phones. Just us. Pass the potatoes.",
        tags: ["Ice Breaker", "The Menu", "Wisdom", "Cheat Code", "Humor", "Life Skill"],
        btns: ["Next Question", "Pick Order", "Next Quote", "Next Cheat Code", "Next Joke", "Next Skill"],
        
        // CHECK IN
        checkin: [
            "🥦 <strong>Veggies:</strong> What challenge is making you stronger?", 
            "🥩 <strong>Meat & Potatoes:</strong> What are you most grateful for?", 
            "🍰 <strong>Dessert:</strong> What are you looking forward to?"
        ],
        
        iceBreakers: [
            "If you could have a boring superpower (like refilling water cups instantly), what would it be?",
            "What is the weirdest thing you have ever eaten?",
            "If animals could talk, which one would be the rudest?",
            "What is your favorite smell in the whole world?",
            "If you could build a house out of anything, what would it be?",
            "What is the bravest thing you have ever done?",
            "If you were a teacher, what rule would you make for your class?",
            "What is the best gift you have ever given someone?",
            "If you could trade places with anyone for a day, who would it be?",
            "What is your favorite family tradition?",
            "If you opened a store, what would you sell?",
            "What is the funniest face you can make?",
            "If you could instantly learn any instrument, what would you play?",
            "What is something you are really good at?",
            "If you could invent a new holiday, what would we celebrate?",
            "What is your favorite thing to do on a rainy day?",
            "If you could meet any character from a book, who would it be?",
            "What is the best dream you’ve ever had?",
            "If you had a robot helper, what chore would you make it do?",
            "What is your favorite memory from a vacation?",
            "If you were a superhero, what would your name be?",
            "What makes you laugh the most?",
            "If you could only eat one color of food for a week, which color would you pick?",
            "What is the kindest thing someone has done for you recently?",
            "If you could design a new animal, what would it look like?",
            "What is your favorite thing about yourself?",
            "If you could time travel to the past or future, where would you go?",
            "What is the hardest thing about being your age?",
            "If you could be invisible for one hour, what would you do?",
            "What is your favorite word?",
            "If you were the President, what is the first law you would make?",
            "What is the grossest vegetable?",
            "If you could have any wild animal as a pet (and it wouldn't bite), what would you pick?",
            "What is your favorite sound?",
            "If you could create a new flavor of ice cream, what would it be?",
            "What is something you want to learn how to do?",
            "If you could talk to your dog/cat, what would you say?",
            "What is the most embarrassing thing your parents do?",
            "If you could be in any movie, which one would you pick?",
            "What is your favorite thing to do outside?",
            "If you had 1 million dollars, what is the first thing you would buy?",
            "What is a fear you used to have but conquered?",
            "If you could grow a garden of anything (not just plants), what would you grow?",
            "What is your favorite joke?",
            "If you could change your name, what would you change it to?",
            "What is the best compliment you ever received?",
            "If you could stay up all night, what would you do?",
            "What is your favorite season and why?",
            "If you were a ghost, who would you haunt?",
            "What is the most boring sport to watch?",
            "If you could fly, where would you go first?",
            "What is your favorite thing in your bedroom?",
            "If you could shrink down to the size of an ant, what would you explore?",
            "What is the best thing about our family?",
            "If you could have a walk-up song play every time you entered a room, what would it be?",
            "If you could add a new, magical room to our house, what would it be?",
            "What movie or TV show character do you think is most like you?",
            "What's the funniest thing that's ever happened to you?",
            "If you could only use one emoji for the rest of your life, which one?",
            "What is the weirdest dream you remember having?",
            "If you could be an expert in any subject instantly, what would it be?",
            "What is your favorite snack to sneak?"
        ],
        quotes: [
            { text: "Family is not an important thing. It's everything.", author: "Michael J. Fox" },
            { text: "The love of a family is life's greatest blessing.", author: "Unknown" },
            { text: "In time of test, family is best.", author: "Burmese Proverb" },
            { text: "The strength of a family, like the strength of an army, is in its loyalty to each other.", author: "Mario Puzo" },
            { text: "What can you do to promote world peace? Go home and love your family.", author: "Mother Teresa" },
            { text: "A happy family is but an earlier heaven.", author: "George Bernard Shaw" },
            { text: "No act of kindness, no matter how small, is ever wasted.", author: "Aesop" },
            { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
            { text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington" },
            { text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt" },
            { text: "Family means no one gets left behind or forgotten.", author: "David Ogden Stiers" },
            { text: "Home is where you are loved the most and act the worst.", author: "Marjorie Pay Hinckley" },
            { text: "The memories we make with our family is everything.", author: "Candace Cameron Bure" },
            { text: "Family is a life jacket in the stormy sea of life.", author: "J.K. Rowling" },
            { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
            { text: "Happiness is homemade.", author: "Unknown" },
            { text: "Ohana means family.", author: "Lilo & Stitch" },
            { text: "The most important thing in the world is family and love.", author: "John Wooden" },
            { text: "Rejoice with your family in the beautiful land of life.", author: "Albert Einstein" },
            { text: "Family is where life begins and love never ends.", author: "Unknown" },
            { text: "You don't choose your family. They are God's gift to you.", author: "Desmond Tutu" },
            { text: "Other things may change us, but we start and end with the family.", author: "Anthony Brandt" },
            { text: "To us, family means putting your arms around each other and being there.", author: "Barbara Bush" },
            { text: "A house is built with hands, but a home is built with hearts.", author: "Unknown" },
            { text: "Family is the anchor that holds us through life’s storms.", author: "Unknown" },
            { text: "The family is one of nature's masterpieces.", author: "George Santayana" },
            { text: "Being a family means you are a part of something very wonderful.", author: "Lisa Weed" },
            { text: "Peace is the beauty of life. It is sunshine. It is the smile of a child.", author: "Menachem Begin" },
            { text: "Children are the hands by which we take hold of heaven.", author: "Henry Ward Beecher" },
            { text: "While we try to teach our children all about life, our children teach us what life is all about.", author: "Angela Schwindt" },
            { text: "Every day is a fresh start.", author: "Unknown" },
            { text: "Kindness is a language which the deaf can hear and the blind can see.", author: "Mark Twain" },
            { text: "Be the change that you wish to see in the world.", author: "Mahatma Gandhi" },
            { text: "Yesterday is history. Tomorrow is a mystery. Today is a gift.", author: "Eleanor Roosevelt" },
            { text: "Try to be a rainbow in someone's cloud.", author: "Maya Angelou" },
            { text: "Don't count the days, make the days count.", author: "Muhammad Ali" },
            { text: "The best way to predict the future is to create it.", author: "Abraham Lincoln" },
            { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
            { text: "You are braver than you believe, stronger than you seem, and smarter than you think.", author: "A.A. Milne" },
            { text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll" },
            { text: "Act as if what you do makes a difference. It does.", author: "William James" },
            { text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe" },
            { text: "Don't let yesterday take up too much of today.", author: "Will Rogers" },
            { text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky" },
            { text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein" },
            { text: "It is never too late to be what you might have been.", author: "George Eliot" },
            { text: "Do the right thing, even when no one is looking.", author: "C.S. Lewis" },
            { text: "Honesty is the first chapter in the book of wisdom.", author: "Thomas Jefferson" },
            { text: "Politeness is a sign of dignity, not subservience.", author: "Theodore Roosevelt" },
            { text: "Gratitude turns what we have into enough.", author: "Unknown" },
            { text: "Listening is an act of love.", author: "Unknown" },
            { text: "The roots of education are bitter, but the fruit is sweet.", author: "Aristotle" },
            { text: "Mistakes are proof that you are trying.", author: "Unknown" },
            { text: "Integrity is doing the right thing, even when no one is watching.", author: "C.S. Lewis" },
            { text: "If you can dream it, you can do it.", author: "Walt Disney" },
            { text: "Be silly, be honest, be kind.", author: "Ralph Waldo Emerson" },
            { text: "Make each day your masterpiece.", author: "John Wooden" },
            { text: "Attitude is a little thing that makes a big difference.", author: "Winston Churchill" },
            { text: "The expert in anything was once a beginner.", author: "Helen Hayes" }
        ],
        dynamics: [ 
            { title: "The Level 99 Paladin", body: "Alex loved video games. He spent all weekend grinding levels to get the 'Golden Armor' for his character. He felt powerful. But on Monday morning, he realized he hadn't studied for his math test, his room was a disaster, and he was exhausted. He failed the test. The next day, the game released a new update and his Golden Armor wasn't the best anymore. He realized he had leveled up a fake character while his real character was failing. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Real life progress (grades, skills, health) is saved forever. Video game progress can be deleted in a second. Prioritize your main character (You).</div>" },
            { title: "The Million Dollar Dust", body: "A man finally bought his dream car—a vintage red convertible. He loved driving it, but he hated the boring stuff like oil changes and tire rotations. 'It runs fine,' he said. 'I'd rather spend that money on gas.' Two years later, the engine seized up on the highway. The mechanic told him the engine was ruined because of the old oil. He had to sell the car for scrap metal. His neighbor, who drove a cheap sedan but took care of it, was still driving happily. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Taking care of your things is the ultimate money hack. Maintenance is boring, but it is much cheaper than replacement.</div>" },
            { title: "The Green Cloud", body: "Sam decided he didn't need to shower after soccer practice. 'I don't smell that bad,' he told himself. He put on extra deodorant and went to school. He didn't notice the smell because he was used to it—he was 'nose blind.' But when he sat next to his crush in science class, she quietly moved three seats away without saying a word. He realized too late that just because you can't smell yourself, doesn't mean others can't. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You are the last person to know if you smell. Trust your parents when they say you need soap. Hygiene is social survival.</div>" },
            { title: "The Silent Assassin", body: "During the championship basketball game, Mia missed an easy layup. Her teammate, Sarah, rolled her eyes and yelled, 'Come on, Mia!' Mia felt so embarrassed and angry that she played worse the rest of the game. They lost by one point. If Sarah had high-fived her and said, 'Get the next one,' Mia might have recovered. Sarah scored the most points, but she was the reason they lost. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Your attitude is a teammate. If you are negative, you are playing for the other team.</div>" },
            { title: "The Two Wolves", body: "An old grandfather sat by the fire with his grandson. 'Inside of me,' he said, 'there is a terrible fight between two wolves. One is evil—he is anger, jealousy, greed, and ego. The other is good—he is joy, peace, love, hope, and kindness.' The boy thought about it and asked, 'Grandpa, which wolf wins?' The grandfather smiled. 'The one I feed.' <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Your mind is a battleground. Every thought you dwell on feeds a wolf. Be careful which one you make strong.</div>" },
            { title: "The Magic Word", body: "Ben marched into the living room. 'Dad, take me to the mall. I need to meet my friends.' His dad didn't even look up from his book. 'No.' Ben stormed off, fuming. He realized demanding wasn't working. He cooled down, walked back in, and tried a different angle. 'Hey Dad, if I take out the trash and unload the dishwasher right now, would you mind driving me?' His dad closed the book and grabbed the keys. 'Deal.' <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Negotiation works better than demanding. If you want something, offer value first.</div>" },
            { title: "The Screen Zombie", body: "The family went on a vacation to Hawaii. It was beautiful. But Tyler spent the entire time on his phone, scrolling through videos of *other* people at the beach. He got mad when his mom asked him to look at the sunset. Five years later, he looked at photos of the trip. He saw his family smiling, but he had no memory of the waves or the sand. He only remembered the memes he saw on his screen. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Be where your feet are. Don't trade a real memory for a digital one.</div>" },
            { title: "The Broken Lamp", body: "Zack was playing ball in the house and smashed a lamp. Terrified, he blamed the cat. His parents found out the truth later. They grounded him for a week—not for the lamp, but for the lie. 'If you had just told us,' his mom said, 'we would have just asked you to clean it up.' Zack realized the punishment for the lie was ten times worse than the punishment for the accident. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> The truth stings for a minute. A lie rots forever. Dealing with consequences is easier than maintaining a lie.</div>" },
            { title: "The Empty Plate", body: "Sarah sat at the dinner table and groaned. 'Meatloaf again? This is gross.' She refused to eat. Her mom didn't argue or cook a second meal. She just put the plate in the fridge. At 9:00 PM, Sarah's stomach was growling like a bear, but the kitchen was closed. The next morning, that leftover meatloaf tasted like the best food she had ever eaten. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Gratitude turns what we have into enough. Complaining turns what we have into nothing.</div>" },
            { title: "The Copycat", body: "Leo didn't want to do his history homework, so he copied his friend's answers on the bus. It was easy. He got an A on the homework. But the next week, there was a test. There was no friend to copy from. Leo stared at the paper, sweating, realizing he knew absolutely nothing. He failed the test and had to retake the class in summer school while his friends were at the pool. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Shortcuts are actually longcuts. Doing the work is the only way to own the skill.</div>" },
            { title: "The Angry Text", body: "Jason got into a fight with his best friend. In a moment of rage, he typed out a cruel text message listing all his friend's insecurities. He hit send. He felt better for exactly ten seconds. Then he felt sick. He tried to apologize, but his friend had already screenshotted it. The friendship ended that day. Jason learned that you can delete a text, but you can't delete how you made someone feel. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Anger makes you stupid. Never send a message when your heart is beating fast.</div>" },
            { title: "The Heavy Backpack", body: "Every time someone was mean to Chloe, she held onto it. She remembered every insult and every slight. It was like putting a rock in her backpack. Soon, her backpack was so heavy with grudges she couldn't enjoy her walk. She saw her friends running ahead, light and happy. She decided to dump the rocks out—to forgive the people who hurt her. She instantly felt light as a feather. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Forgiveness isn't for *them*. It's to lighten *your* load.</div>" },
            { title: "The Snooze Button", body: "Noah wanted to be productive, but when his alarm went off at 7 AM, he hit snooze. Then again. And again. He finally woke up at 7:45, panicked. He missed the bus, forgot his lunch, and arrived at school sweating and stressed without his homework. His entire day was ruined because of one decision he made while half-asleep. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You win the morning, you win the day. When the alarm rings, put your feet on the floor.</div>" },
            { title: "The Rich Man's Trash", body: "A billionaire was asked, 'You have billions of dollars, private jets, and mansions. Is there anything you would trade it all for?' The billionaire thought for a moment and said, 'I would trade every single penny to be 15 years old again, even if I was poor.' You have something money can't buy: Time. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You are already rich in time. Don't waste your fortune on boredom.</div>" },
            { title: "The Comparison Trap", body: "Emma felt ugly because she didn't look like the influencers on Instagram. She didn't realize that the girl in the photo took 500 shots, used 3 filters, and had professional lighting. Emma was comparing her 'behind the scenes' reality to someone else's 'highlight reel.' She put the phone down and looked in the mirror. She was real. The photos were not. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Comparison is the thief of joy. The internet is not real life.</div>" },
            { title: "The Compound Effect", body: "Two planes left Los Angeles for New York. One pilot adjusted his course by just 1 degree south. Nobody noticed. After 6 hours of flying, the first plane landed in New York. The second plane, which was just slightly off, landed in Washington D.C. Small habits, done consistently over time, lead to completely different destinations. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You don't need to be perfect. You just need to be 1% better every day.</div>" },
            { title: "The Echo Canyon", body: "A boy got mad at his brother and shouted 'I hate you!' into a canyon. The canyon shouted back 'I hate you! I hate you!' He got scared. His dad told him to shout 'I believe in you!' The canyon shouted back 'I believe in you! I believe in you!' The boy learned that life is an echo. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> The world gives you back exactly what you put out. Radiate positivity.</div>" },
            { title: "The Two Gardeners", body: "One gardener watered his plants only when he felt like it. Some days he forgot, some days he was too tired. The other gardener watered them every single morning, even when it was raining, even when he was tired. The first garden withered and died. The second garden grew massive and fed the whole neighborhood. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Motivation is fickle. Discipline is reliable. Do it even when you don't want to.</div>" },
            { title: "The Bored Genius", body: "In 1665, a plague hit London. A young student named Isaac Newton was sent home from college. There was no internet, no TV, and no friends around. He was incredibly bored. He sat under a tree, staring at nothing. An apple fell. Because his mind was quiet, he started wondering *why* it fell. In that boredom, he discovered Gravity. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Boredom is not a problem to be fixed; it's an opportunity for your brain to create.</div>" },
            { title: "The Broken Fence", body: "A boy had a bad temper. His father told him to hammer a nail into the wooden fence every time he got angry. The first day, he drove 37 nails. Eventually, he learned to control his temper. His father said, 'Now, pull the nails out.' The boy did, but he saw the wood was ruined. 'The fence will never be the same,' his father said. 'When you say things in anger, they leave scars just like these holes.' <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You can say sorry, but words leave scars. Be careful with your temper.</div>" },
            { title: "The Invisible Backpack", body: "Everyone you meet is wearing an invisible backpack filled with rocks. Some rocks are small (a bad hair day). Some are huge (a sick family member). You can't see the rocks, but you can see them struggling to walk. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Be kind, for everyone you meet is fighting a hard battle you know nothing about.</div>" },
            { title: "The Rusty Bicycle", body: "A boy left his bike in the rain for a month. When he tried to ride it, the chain snapped. He blamed the bike manufacturer. His dad showed him a bike kept in the garage that was 10 years older but worked perfectly. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Things don't break because they are bad; they break because they are neglected. This applies to toys, teeth, and friendships.</div>" },
            { title: "The Thermostat vs. The Thermometer", body: "A thermometer just reflects the temperature of the room. If it's cold, it reads cold. A thermostat *sets* the temperature. If it's cold, it turns on the heat. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Don't just reflect the mood of the room (Thermometer). Be the one who sets the mood (Thermostat).</div>" },
            { title: "The Pottery Class", body: "A pottery teacher split the class. Group A was graded on *quantity* (make 50 pots). Group B was graded on *quality* (make one perfect pot). At the end, Group A had the best pots. Why? Because they practiced 50 times while Group B spent all day overthinking one pot. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Quantity leads to quality. Don't try to be perfect, just do the reps.</div>" },
            { title: "The Crab Bucket", body: "If you put one crab in a bucket, it can crawl out. If you put ten crabs in, none escape. Why? Because when one tries to climb out, the others pull it back down. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Watch out for friends who try to pull you down when you try to improve. Surround yourself with climbers.</div>" },
            { title: "The 10,000 Hour Rule", body: "Mozart wasn't born a genius pianist. He practiced for thousands of hours before he wrote his first masterpiece. Even talent needs work. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Hard work beats talent when talent doesn't work hard.</div>" },
            { title: "The Man in the Arena", body: "It is not the critic who counts; not the man who points out how the strong man stumbles. The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Ignore the haters in the cheap seats. Only listen to feedback from people who are also in the arena.</div>" },
            { title: "The Golden Rule", body: "A classic for a reason. Treat others the way you want to be treated. If you want respect, give respect. If you want kindness, give kindness. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You teach people how to treat you by how you treat them.</div>" },
            { title: "The Marshmallow Test", body: "Kids were offered one marshmallow now, or two if they could wait 15 minutes. The kids who waited ended up being more successful in life. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Patience pays interest. Waiting for what you want often gets you more of it.</div>" },
            { title: "The Starfish Story", body: "A man saw a boy throwing starfish back into the ocean. 'There are millions,' the man said. 'You can't make a difference.' The boy threw one in and said, 'It made a difference to that one.' <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> You can't fix the whole world, but you can fix someone's whole day. Start small.</div>" },
            { title: "The Empty Boat", body: "If a boat hits yours in the fog, you yell at the driver. But if you see the boat is empty, your anger disappears instantly. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Most people who hurt you are 'empty boats'—acting out of their own pain, not trying to target you. Don't take it personally.</div>" },
            { title: "The Diamond in the Mud", body: "If you drop a diamond in the mud, is it still a diamond? Yes. Does it look like one? No. It needs to be cleaned. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Your value doesn't change when you have a bad day or make a mistake. You're just a diamond that needs a wash.</div>" },
            { title: "The Four Minute Mile", body: "For centuries, scientists said running a mile under 4 minutes was impossible. Then Roger Bannister did it. Within a year, dozens of others did it too. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Impossible is often just a mental barrier. Once you see it can be done, it becomes easy.</div>" },
            { title: "The Farmer and the Horse", body: "A farmer's horse ran away. Neighbors said 'Bad luck!' Farmer said 'Maybe.' The horse returned with wild horses. Neighbors said 'Good luck!' Farmer said 'Maybe.' <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Don't be too quick to judge a situation as 'good' or 'bad.' Life is a long story.</div>" },
            { title: "The Sword in the Stone", body: "Arthur didn't pull the sword because he was the strongest. He pulled it because he was *worthy*. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Character matters more than muscle. Being a good person unlocks doors that strength cannot.</div>" },
            { title: "The Tortoise and the Hare", body: "Everyone knows the rabbit was faster. But the rabbit stopped to nap, brag, and snack. The turtle just kept moving. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Consistency is the ultimate superpower. Slow and steady really does win the race.</div>" },
            { title: "The Sharp Axe", body: "Two woodcutters chopped wood. One chopped all day without stopping. The other stopped every hour for 10 minutes. The second one chopped twice as much wood. Why? He spent the 10 minutes sharpening his axe. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Rest is not laziness. Rest is sharpening your axe so you can be more effective.</div>" },
            { title: "The Bamboo Tree", body: "A bamboo seed is watered for 5 years with no growth. Then, in 6 weeks, it grows 90 feet tall. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Overnight success actually takes years of invisible preparation. Keep watering your dreams.</div>" },
            { title: "The Butterfly Effect", body: "A butterfly flapping its wings in Brazil can cause a tornado in Texas. Small actions have huge consequences. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Your small act of kindness today might change someone's entire life tomorrow. Never underestimate your impact.</div>" },
            { title: "The Lesson of the Kite", body: "A kite rises against the wind, not with it. <div class='cheat-code-box'>🔑 <strong>Cheat Code:</strong> Resistance and challenges are what help you fly higher. Don't fear the wind.</div>" }
        ],
        skills: [
            { title: "The Perfect Handshake", body: "Stand up. Make eye contact. Smile. Grip firmly (web to web). Shake twice. Release. It builds instant respect." },
            { title: "The 2-Minute Rule", body: "If a task takes less than 2 minutes (hanging a coat, washing a dish), do it immediately. Never add it to a to-do list." },
            { title: "Active Listening", body: "When someone talks, look at them. Do not think about your response. Just listen. When they finish, ask one question about what they said." },
            { title: "Box Breathing", body: "Anxiety hack: Breathe in for 4 seconds. Hold for 4 seconds. Exhale for 4 seconds. Hold for 4 seconds. Repeat." },
            { title: "How to Apologize", body: "A real apology has 3 parts: 1. 'I am sorry.' 2. 'It was my fault because...' 3. 'Next time I will...' Without part 3, it is just an excuse." },
            { title: "Budgeting 50/30/20", body: "Money rule: 50% for Needs (Rent/Food). 30% for Wants (Fun). 20% for Savings. Always pay your savings first." },
            { title: "Table Manners", body: "Wait until everyone is served before eating. Chew with your mouth closed. Keep elbows off the table while eating. It shows respect for the cook." },
            { title: "The Gratitude Pivot", body: "When you complain ('I have to go to school'), switch 'Have' to 'Get'. 'I GET to go to school.' It changes your brain chemistry." },
            { title: "Changing a Tire", body: "Loosen nuts BEFORE jacking up the car. Jack it up. Remove nuts. Swap tire. Tighten nuts by hand. Lower car. Tighten nuts fully." },
            { title: "How to Introduce People", body: "Say the name of the older/higher status person first. 'Grandma, this is my friend Sam.' It shows social grace." },
            { title: "Making a Bed", body: "Hospital corners: Tuck the foot. Lift the side of the sheet, tuck the excess triangle under, then drop the side. Crisp and tight." },
            { title: "Remembering Names", body: "When introduced, say their name back immediately. 'Nice to meet you, Sarah.' Visualize 'Sarah' written on her forehead." },
            { title: "Writing a Thank You Note", body: "1. Salutation. 2. Mention the specific gift. 3. Say how you will use it. 4. Mention seeing them soon. 5. Sign off." },
            { title: "Doing Laundry", body: "Separate lights and darks. Check pockets! Use cold water to save energy and clothes. Fold immediately to avoid wrinkles." },
            { title: "Unclogging a Sink", body: "Pour boiling water first. Then 1/2 cup baking soda, followed by 1/2 cup vinegar. Cover for 10 mins. Flush with boiling water." },
            { title: "Treating a Burn", body: "Run cool (not freezing) water over it for 10 minutes. Do not pop blisters. Cover loosely with sterile gauze." },
            { title: "Checking Oil", body: "Park on flat ground. Pull dipstick, wipe clean. Re-insert fully. Pull out and check if oil is between min/max lines." },
            { title: "Turning off Water Valve", body: "If a pipe bursts, find the main valve (usually in basement/garage). Turn clockwise until tight. Open faucets to drain." },
            { title: "Sewing a Button", body: "Thread needle, knot the end. Go up through one hole, down the diagonal hole. Repeat 4 times. Do the other pair. Wrap thread around the 'neck' of the button. Tie off." },
            { title: "Using a Fire Extinguisher", body: "PASS: Pull the pin. Aim at the base of fire. Squeeze the handle. Sweep side to side." },
            { title: "Tying a Tie", body: "Four-in-Hand Knot: Wide end over narrow. Around behind. Across front. Up through neck loop. Down through front knot. Tighten." },
            { title: "Reading a Map", body: "Orient the map North. Look for landmarks. Use the scale to estimate distance. Don't rely solely on GPS." },
            { title: "Cooking Pasta", body: "Boil water first. Add lots of salt (should taste like the sea). Don't break the spaghetti. Save some pasta water before draining." },
            { title: "Starting a Fire", body: "Tinder (dry grass), Kindling (small twigs), Fuel (logs). Leave air gaps. Light the tinder. Build up slowly." },
            { title: "Writing a Check", body: "Date. Pay to the Order of (Name). Amount in numbers box. Amount in words on the line. Memo (what for). Sign bottom right." },
            { title: "Ironing a Shirt", body: "Collar first. Then cuffs. Then sleeves. Then the back (yoke). Finally the front panels. Hang immediately." },
            { title: "Plunging a Toilet", body: "Ensure water covers the plunger cup. Create a seal. Push down gently, pull up vigorously. It's the pull that clears the clog." },
            { title: "Using a Compass", body: "Hold flat. Red needle points North. Turn housing to match bearing. Follow the 'direction of travel' arrow." },
            { title: "Identifying Poison Ivy", body: "Leaves of three, let it be. Hairy vine, no friend of mine. White berries, run away." },
            { title: "Folding a Fitted Sheet", body: "Tuck corners inside each other. Lay flat. Fold into a rectangle. It's magic, but it works with practice." },
            { title: "Saving a Document", body: "Ctrl+S (Windows) or Cmd+S (Mac). Do it every 10 minutes. Don't lose your homework." },
            { title: "Escaping a Rip Current", body: "Don't swim against it. Swim parallel to the shore until you are out of the current, then swim back in." },
            { title: "Giving a Toast", body: "Stand up. Keep it short (under 2 mins). Focus on the person, not yourself. End with 'Cheers!' and take a sip." },
            { title: "Scrambling Eggs", body: "Low heat. Butter in pan. Whisk eggs in a bowl first. Pour in. Push gently with spatula. Take off heat *before* they look done." },
            { title: "Using a Drill", body: "Righty-tighty, Lefty-loosey. Keep the drill straight. Apply steady pressure. Don't strip the screw head." },
            { title: "Parallel Parking", body: "Pull up next to the front car. Turn wheel all the way right. Back up until 45 degrees. Straighten wheel. Back in. Turn left to finish." },
            { title: "CPR Basics", body: "Push hard and fast in the center of the chest. 100-120 beats per minute (to the beat of 'Stayin' Alive'). Call 911 first." },
            { title: "Sharpening a Knife", body: "Hold knife at 20-degree angle. Slide across stone/steel like you are slicing a thin layer off it. Repeat both sides." },
            { title: "Finding a Stud", body: "Tap the wall. Hollow sound = no stud. Solid sound = stud. Or look for outlets/switches, studs are usually next to them." },
            { title: "Calculating Tip", body: "Move the decimal one spot left (that's 10%). Double it for 20%. Round up for good service." },
            { title: "Packing a Suitcase", body: "Roll clothes instead of folding to save space and reduce wrinkles. Put heavy shoes at the bottom." },
            { title: "Removing a Stripped Screw", body: "Place a wide rubber band over the screw head. Push screwdriver into the rubber band and turn." },
            { title: "Stop a Nosebleed", body: "Lean forward (not back!). Pinch the soft part of the nose just below the bone. Hold for 10 minutes." },
            { title: "Jump Starting a Car", body: "Red to Dead. Red to Good. Black to Good. Black to Metal (Ground). Start Good car. Start Dead car. Remove in reverse." },
            { title: "Basic Knot: Bowline", body: "The rabbit comes out of the hole, goes around the tree, and goes back into the hole. The 'King of Knots'." },
            { title: "Reading Body Language", body: "Crossed arms = defensive. Leaning in = interested. Looking away = hiding something or bored." },
            { title: "Effective Google Search", body: "Use quotes for exact phrases. Use minus sign (-) to exclude words (e.g. jaguar speed -car)." },
            { title: "Cleaning Windows", body: "Use vinegar and water. Wipe with crumpled newspaper instead of paper towels for a streak-free shine." },
            { title: "Unfreezing a Computer", body: "Ctrl+Alt+Delete (Windows) or Cmd+Option+Esc (Mac). Force quit the bad app." },
            { title: "Measuring without a Ruler", body: "A dollar bill is 6 inches long. Your foot is roughly... a foot. Know your hand span." },
            { title: "Making Coffee", body: "2 tablespoons of grounds for every 6 ounces of water. Use cold, filtered water. Clean the pot." },
            { title: "Setting a Table", body: "Fork on the Left (4 letters). Knife and Spoon on the Right (5 letters). Glass top right." },
            { title: "Shaking Hands", body: "Web-to-web contact. Firm grip but don't crush. 2-3 pumps. Eye contact and a smile are mandatory." },
            { title: "Polishing Shoes", body: "Clean dirt off. Apply polish in circles. Let dry. Buff vigorously with a horsehair brush for shine." },
            { title: "Using Chopsticks", body: "Bottom stick stays still. Top stick moves like a pencil. Hold near the back end, not the tip." },
            { title: "Breaking in Shoes", body: "Wear them with thick socks around the house for short periods. Use a hair dryer on tight spots while wearing them." },
            { title: "Removing Gum from Hair", body: "Don't cut it! Rub peanut butter or olive oil into the gum. It breaks down the stickiness." },
            { title: "Opening a Jar", body: "Run the lid under hot water to expand the metal. Or tap the edge of the lid with a spoon to break the vacuum seal." },
            { title: "Threading a Needle", body: "Cut the thread at an angle. Wet the end. Hold needle against a white background to see the eye." },
            { title: "Identifying Constellations", body: "Find the Big Dipper. The two outer stars of the bowl point directly to the North Star (Polaris)." }
        ]
    },
    social: {
        title: "The Campfire",
        subtitle: "Sparking conversations that burn bright.",
        tags: ["Vibe Check", "Highs & Lows", "Wisdom", "Hot Take", "Humor", "Party Trick"],
        btns: ["Next Question", "Pick Order", "Next Quote", "Next Hot Take", "Next Joke", "Next Trick"],
        checkin: [
            "🥂 <strong>Toast:</strong> Cheers to something good in your life right now.", 
            "🔮 <strong>Manifest:</strong> A personal goal you are chasing right now.", 
            "🙈 <strong>Guilty:</strong> What is your current guilty pleasure?"
        ],
        iceBreakers: [
            "Worst date you've ever been on?", "What is a 'Red Flag' you ignore in dating?", "If you won the lottery, what's the first thing you buy?", "Who here would die first in a zombie apocalypse?", "What is your go-to karaoke song?", "What is the weirdest thing you find attractive?", "If you could get away with a crime, what would it be?", "What was your most embarrassing moment in high school?", "If you could swap lives with one celebrity, who would it be?", "What is your guilty pleasure TV show?", "What is the worst trend you ever followed?", "If you were an alcoholic drink, what would you be?", "What is your biggest pet peeve?", "If you could have dinner with three people (dead or alive), who?", "What is the best concert you have ever been to?", "Have you ever ghosted someone?", "What is a lie you tell often?", "What is the craziest thing you have done for love?", "What is your unpopular food opinion?", "Who is your celebrity crush?", "What's the worst advice you've ever taken?", "Have you ever been caught doing something you shouldn't?", "What is the strangest rumor you've heard about yourself?", "What is your signature dance move?", "If you had to marry one person in this room, who?", "What is the most illegal thing you have done?", "What is a secret talent you have?", "Who was your first crush?", "What is your worst travel story?", "If you were arrested, what would we assume you did?", "What is the most impulsive thing you've ever bought?", "What conspiracy theory do you secretly believe?", "Who in this room is the best liar?", "What is your most toxic trait?", "What is the worst text you've ever accidentally sent?", "If you had a warning label, what would it say?", "What is the longest you've gone without showering?", "What is your favorite curse word?", "What is a song that instantly makes you cry?", "What is your biggest irrational fear?", "If you could read one person's mind, whose?", "If you had to delete all apps but three, which three stay?", "What is your strategy in a horror movie?", "If you could be instantly fluent in any language, which one?", "Who is the last person you stalked on social media?", "What is your go-to order at a dive bar?", "If we were in a bank heist, what would your role be?",
            "What is a movie you have seen more than 10 times?", "What is the most expensive thing you have broken?", "If you could punch one person in the face without consequences, who?", "What is the best prank you've ever pulled?", "What is something you pretend to like but actually hate?", "Who is your 'hall pass' celebrity?", "What is the cringiest thing you posted on social media?", "If you had to eat one meal for the rest of your life, what is it?", "What is the best wifi name you've seen?", "What is a skill you wish you had?", "Who is the most famous person you've met?", "What is your dream car?", "If you could live anywhere, where would it be?", "What is the most useless talent you have?", "What is the best pickup line you've heard?", "Have you ever been in a physical fight?", "What is your favorite board game?", "If you could erase one event from history, what would it be?", "What is the weirdest thing in your fridge right now?", "What is your favorite app?", "If you were a wrestler, what would your entrance song be?", "What is the best compliment you've received?", "What is your biggest regret?", "If you could have any job in the world, what would it be?"
        ],
        quotes: [
            { text: "Friendship is born at that moment when one person says to another, 'What! You too?'", author: "C.S. Lewis" },
            { text: "Good times and crazy friends make the best memories.", author: "Unknown" },
            { text: "A true friend is someone who thinks that you are a good egg even though he knows that you are slightly cracked.", author: "Bernard Meltzer" },
            { text: "There is nothing better than a friend, unless it is a friend with chocolate.", author: "Linda Grayson" },
            { text: "It is the privilege of friendship to talk nonsense, and to have her nonsense respected.", author: "Charles Lamb" },
            { text: "Friends are the family you choose.", author: "Jess C. Scott" },
            { text: "A good friend will help you move. But a best friend will help you move a dead body.", author: "Jim Hayes" },
            { text: "Lots of people want to ride with you in the limo, but you want someone who will take the bus with you when the limo breaks down.", author: "Oprah Winfrey" },
            { text: "True friendship comes when the silence between two people is comfortable.", author: "David Tyson" },
            { text: "A friend is someone who knows all about you and still loves you.", author: "Elbert Hubbard" },
            { text: "Friendship is the only cement that will ever hold the world together.", author: "Woodrow Wilson" },
            { text: "Friends show their love in times of trouble, not in happiness.", author: "Euripides" },
            { text: "Walking with a friend in the dark is better than walking alone in the light.", author: "Helen Keller" },
            { text: "There are no strangers here; Only friends you haven't yet met.", author: "William Butler Yeats" },
            { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
            { text: "A single rose can be my garden... a single friend, my world.", author: "Leo Buscaglia" },
            { text: "Don't walk behind me; I may not lead. Don't walk in front of me; I may not follow. Just walk beside me and be my friend.", author: "Albert Camus" },
            { text: "Friendship consists in forgetting what one gives and remembering what one receives.", author: "Alexander Dumas" },
            { text: "One of the most beautiful qualities of true friendship is to understand and to be understood.", author: "Seneca" },
            { text: "Rare as is true love, true friendship is rarer.", author: "Jean de La Fontaine" },
            { text: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell" },
            { text: "Friendship improves happiness, and abates misery, by doubling our joys, and dividing our grief.", author: "Marcus Tullius Cicero" },
            { text: "A sweet friendship refreshes the soul.", author: "Proverbs 27:9" },
            { text: "Life is an awful, ugly place to not have a best friend.", author: "Sarah Dessen" },
            { text: "Time doesn't take away from friendship, nor does separation.", author: "Tennessee Williams" },
            { text: "Find a group of people who challenge and inspire you; spend a lot of time with them, and it will change your life.", author: "Amy Poehler" },
            { text: "In the cookie of life, friends are the chocolate chips.", author: "Salman Rushdie" },
            { text: "Things are never quite as scary when you've got a best friend.", author: "Bill Watterson" },
            { text: "Friends are the siblings God never gave us.", author: "Mencius" },
            { text: "True friends are like diamonds—bright, beautiful, valuable, and always in style.", author: "Nicole Richie" },
            { text: "Friendship is the golden thread that ties the heart of all the world.", author: "John Evelyn" },
            { text: "It's not what we have in life, but who we have in our life that matters.", author: "Unknown" },
            { text: "A friend knows the song in my heart and sings it to me when my memory fails.", author: "Donna Roberts" },
            { text: "Best friends are the people in your life who make you laugh louder, smile brighter and live better.", author: "Unknown" },
            { text: "Side by side or miles apart, real friends are always close to the heart.", author: "Unknown" },
            { text: "F.R.I.E.N.D.S. Fight for you. Respect you. Include you. Encourage you. Need you. Deserve you. Stand by you.", author: "Unknown" },
            { text: "Making a hundred friends is not a miracle. The miracle is to make a friend who will stand by you when hundreds are against you.", author: "Unknown" },
            { text: "Surround yourself with only people who are going to lift you higher.", author: "Oprah Winfrey" },
            { text: "We didn't realize we were making memories, we just knew we were having fun.", author: "Winnie the Pooh" },
            { text: "The language of friendship is not words but meanings.", author: "Henry David Thoreau" },
            { text: "Be slow to fall into friendship, but when you are in, continue firm and constant.", author: "Socrates" },
            { text: "The greatest gift of life is friendship, and I have received it.", author: "Hubert H. Humphrey" },
            { text: "A friend is one that knows you as you are, understands where you have been, accepts what you have become, and still, gently allows you to grow.", author: "William Shakespeare" },
            { text: "Let us be grateful to the people who make us happy; they are the charming gardeners who make our souls blossom.", author: "Marcel Proust" },
            { text: "Some people go to priests; others to poetry; I to my friends.", author: "Virginia Woolf" },
            { text: "It is one of the blessings of old friends that you can afford to be stupid with them.", author: "Ralph Waldo Emerson" },
            { text: "True friendship is a plant of slow growth.", author: "George Washington" },
            { text: "A friend to all is a friend to none.", author: "Aristotle" },
            { text: "Ultimately the bond of all companionship, whether in marriage or in friendship, is conversation.", author: "Oscar Wilde" },
            { text: "Only a true best friend can protect you from your immortal enemies.", author: "Richelle Mead" },
            { text: "Wishing to be friends is quick work, but friendship is a slow ripening fruit.", author: "Aristotle" },
            { text: "There is nothing on this earth more to be prized than true friendship.", author: "Thomas Aquinas" },
            { text: "The sincere friends of this world are as ship lights in the storm.", author: "Giotto di Bondone" },
            { text: "My best friend is the one who brings out the best in me.", author: "Henry Ford" },
            { text: "Friendship isn't about whom you have known the longest... It's about who came, and never left your side.", author: "Mikaela Tiu" },
            { text: "A snowball in the face is surely the perfect beginning to a lasting friendship.", author: "Markus Zusak" },
            { text: "Friends are medicine for a wounded heart, and vitamins for a hopeful soul.", author: "Steve Maraboli" },
            { text: "Love is blind; friendship closes its eyes.", author: "Friedrich Nietzsche" },
            { text: "Life is partly what we make it, and partly what it is made by the friends we choose.", author: "Tennessee Williams" },
            { text: "No friendship is an accident.", author: "O. Henry" }
        ],
        dynamics: [ 
            { title: "Hot Take:", body: "Voice notes are just phone calls for cowards. Text or call, don't make me listen to a podcast of your life." },
            { title: "Hot Take:", body: "Tipping culture has gone too far. You shouldn't have to tip for someone turning an iPad around at a coffee shop." },
            { title: "Hot Take:", body: "You should not be forced to hang out with your partner's friends if you don't like them." },
            { title: "Hot Take:", body: "Ghosting is a perfectly acceptable way to end a talking stage of less than 3 dates." },
            { title: "Hot Take:", body: "Splitting the check evenly is unfair if one person ordered an appetizer and three cocktails, and the other ordered a salad." },
            { title: "Hot Take:", body: "Pineapple absolutely belongs on pizza." },
            { title: "Hot Take:", body: "Die Hard is NOT a Christmas movie." },
            { title: "Hot Take:", body: "Friends (TV Show) is vastly overrated and hasn't aged well." },
            { title: "Hot Take:", body: "Dogs are better companions than cats. Period." },
            { title: "Hot Take:", body: "It is incredibly rude to recline your seat on an airplane in economy class." },
            { title: "Hot Take:", body: "The person who pays on a first date gets to pick the venue." },
            { title: "Hot Take:", body: "Staying friends with an ex is a bad idea 99% of the time." },
            { title: "Hot Take:", body: "Looking through your partner's phone is a violation of trust, even if you find something." },
            { title: "Hot Take:", body: "Money absolutely buys happiness, up to about $100,000 a year." },
            { title: "Hot Take:", body: "Shows meant to be 'binge-watched' are usually lower quality than weekly releases." },
            { title: "Hot Take:", body: "Sleeping with socks on is a crime against humanity." },
            { title: "Hot Take:", body: "Boneless wings are just chicken nuggets for adults." },
            { title: "Hot Take:", body: "Social media has done more harm to society than good." },
            { title: "Hot Take:", body: "Traveling is stressful and overrated. Staying home is elite." },
            { title: "Hot Take:", body: "You don't need to shower every single day unless you worked out." },
            { title: "Hot Take:", body: "Weddings are a waste of money. Spend it on a house or honeymoon." },
            { title: "Hot Take:", body: "Cold coffee is superior to hot coffee in every way." },
            { title: "Hot Take:", body: "GIFs are cringe and for old people now." },
            { title: "Hot Take:", body: "Audiobooks don't count as 'reading'." },
            { title: "Hot Take:", body: "Breakfast is the worst meal of the day." },
            { title: "Hot Take:", body: "Most meetings could have been an email." },
            { title: "Hot Take:", body: "Dark chocolate is gross. It tastes like dirt." },
            { title: "Hot Take:", body: "Ketchup ruins perfectly good fries." },
            { title: "Hot Take:", body: "Summer is the worst season. It's sweaty and buggy." },
            { title: "Hot Take:", body: "People who back into parking spots are just showing off." },
            { title: "Hot Take:", body: "Buying a house is a bad investment for most people." },
            { title: "Hot Take:", body: "Mint chocolate chip tastes like toothpaste." },
            { title: "Hot Take:", body: "If you are late, you are disrespectful. There is no excuse." },
            { title: "Hot Take:", body: "Reality TV is actually good for your brain because it teaches social dynamics." },
            { title: "Hot Take:", body: "Beer tastes bad. People just pretend to like it." },
            { title: "Hot Take:", body: "The book is not always better than the movie." },
            { title: "Hot Take:", body: "Crocs are the ultimate footwear." },
            { title: "Hot Take:", body: "Cereal is a soup." },
            { title: "Hot Take:", body: "A hot dog is a taco, not a sandwich." },
            { title: "Hot Take:", body: "Toilet paper should hang 'over', not 'under'." },
            { title: "Hot Take:", body: "Making your bed is a waste of time." },
            { title: "Hot Take:", body: "Notifications should be turned off for everything except phone calls." },
            { title: "Hot Take:", body: "Group chats are annoying and should be muted." },
            { title: "Hot Take:", body: "Emojis are better than words for conveying tone." },
            { title: "Hot Take:", body: "Artificial Intelligence will save humanity, not destroy it." },
            { title: "Hot Take:", body: "Aliens definitely exist and have visited Earth." },
            { title: "Hot Take:", body: "Ghosts are real." },
            { title: "Hot Take:", body: "Zodiac signs are completely made up and mean nothing." },
            { title: "Hot Take:", body: "Mayo is the best condiment." },
            { title: "Hot Take:", body: "Sparkling water tastes like TV static." },
            { title: "Hot Take:", body: "Movie theater popcorn is better than any other food." },
            { title: "Hot Take:", body: "Napkins belong in your lap, not tucked in your shirt." },
            { title: "Hot Take:", body: "People who don't like dogs are untrustworthy." },
            { title: "Hot Take:", body: "Cats are evil." },
            { title: "Hot Take:", body: "Disney adults are weird." },
            { title: "Hot Take:", body: "Putting a period at the end of a text message is aggressive." },
            { title: "Hot Take:", body: "Brunch is just an excuse to day drink." },
            { title: "Hot Take:", body: "Avocado toast is worth the hype." },
            { title: "Hot Take:", body: "Crypto is a scam." },
            { title: "Hot Take:", body: "The Oxford Comma is non-negotiable." }
        ],
        skills: [ 
            { title: "Open a Bottle Without an Opener", body: "Use the edge of a lighter or a spoon as a lever under the cap." },
            { title: "The Perfect High Five", body: "Look at the other person's ELBOW, not their hand. You will never miss." },
            { title: "Saber a Champagne Bottle", body: "Find the seam of the bottle. Chill the neck. Slide a blunt knife along the seam and hit the lip firmly." },
            { title: "Exit a Boring Conversation", body: "Say 'I need to grab a drink/food/bathroom' or 'I see [Name], I need to say hi.'" },
            { title: "Remove Red Wine Stains", body: "Pour white wine or salt on the stain immediately to absorb it." },
            { title: "Whistle with Fingers", body: "Make an 'A' shape with index and middle fingers. Fold tongue back. Blow over the tongue." },
            { title: "Rip an Apple in Half", body: "Grip apple with palms, thumbs on top. Pull apart with chest muscles, rolling palms outward." },
            { title: "Coin Knuckle Roll", body: "Balance coin on index finger. Use thumb to push it over middle finger. Catch with ring finger. Practice." },
            { title: "Zippo Snap Start", body: "Hold Zippo by the lid. Snap fingers, hitting the wheel. It lights instantly." },
            { title: "Beer Mat Flip", body: "Place beer mat on edge of table. Flip it 180 degrees with back of hand and catch it." },
            { title: "Cool a Beer Fast", body: "Wrap the bottle/can in a wet paper towel and put it in the freezer for 15 minutes." },
            { title: "Relieve Brain Freeze", body: "Press your tongue flat against the roof of your mouth to warm up the nerves." },
            { title: "Look Good in Photos", body: "Push your forehead slightly forward and down. Put your tongue behind your front teeth. Breathe out." },
            { title: "Remember Drinks", body: "Assign a visual number to people. Person 1 is a Bun (Beer). Person 2 is a Shoe (Wine). Simple memory palace." },
            { title: "Light a Match with One Hand", body: "Fold the matchbook cover back. Press the matchhead inside against the striker. Squeeze and pull." },
            { title: "Tie a Cherry Stem", body: "Use tongue to bend stem in half. Twist it. Use teeth to pull loop tight. Requires practice." },
            { title: "Card Throwing", body: "Grip corner of card between index and middle finger. Flick wrist like snapping a towel. Spin is key." },
            { title: "Napkin Rose", body: "Roll top edge. Twist around finger. Pinch bottom. Pull layers up to form petals." },
            { title: "Shotgun a Beer", body: "Poke hole in bottom side of can. Put mouth over hole. Pop tab. Gravity does the rest." },
            { title: "Identify a Liar", body: "Liars often make *too much* eye contact, cover their mouth, or provide too many unnecessary details." },
            { title: "Remember a Name", body: "Ask 'How do you spell that?' (even for simple names like Smith). It forces you to visualize it." },
            { title: "Pour the Perfect Pint", body: "Tilt glass at 45 degrees. Pour to middle of side. Straighten at the end for the head." },
            { title: "Pen Spin", body: "Hold pen between thumb, index, middle. Push with middle finger to spin around thumb. Catch with index." },
            { title: "Moonwalk", body: "Keep one foot flat, lift heel of other. Slide the flat foot back. Switch heels. Repeat." },
            { title: "Juggle 3 Balls", body: "Throw 1 to other hand in an arc. When it peaks, throw 2 underneath it. When 2 peaks, throw 3. Rhythm." },
            { title: "Tell a Joke", body: "Setup (create expectation), Pause, Punchline (break expectation). Don't laugh at your own joke." },
            { title: "Win Rock Paper Scissors", body: "If they win with Rock, they will likely play Rock again. If they lose, they will switch. React accordingly." },
            { title: "Calculate Day of Week", body: "Learn the Doomsday algorithm. It allows you to calculate the day of the week for any date in history." },
            { title: "Speed Read", body: "Don't say the words in your head (subvocalization). Use a finger to guide your eyes. Focus on the middle of the line." },
            { title: "Pick a Lock (Basic)", body: "Use tension wrench to apply pressure. Use pick to lift pins until they click. (For educational purposes only)." },
            { title: "Lucid Dream", body: "Check reality often (look at hands). When you do it in a dream, you will realize you are dreaming." },
            { title: "Memorize a Deck of Cards", body: "Assign an image to each card (King Hearts = Dad). Create a story linking the images in order." },
            { title: "Hand Whistle", body: "Cup hands together to form air chamber. Blow through thumbs. Adjust seal until it whistles." },
            { title: "Pop a Cork", body: "Twist the bottle, not the cork. Hold the cork firm and let the pressure push it out with a quiet 'hiss'." },
            { title: "Solve a Rubik's Cube", body: "Learn the layer method. Solve white cross, then corners, then middle layer, then top layer." },
            { title: "Human Flag", body: "Grip pole. Top arm pulls, bottom arm pushes. Engage core. Lift legs. Requires immense strength." },
            { title: "Backflip", body: "Jump straight UP, not back. Tuck knees to chest tight. Spin. Spot the landing. Use a trampoline first." },
            { title: "Beatbox Basic", body: "Boots (B), Cats (K), Hats (T). Repeat: Boots-Cats-Boots-Cats. Speed it up." },
            { title: "Card Spring", body: "Bend deck in one hand. Release pressure slowly to shoot cards to other hand. Start close." },
            { title: "Dice Stacking", body: "Use a cup. Swing back and forth to scoop dice. Centrifugal force holds them. Stop cup flat." },
            { title: "Shadow Puppets", body: "Bird: Lock thumbs, flutter fingers. Dog: Fist with thumb up, pinky moves as mouth." },
            { title: "Fast Clap", body: "Don't slap palms. Hit fingers of one hand against palm of other. Move back and forth." },
            { title: "Identify a Song", body: "Listen to the bassline. It usually reveals the song faster than the melody." },
            { title: "Detect a Fake Smile", body: "Real smiles (Duchenne) crinkle the eyes. Fake smiles stop at the mouth." },
            { title: "Make a Cocktail", body: "2 parts Spirit, 1 part Sweet, 1 part Sour. Shake with ice. Strain." },
            { title: "Sharpen a Pencil with a Knife", body: "Push with thumb on the blade, shave wood away from you. Rotate pencil." },
            { title: "Skip a Stone", body: "Flat stone. Low angle. Flick wrist for high spin. Aim for the water surface, not into it." },
            { title: "Blow a Bubblegum Bubble", body: "Flatten gum on roof of mouth. Push tongue through. Blow gently. Seal lips." },
            { title: "Make a Paper Airplane", body: "Fold center. Fold wings down. Add winglets at tips for stability. Throw level." },
            { title: "French Braid", body: "Separate 3 strands. Cross right over middle, then left over middle. Add hair to side strands as you go down." },
            { title: "Parallel Park", body: "Line up rear bumpers. Turn wheel fully. Back up to 45 degrees. Straighten. Back in. Turn fully to curb." },
            { title: "Drive Manual", body: "Clutch in. First gear. Slowly release clutch while giving gas. Find the 'bite point'." },
            { title: "Change a Tire", body: "Loosen nuts. Jack up car. Remove nuts. Swap tire. Hand tighten nuts. Lower car. Wrench tighten." },
            { title: "Start a Fire w/o Matches", body: "Use a lens (glasses/magnifying glass) to focus sun on dry tinder. Or friction (bow drill)." },
            { title: "Read a Compass", body: "Red needle is North. Turn dial to align 'N' with needle. Follow travel arrow." },
            { title: "Tie a Bowline", body: "Rabbit comes out of hole, goes around tree, back in hole. The rescue knot." },
            { title: "Spot North (Stars)", body: "Find Big Dipper. Two end stars of the cup point to Polaris (North Star)." },
            { title: "Whistle with Grass", body: "Hold blade of grass tight between thumbs. Blow through the gap." },
            { title: "Make a Cat's Cradle", body: "Loop string around fingers. Use patterns to transfer string between players." },
            { title: "Hula Hoop", body: "Push forward and back, not side to side. Keep rhythm." }
        ],
        ad_text: "Brought to you by",
        ad_link: "Noble Realty WV &rarr;"
    },
    work: {
        title: "The Huddle",
        subtitle: "Unite the squad. Clear the path. Win the day.",
        tags: ["Warm Up", "Check-In", "Mindset", "The Playbook", "Humor", "Growth"],
        btns: ["Next Question", "Pick Order", "Inspire Me", "Next Drill", "Break Tension", "Next Tip"],
        checkin: [
            "🏆 <strong>Win:</strong> What is one recent victory?", 
            "📍 <strong>Focus:</strong> What is your main priority today?", 
            "🧱 <strong>Block:</strong> What hurdle is standing in your way?"
        ],
        iceBreakers: [ 
            "What was the very first job you ever had?",
            "What is one tool or item you absolutely need to do your job well?",
            "Best career/life advice you ever received?",
            "What is your favorite way to decompress after a long shift?",
            "What is one skill you want to learn this year?",
            "What was the first thing you bought with your own money?",
            "Who is a leader or mentor you admire?",
            "What is the best team you have ever been a part of?",
            "What is your favorite work snack?",
            "How do you handle a highly stressful moment?",
            "What is one thing you are proud of accomplishing this month?",
            "What is one thing you would change about our industry as a whole?",
            "What is the most valuable lesson you've learned from a mistake?",
            "If you could have a 3-day weekend or higher pay, which would you pick?",
            "What music or podcast keeps you going during the day?",
            "What is a hill you are willing to die on professionally?",
            "What is the best professional compliment you've received?",
            "What is your biggest pet peeve in the workplace?",
            "If you could automate one part of your job, what would it be?",
            "What is the most useful app on your phone for work?",
            "What is the best team outing you've ever been on?",
            "What is your 'weird' productivity hack?",
            "What is the most difficult challenge you overcame at work?",
            "What is your favorite way to celebrate a big win?",
            "Who on the team makes you laugh the most?",
            "If you could work from any city in the world, where?",
            "What is one non-work hobby you are passionate about?",
            "What is the most important quality in a good manager?",
            "What is your go-to productivity music?",
            "If you were the CEO for a day, what one rule would you change?",
            "What is a book that changed how you work?",
            "What is your preferred communication style: Email, Slack, or Phone?",
            "If we had a team mascot, what would it be?",
            "What is the best conference or event you've attended?",
            "What is your superpower at work?",
            "What is a habit you are trying to break?",
            "If you could trade jobs with anyone in the company for a day, who?",
            "What is the most disorganized part of your digital life?",
            "Do you prefer open office or private office?",
            "What is your coffee order?",
            "What is the weirdest job you've ever had?",
            "What is a skill you have that no one at work knows about?",
            "If you could have an assistant do one task for you, what would it be?",
            "What is the best lunch spot near here?",
            "How do you stay organized?",
            "What is your favorite quote about success?",
            "If you wrote a book about your career, what would the title be?",
            "What is the biggest risk you've taken in your career?",
            "What motivates you more: praise or money?",
            "Who is the smartest person you know?",
            "What is a piece of technology you can't live without?",
            "If you could learn any language fluently for business, which one?",
            "What is the most creative solution you've seen to a problem?",
            "What is your favorite way to start a Monday?",
            "What is your favorite way to end a Friday?",
            "Do you listen to music while you work?",
            "What is the biggest misconception people have about your job?",
            "What is a 'soft skill' you think is underrated?",
            "If you could retire tomorrow, what would you do?",
            "What is the best team-building activity you've done?",
            "What is your strategy for handling difficult clients?",
            "What is the most important lesson you learned in your first year of work?",
            "If you could give your younger self career advice, what would it be?"
        ],
        quotes: [
            { text: "Individual commitment to a group effort—that is what makes a team work.", author: "Vince Lombardi" },
            { text: "Alone we can do so little; together we can do so much.", author: "Helen Keller" },
            { text: "Talent wins games, but teamwork and intelligence win championships.", author: "Michael Jordan" },
            { text: "It is amazing what you can accomplish if you do not care who gets the credit.", author: "Harry Truman" },
            { text: "Coming together is a beginning. Keeping together is progress. Working together is success.", author: "Henry Ford" },
            { text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill" },
            { text: "The strength of the team is each individual member. The strength of each member is the team.", author: "Phil Jackson" },
            { text: "You don't have to be great to start, but you have to start to be great.", author: "Zig Ziglar" },
            { text: "The only way to do great work is to love what you do.", author: "Steve Jobs" },
            { text: "In the middle of difficulty lies opportunity.", author: "Albert Einstein" },
            { text: "Great things in business are never done by one person. They're done by a team of people.", author: "Steve Jobs" },
            { text: "If you want to go fast, go alone. If you want to go far, go together.", author: "African Proverb" },
            { text: "None of us is as smart as all of us.", author: "Ken Blanchard" },
            { text: "Collaboration allows teachers to capture each other's fund of collective intelligence.", author: "Mike Schmoker" },
            { text: "Teamwork is the ability to work together toward a common vision.", author: "Andrew Carnegie" },
            { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
            { text: "Quality means doing it right when no one is looking.", author: "Henry Ford" },
            { text: "Innovation distinguishes between a leader and a follower.", author: "Steve Jobs" },
            { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
            { text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates" },
            { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
            { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
            { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
            { text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill" },
            { text: "Opportunities don't happen. You create them.", author: "Chris Grosser" },
            { text: "Try not to become a man of success. Rather become a man of value.", author: "Albert Einstein" },
            { text: "Stop chasing the money and start chasing the passion.", author: "Tony Hsieh" },
            { text: "All progress takes place outside the comfort zone.", author: "Michael John Bobak" },
            { text: "The only place where success comes before work is in the dictionary.", author: "Vidal Sassoon" },
            { text: "Whatever the mind of man can conceive and believe, it can achieve.", author: "Napoleon Hill" },
            { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
            { text: "A goal without a plan is just a wish.", author: "Antoine de Saint-Exupéry" },
            { text: "Leadership is not about being in charge. It is about taking care of those in your charge.", author: "Simon Sinek" },
            { text: "Effort only fully releases its reward after a person refuses to quit.", author: "Napoleon Hill" },
            { text: "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.", author: "Socrates" },
            { text: "Do not wait; the time will never be 'just right'.", author: "Napoleon Hill" },
            { text: "Action is the foundational key to all success.", author: "Pablo Picasso" },
            { text: "Setting goals is the first step in turning the invisible into the visible.", author: "Tony Robbins" },
            { text: "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work.", author: "Steve Jobs" },
            { text: "Persistence is very important. You should not give up unless you are forced to give up.", author: "Elon Musk" },
            { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
            { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
            { text: "Keep your eyes on the stars, and your feet on the ground.", author: "Theodore Roosevelt" },
            { text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius" },
            { text: "Failure is the condiment that gives success its flavor.", author: "Truman Capote" },
            { text: "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.", author: "Colin Powell" },
            { text: "The successful warrior is the average man, with laser-like focus.", author: "Bruce Lee" },
            { text: "If you really look closely, most overnight successes took a long time.", author: "Steve Jobs" },
            { text: "The question isn't who is going to let me; it's who is going to stop me.", author: "Ayn Rand" },
            { text: "Be so good they can't ignore you.", author: "Steve Martin" },
            { text: "Work hard in silence, let your success be your noise.", author: "Frank Ocean" },
            { text: "Dreams don't work unless you do.", author: "John C. Maxwell" },
            { text: "Go the extra mile. It's never crowded there.", author: "Wayne Dyer" },
            { text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair" },
            { text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
            { text: "Focus on being productive instead of busy.", author: "Tim Ferriss" },
            { text: "If you cannot do great things, do small things in a great way.", author: "Napoleon Hill" },
            { text: "Nothing will work unless you do.", author: "Maya Angelou" },
            { text: "Think big and don't listen to people who tell you it can't be done.", author: "Diego Marcheset" },
            { text: "Don't be distracted by criticism. Remember, the only taste of success some people get is to take a bite out of you.", author: "Zig Ziglar" }
        ],
        dynamics: [ // "THE PLAYBOOK" - Leadership & Strategy for Teams
            { title: "The Pre-Mortem", body: "Most teams do a 'Post-Mortem' after a project fails to find out why. <br><br><strong>🔑 The Drill:</strong> Imagine it is 6 months from now and our current project has failed completely. Write down 3 reasons *why* it failed. Now, let's fix those 3 things before they happen." },
            { title: "The 80/20 Rule", body: "20% of your activities result in 80% of your success. The other 80% is just 'busy work.' <br><br><strong>🔑 The Drill:</strong> Identify the top 2 tasks that actually move the needle for this team. Permission granted to spend less time on everything else." },
            { title: "The Silo Breaker", body: "Teams often get stuck in their own bubbles. <br><br><strong>🔑 The Drill:</strong> Who is one person *outside* of this team/department that we need to communicate with this week? What do we need to ask them?" },
            { title: "Radical Candor", body: "Being 'nice' can sometimes be toxic if it means we aren't being honest. <br><br><strong>🔑 The Drill:</strong> Is there a hard truth or a problem we are avoiding discussing because it's uncomfortable? Let's put it on the table now." },
            { title: "The 'Bus Factor'", body: "If one key person got hit by a bus tomorrow, would the team collapse? <br><br><strong>🔑 The Drill:</strong> Identify one critical task that only ONE person knows how to do. That person needs to teach someone else how to do it this week." },
            { title: "Disagree and Commit", body: "Great teams argue passionately, but once a decision is made, they support it 100%. <br><br><strong>🔑 The Drill:</strong> Are there any past decisions we are still secretly fighting against? It's time to get on the bus or get off." },
            { title: "The Pygmalion Effect", body: "People tend to rise (or fall) to the level of expectations placed on them. <br><br><strong>🔑 The Drill:</strong> Name one person on the team who has potential they aren't seeing in themselves yet. How can we challenge them to step up?" },
            { title: "Parkinson's Law", body: "Work expands to fill the time available for its completion. If you give yourself a week, it takes a week. <br><br><strong>🔑 The Drill:</strong> What is a deadline we can shorten to create momentum and focus?" },
            { title: "The 5 Whys", body: "When a problem happens, the first reason is usually just a symptom. <br><br><strong>🔑 The Drill:</strong> Think of a recent problem. Ask 'Why?' 5 times in a row to find the root cause (e.g., The machine broke -> Why? -> Not maintained -> Why? -> No schedule -> Why? -> No owner)." },
            { title: "Extreme Ownership", body: "Bad teams blame others. Great teams look in the mirror. <br><br><strong>🔑 The Drill:</strong> Instead of saying 'They didn't give us what we needed,' ask 'What could WE have done differently to get what we needed?'" },
            { title: "The Energy Audit", body: "Time is managed, but energy is generated. <br><br><strong>🔑 The Drill:</strong> What represents the biggest 'energy drain' for the team right now? Is it a specific meeting, a broken tool, or a confusing process? How do we kill it?" },
            { title: "The Zone of Genius", body: "Everyone has things they are good at but hate (Competence) and things they love and are elite at (Genius). <br><br><strong>🔑 The Drill:</strong> Is anyone currently spending more than 50% of their time outside their Zone of Genius? How can we shift that?" },
            { title: "The 'No' Strategy", body: "Strategy is not just what you choose to do; it's what you choose *not* to do. <br><br><strong>🔑 The Drill:</strong> What is one project or initiative we should kill right now to free up resources for the main goal?" },
            { title: "The Daily Standup", body: "Long meetings kill momentum. Short check-ins build it. <br><br><strong>🔑 The Drill:</strong> For the next week, all status updates must be done standing up. If it takes longer than 15 minutes, it's too long." },
            { title: "High Agency", body: "Low Agency people wait for instructions. High Agency people find a way to get the result no matter what. <br><br><strong>🔑 The Drill:</strong> Where are we waiting for permission when we should just be taking action?" },
            { title: "First Principles Thinking", body: "Boil things down to the most fundamental truths and reason up from there. <br><br><strong>🔑 The Drill:</strong> Don't just do it because 'that's how we've always done it.' Ask: 'If we started this company today, would we still do it this way?'" },
            { title: "The Flywheel Effect", body: "Greatness is not a single push, but small pushes consistently in the same direction. <br><br><strong>🔑 The Drill:</strong> What is the one repetitive action we can do every day that builds momentum over time?" },
            { title: "Eat the Frog", body: "Do the hardest, most important task first thing in the morning. <br><br><strong>🔑 The Drill:</strong> Everyone write down their 'Frog' for tomorrow. Do not open email until the Frog is eaten." },
            { title: "Deep Work", body: "Distracted work is low value. Focused work is high value. <br><br><strong>🔑 The Drill:</strong> Schedule a 2-hour block of 'Deep Work' this week where no Slack, email, or meetings are allowed." },
            { title: "The 2-Pizza Rule", body: "If a team can't be fed with 2 pizzas, it's too big. <br><br><strong>🔑 The Drill:</strong> Look at our next meeting invite list. Who really doesn't need to be there? Let them have their time back." },
            { title: "Bias for Action", body: "Speed matters in business. Many decisions are reversible. <br><br><strong>🔑 The Drill:</strong> What decision have we been analyzing for too long? Make a choice today and adjust later if needed." },
            { title: "Customer Obsession", body: "Start with the customer and work backward. <br><br><strong>🔑 The Drill:</strong> In our last discussion, did we mention the customer's needs even once? If not, we are drifting." },
            { title: "The Growth Mindset", body: "Talent is not fixed. You can learn anything. <br><br><strong>🔑 The Drill:</strong> What is a skill the team lacks? Instead of hiring for it, who wants to learn it?" },
            { title: "Feedback Loops", body: "You can't improve what you don't measure. <br><br><strong>🔑 The Drill:</strong> What is one key metric we are ignoring? How can we track it starting today?" },
            { title: "Celebrate Small Wins", body: "Momentum comes from feeling like you are winning. <br><br><strong>🔑 The Drill:</strong> Stop and clap for something small right now. A bug fixed, a call made, a deadline met." },
            { title: "Hanlon's Razor", body: "Never attribute to malice that which is adequately explained by stupidity (or busyness). <br><br><strong>🔑 The Drill:</strong> If you are mad at a colleague, assume they are just busy or confused, not trying to hurt you. Reach out." },
            { title: "The IKEA Effect", body: "People love what they help build. <br><br><strong>🔑 The Drill:</strong> Don't just give orders. Ask the team to help design the solution. They will fight harder for it." },
            { title: "Batching", body: "Context switching kills productivity. <br><br><strong>🔑 The Drill:</strong> Group similar tasks (emails, calls) and do them all at once. Don't multitask." },
            { title: "Essentialism", body: "Less but better. <br><br><strong>🔑 The Drill:</strong> If you could only accomplish ONE thing this quarter, what would it be? Does our calendar reflect that?" },
            { title: "The Check-In", body: "Are we human beings or human doings? <br><br><strong>🔑 The Drill:</strong> Spend the first 5 minutes of the meeting talking about life, not work. Connection builds trust." }
        ],
        skills: [ 
            { title: "Box Breathing", body: "In for 4s, Hold for 4s, Out for 4s, Hold for 4s. Instantly lowers heart rate in stressful situations." },
            { title: "The 2-Minute Rule", body: "If a quick task takes less than 2 minutes, do it instantly. Don't let small things pile up." },
            { title: "De-escalation", body: "When someone is angry, lower your voice, validate their frustration ('I hear you'), and focus on the solution, not the blame." },
            { title: "Saying 'No' Politely", body: "Say: 'I can't prioritize that right now without dropping other balls. Which would you like me to do first?'" },
            { title: "The High Five", body: "Celebrating small wins releases dopamine and builds momentum. Don't wait for the championship to celebrate." },
            { title: "Task Batching", body: "Group similar tasks together. Do all your prep work in one block to save mental energy." },
            { title: "Praise Publicly, Correct Privately", body: "Never discipline or correct a teammate in front of others. Always save it for a private, respectful conversation." },
            { title: "Active Listening", body: "Listen to understand, not to reply. Wait 2 seconds after someone finishes speaking before you talk." },
            { title: "The Eisenhower Matrix", body: "Sort tasks: Urgent/Important (Do now), Not Urgent/Important (Schedule for later), Urgent/Not Important (Delegate), Neither (Delete)." },
            { title: "Visualization", body: "Before you start a hard task, close your eyes and visualize yourself finishing it successfully. It primes your brain for the win." },
            { title: "The 5 Why's", body: "When a problem happens, ask 'Why?' 5 times to get to the root cause, not just the symptom." },
            { title: "Eat the Frog", body: "Do your hardest, most dreaded task first thing in the morning. The rest of the day is easy." },
            { title: "Clear Communication", body: "BLUF: Bottom Line Up Front. Put the main point in the first sentence, then give details." },
            { title: "The Check-Back", body: "When receiving complex instructions, repeat them back in your own words to ensure understanding." },
            { title: "Boundary Setting", body: "Protect your time off. You can't play hard if you don't rest hard." },
            { title: "Focus", body: "Multitasking is a myth. Focus on one thing at a time to do it faster and better." },
            { title: "Clean Space", body: "A cluttered physical space creates a cluttered mental state. Reset your space at the end of every shift." },
            { title: "The 80/20 Rule", body: "20% of your efforts yield 80% of your results. Focus on the high-impact tasks." },
            { title: "Ownership", body: "Own your mistakes immediately. Don't make excuses. Say: 'I made a mistake, here is how I am fixing it.'" },
            { title: "Inbox Zero", body: "Touch an email once: Reply, Delete, Archive, or Defer. Don't open it and close it without action." },
            { title: "Time Blocking", body: "Schedule your work in blocks on your calendar. Treat these blocks like meetings you can't miss." },
            { title: "The Pomodoro Technique", body: "Work for 25 minutes. Break for 5 minutes. After 4 cycles, take a longer break." },
            { title: "Networking", body: "It's not about asking for favors. It's about asking 'How can I help you?' Give value first." },
            { title: "Negotiation", body: "Silence is powerful. Make your offer, then stop talking. The next person to speak loses." },
            { title: "Public Speaking", body: "Don't memorize a script. Know your key points. Make eye contact with one person at a time." },
            { title: "Meeting Etiquette", body: "Arrive 2 minutes early. Have an agenda. If you aren't adding value, ask to leave." },
            { title: "Decision Making", body: "Gather 70% of the information, then decide. Waiting for 100% takes too long." },
            { title: "Stress Management", body: "Control the controllables. Let go of the rest. Worrying creates suffering without solving problems." },
            { title: "Goal Setting", body: "SMART Goals: Specific, Measurable, Achievable, Relevant, Time-bound." },
            { title: "Mentorship", body: "Find someone who is where you want to be. Ask them specifically how they got there." },
            { title: "Adaptability", body: "The only constant is change. Don't fight it. Ask 'How can I use this change to my advantage?'" },
            { title: "Delegation", body: "If someone can do it 80% as well as you, let them do it. It frees you up for higher-level work." },
            { title: "Conflict Resolution", body: "Use 'I' statements ('I feel frustrated when...') instead of 'You' statements ('You always...')." },
            { title: "Self-Discipline", body: "Doing what needs to be done, even when you don't feel like it." },
            { title: "Emotional Intelligence", body: "Recognize your own emotions and the emotions of others. Pause before reacting." },
            { title: "Critical Thinking", body: "Don't accept things at face value. Ask 'Is this true?' and 'What is the evidence?'" },
            { title: "Creativity", body: "Connect dots that others don't see. There is always more than one way to solve a problem." },
            { title: "Resilience", body: "Bounce back from failure. See failure as feedback, not a final verdict." },
            { title: "Personal Branding", body: "What do people say about you when you leave the room? Be intentional about your reputation." },
            { title: "Financial Literacy", body: "Spend less than you earn. Invest the difference. Understand compound interest." },
            { title: "Cybersecurity", body: "Use a password manager. Enable 2-Factor Authentication. Don't click suspicious links." },
            { title: "Speed Reading", body: "Scan for headings and bold text. You don't need to read every word to get the main idea." },
            { title: "Note Taking", body: "Don't transcribe everything. Write down key points and action items only." },
            { title: "Brainstorming", body: "No bad ideas in the first round. Quantity over quality. Filter later." },
            { title: "Giving Feedback", body: "The Sandwich Method: Positive comment, Constructive criticism, Positive comment." },
            { title: "Receiving Feedback", body: "Say 'Thank you.' Don't get defensive. Treat it as data to help you improve." },
            { title: "Managing Up", body: "Make your boss's life easier. Anticipate their needs before they ask." },
            { title: "Virtual Meetings", body: "Camera on. Mute when not speaking. Look at the camera, not the screen." },
            { title: "Work-Life Balance", body: "Set clear boundaries. When work is done, turn it off completely." },
            { title: "Continuous Learning", body: "Read books, listen to podcasts, take courses. Never stop growing." }
        ],
        ad_text: "Brought to you by",
        ad_link: "Noble Realty WV &rarr;"
    }
};