// Validates all decks, then inlines data + engine into src/shell.html → index.html,
// and stamps sw.js with a content hash so installed copies pick up the new build.
import fs from "fs"; import path from "path"; import crypto from "crypto";
import { loadAll, ROOT } from "./load.mjs";
import { validate, report } from "./validate.mjs";

const all = await loadAll();
const r = validate(all); report(r);
if (r.errors.length) { console.error("\nBuild aborted — fix errors above."); process.exit(1); }

const decks = all.decks.map(({ file, ...d }) => d);
const ex = all.extra;
const json = v => JSON.stringify(v).replace(/</g, "\\u003c"); // no "</script>" breakouts
const data = [
  `const DECKS=${json(decks)};`,
  `const GRAMMAR=${json(ex["spanish-grammar"]?.default || [])};`,
  `const VERBS=${json(ex["spanish-verbs"]?.default || [])};`,
  `const PERSONS=${json(ex["spanish-verbs"]?.PERSONS || [])};`,
  `const FIELD=${json(ex["field"]?.default || [])};`,
].join("\n");

const shell = fs.readFileSync(path.join(ROOT, "src/shell.html"), "utf8");
const engine = fs.readFileSync(path.join(ROOT, "src/engine.js"), "utf8");
const html = shell.replace("/*@DATA@*/", () => data).replace("/*@ENGINE@*/", () => engine);
fs.writeFileSync(path.join(ROOT, "index.html"), html);

// Audit log: every card that carries a `verified` URL.
const ver = ["# Verification log", "", "Generated by `tools/build.mjs`. One row per card: the source on the card and the page it was checked against.", "",
  "Verification method (Oct 2026): web search results quoting the primary source (opinion, U.S. Code, C.F.R., agency PDF). Direct fetching was blocked in the build environment.", ""];
for (const d of all.decks) {
  const rows = d.cards.filter(c => c.verified);
  if (!rows.length) continue;
  ver.push(`## ${d.meta.name}`, "", "| Card | Source | Checked against |", "|---|---|---|");
  for (const c of rows) ver.push(`| \`${c.id}\` | ${c.source.replace(/\|/g, "\\|")} | ${c.verified} |`);
  ver.push("");
}
fs.writeFileSync(path.join(ROOT, "VERIFICATION.md"), ver.join("\n"));

// UNVERIFIED.md: cards whose only check was a secondary source (encyclopedia, brief sites, blogs).
const PRIMARY = /(govinfo\.gov|law\.cornell\.edu|justia\.com|supremecourt\.gov|cbp\.gov|dhs\.gov|law\.resource\.org|chanrobles\.com|uscourts\.gov|faa\.gov|oqlf\.gouv\.qc\.ca|saaq\.gouv\.qc\.ca|fema\.gov|marines\.mil|larousse\.fr|ulaval\.ca|thecanadianencyclopedia\.ca|skybrary\.aero)/;
const sec = ["| Card | Source | Checked via |", "|---|---|---|"];
for (const d of all.decks) for (const c of d.cards) if (c.verified && !PRIMARY.test(c.verified))
  sec.push(`| \`${c.id}\` | ${c.source.replace(/\|/g, "\\|")} | ${new URL(c.verified).hostname} |`);
const uvPath = path.join(ROOT, "UNVERIFIED.md");
const uv = fs.readFileSync(uvPath, "utf8").replace(/<!-- secondary:start[^>]*-->[\s\S]*?<!-- secondary:end -->/,
  m => m.split("\n")[0] + "\n" + sec.join("\n") + "\n<!-- secondary:end -->");
fs.writeFileSync(uvPath, uv);

const hash = crypto.createHash("sha256").update(html).digest("hex").slice(0, 10);
const sw = fs.readFileSync(path.join(ROOT, "src/sw.js"), "utf8").replace("@VERSION@", hash);
fs.writeFileSync(path.join(ROOT, "sw.js"), sw);
console.log(`\nWrote index.html (${(html.length / 1024).toFixed(0)} KB), sw.js (cache pk-${hash})`);
