// CASE LAW — Fourth Amendment, border, arrest and liability cases.
// Every card: cite + year verified against the URL in `verified` (see VERIFICATION.md).
// binding: "SCOTUS" and "2d Cir." bind in Vermont; anything else is "persuasive (Nth Cir.)".
// Field lines restate the holding as it applies on the road — they add no rules of their own.
export default {
  meta: { id:"caselaw", name:"Case Law", short:"LAW", color:"#7FA3C8", order:3, requireVerified:true,
    blurb:"Core Supreme Court and Second Circuit cases. Vermont sits in the 2d Circuit.",
    subModes:["browse"] },
  categories: {
    "Stops & Suspicion":      { why:"Every stop you make has to fit one of these standards." },
    "Border & Checkpoints":   { why:"The border-search exception and checkpoint rules are what make BP authority different." },
    "Vehicles & Searches":    { why:"Most enforcement contact happens in or around a vehicle." },
    "Statements":             { why:"An unwarned custodial statement can't be used at trial." },
    "Force":                  { why:"Every use of force is judged against these cases." },
    "Liability":              { why:"Tells you what remedies exist when an agent is sued." },
    "Which Case Governs?":    { why:"Picking the right case quickly is how you articulate your legal basis." },
  },
  cards: [
  // ---------------- Stops & Suspicion ----------------
  { id:"cl-terry", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"Terry v. Ohio", cite:"392 U.S. 1", year:1968,
    back:"Police may briefly stop a person on reasonable suspicion that criminal activity is afoot, and frisk for weapons if they reasonably suspect the person is armed and dangerous. Neither requires probable cause.",
    rule:"Stop = reasonable suspicion of crime. Frisk = reasonable suspicion of armed and dangerous.",
    field:"Articulate two separate justifications: one for the stop, one for the pat-down.",
    why:"The foundation for every investigative detention short of arrest.",
    source:"Terry v. Ohio, 392 U.S. 1 (1968)", verified:"https://www.acluohio.org/cases/terry-v-ohio-392-us-1-1968/" },
  { id:"cl-brignoni", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"United States v. Brignoni-Ponce", cite:"422 U.S. 873", year:1975,
    back:"Away from the border and its functional equivalents, a roving patrol may stop a vehicle only on specific articulable facts, plus rational inferences, that reasonably warrant suspicion the vehicle contains aliens who may be illegally in the country. Apparent Mexican ancestry alone is not enough.",
    rule:"Roving-patrol stop = reasonable suspicion. Apparent ethnicity can be a factor but never the only one.",
    field:"Build the stop on articulable factors: driving behavior, the vehicle and its load, the area, recent crossings, your experience.",
    why:"The governing standard for every roving-patrol vehicle stop.",
    source:"United States v. Brignoni-Ponce, 422 U.S. 873 (1975)", verified:"https://en.wikipedia.org/wiki/United_States_v._Brignoni-Ponce" },
  { id:"cl-cortez", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"United States v. Cortez", cite:"449 U.S. 411", year:1981,
    back:"Reasonable suspicion requires a particularized and objective basis for suspecting the particular person stopped, judged on the whole picture. Trained Border Patrol agents may draw inferences from facts that would mean nothing to an untrained observer.",
    rule:"Totality of the circumstances, weighed as a trained agent would weigh them.",
    field:"Your training and experience (sign cutting, crossing patterns, timing) count as part of the basis. Write them into the report.",
    why:"Shows that agent expertise is part of reasonable suspicion. It came out of a Border Patrol sign-cutting case.",
    source:"United States v. Cortez, 449 U.S. 411 (1981)", verified:"https://supreme.justia.com/cases/federal/us/449/411/" },
  { id:"cl-arvizu", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"United States v. Arvizu", cite:"534 U.S. 266", year:2002,
    back:"Reasonable suspicion supported a Border Patrol stop on a remote road even though each factor, taken alone, had an innocent explanation. Courts may not use a 'divide-and-conquer' analysis that discards factors one at a time.",
    rule:"Factors are weighed together. Innocent-looking facts can add up to reasonable suspicion.",
    field:"List every factor in your report, including the ones that are weak on their own.",
    why:"Blocks the defense tactic of picking off your factors one at a time.",
    source:"United States v. Arvizu, 534 U.S. 266 (2002)", verified:"https://www.law.cornell.edu/supct/html/00-1519.ZS.html" },
  { id:"cl-sokolow", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"United States v. Sokolow", cite:"490 U.S. 1", year:1989,
    back:"Reasonable suspicion existed from a set of factors (cash payment, short trip to a source city, travel under another name, nervousness, no checked bags), each consistent with innocent travel but suspicious taken together.",
    rule:"Totality of the circumstances. There is no required 'ongoing criminal activity' fact.",
    field:"Probabilistic facts count. Articulate why the combination is suspicious.",
    why:"Confirms the whole-picture test outside the border context.",
    source:"United States v. Sokolow, 490 U.S. 1 (1989)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-490/pdf/USREPORTS-490-1.pdf" },
  { id:"cl-wardlow", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"Illinois v. Wardlow", cite:"528 U.S. 119", year:2000,
    back:"Presence in a high-crime area alone isn't reasonable suspicion, but location is relevant. Unprovoked headlong flight on seeing police, combined with the area, justified a stop.",
    rule:"Unprovoked flight + context can supply reasonable suspicion. Location alone cannot.",
    field:"Flight is a strong factor. Document what prompted it and the setting it happened in.",
    why:"Flight on seeing a marked unit is a common fact pattern.",
    source:"Illinois v. Wardlow, 528 U.S. 119 (2000)", verified:"https://law.justia.com/cases/federal/us/528/119/" },
  { id:"cl-glover", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"Kansas v. Glover", cite:"589 U.S. ___, 140 S. Ct. 1183", year:2020,
    back:"After running a plate and learning the registered owner's license is revoked, an officer may stop the vehicle on the commonsense inference that the owner is driving, unless the officer has information negating that inference.",
    rule:"Registered owner revoked + nothing suggesting someone else is driving = reasonable suspicion.",
    field:"If you can see the driver doesn't match the owner's description, the inference is gone.",
    why:"Lets a records check alone justify a stop.",
    source:"Kansas v. Glover, 589 U.S. ___, 140 S. Ct. 1183 (2020)", verified:"https://www.supremecourt.gov/opinions/19pdf/589us2r21_a7bf.pdf" },
  { id:"cl-heien", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"Heien v. North Carolina", cite:"574 U.S. 54", year:2014,
    back:"An officer's reasonable mistake of law can supply the reasonable suspicion for a traffic stop (a single brake light out, under an ambiguous state statute).",
    rule:"A reasonable mistake of law doesn't invalidate the stop. An unreasonable one does.",
    field:"Know the traffic code you rely on. The mistake must be one a reasonable officer could make.",
    why:"Your basis for the stop survives an honest, reasonable misreading of an unclear statute.",
    source:"Heien v. North Carolina, 574 U.S. 54 (2014)", verified:"https://law.justia.com/cases/federal/us/574/54/" },
  { id:"cl-delgado", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"INS v. Delgado", cite:"466 U.S. 210", year:1984,
    back:"Factory surveys where agents questioned workers about citizenship while others stood at the exits did not seize the workforce. Questioning about identity or citizenship is not by itself a seizure.",
    rule:"Asking about status isn't a seizure unless a reasonable person would believe they weren't free to leave.",
    field:"Consensual questioning needs no suspicion. Once you restrain movement, you need reasonable suspicion.",
    why:"Draws the line between a consensual status question and a detention.",
    source:"INS v. Delgado, 466 U.S. 210 (1984)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-466/pdf/USREPORTS-466-210.pdf" },
  { id:"cl-drayton", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"United States v. Drayton", cite:"536 U.S. 194", year:2002,
    back:"Officers who boarded a bus and asked passengers questions and for consent to search did not seize them. The Fourth Amendment does not require telling people they may refuse.",
    rule:"An encounter is consensual if a reasonable person would feel free to decline. No advisement of rights is required.",
    field:"Keep transit checks consensual: a reasonable person must feel free to decline.",
    why:"Governs consensual transportation checks.",
    source:"United States v. Drayton, 536 U.S. 194 (2002)", verified:"https://www.law.cornell.edu/supremecourt/text/536/194" },
  { id:"cl-bostick", type:"flip", cat:"Stops & Suspicion", binding:"SCOTUS",
    front:"Florida v. Bostick", cite:"501 U.S. 429", year:1991,
    back:"A police encounter on a bus is not automatically a seizure. The test is whether a reasonable person would feel free to decline the officers' requests or otherwise end the encounter.",
    rule:"The 'free to decline or terminate' test applies in confined spaces like buses.",
    field:"Consent questions on a bus are allowed. How you conduct them decides whether they stay consensual.",
    why:"The baseline test for consensual encounters.",
    source:"Florida v. Bostick, 501 U.S. 429 (1991)", verified:"https://www.law.cornell.edu/supct/html/89-1717.ZO.html" },

  // ---------------- Border & Checkpoints ----------------
  { id:"cl-martinez-fuerte", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"United States v. Martinez-Fuerte", cite:"428 U.S. 543", year:1976,
    back:"Routine stops for brief questioning at a reasonably located permanent checkpoint are constitutional without individualized suspicion. Referral to secondary for limited further questioning also needs no individualized suspicion.",
    rule:"Checkpoint stop and brief questioning = no suspicion needed. Searching the vehicle is a different question (see Ortiz).",
    field:"At a checkpoint you may stop, ask and refer to secondary. To search, you need consent or probable cause.",
    why:"Legal basis for immigration checkpoints.",
    source:"United States v. Martinez-Fuerte, 428 U.S. 543 (1976)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-428/pdf/USREPORTS-428-543.pdf" },
  { id:"cl-ortiz", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"United States v. Ortiz", cite:"422 U.S. 891", year:1975,
    back:"At traffic checkpoints removed from the border and its functional equivalents, Border Patrol may not search private vehicles without consent or probable cause.",
    rule:"Interior checkpoint search = consent or probable cause.",
    field:"Stopping a car at the checkpoint and opening its trunk need different justifications.",
    why:"Keeps checkpoint stops from turning into suspicionless searches.",
    source:"United States v. Ortiz, 422 U.S. 891 (1975)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-422/pdf/USREPORTS-422-891.pdf" },
  { id:"cl-almeida", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"Almeida-Sanchez v. United States", cite:"413 U.S. 266", year:1973,
    back:"A roving-patrol search of a car about 25 air miles from the border, made without a warrant, probable cause or consent, violated the Fourth Amendment. A statute authorizing searches within a 'reasonable distance' doesn't override that.",
    rule:"Away from the border or its functional equivalent, a vehicle search needs probable cause or consent.",
    field:"8 U.S.C. § 1357(a)(3) authority to search conveyances is limited by the Fourth Amendment. It is not a suspicionless search power.",
    why:"Defines the limit of the statutory 'reasonable distance' authority.",
    source:"Almeida-Sanchez v. United States, 413 U.S. 266 (1973)", verified:"https://en.wikipedia.org/wiki/Almeida-Sanchez_v._United_States" },
  { id:"cl-flores-montano", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"United States v. Flores-Montano", cite:"541 U.S. 149", year:2004,
    back:"At the international border, the government may remove, disassemble and reassemble a vehicle's fuel tank without any suspicion.",
    rule:"Border vehicle searches, including taking the vehicle apart, are routine. No suspicion needed.",
    field:"Applies at the border and its functional equivalent, not at interior stops.",
    why:"Shows how far the border-search exception reaches for vehicles.",
    source:"United States v. Flores-Montano, 541 U.S. 149 (2004)", verified:"https://www.law.cornell.edu/supremecourt/text/541/149" },
  { id:"cl-montoya", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"United States v. Montoya de Hernandez", cite:"473 U.S. 531", year:1985,
    back:"Detaining a traveler at the border beyond a routine search is justified when officers reasonably suspect she is smuggling contraband in her alimentary canal.",
    rule:"Non-routine border detention or search = reasonable suspicion.",
    field:"Routine border search: no suspicion. Prolonged or intrusive: articulate reasonable suspicion.",
    why:"Source of the routine vs. non-routine border-search line.",
    source:"United States v. Montoya de Hernandez, 473 U.S. 531 (1985)", verified:"https://www.law.cornell.edu/supremecourt/text/473/531" },
  { id:"cl-ramsey", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"United States v. Ramsey", cite:"431 U.S. 606", year:1977,
    back:"Customs may open incoming international mail at the border without a warrant or probable cause. Border searches are reasonable simply because they happen at the border. Reading correspondence still requires a warrant under the regulations.",
    rule:"Border searches are reasonable in themselves, including searches of international mail.",
    field:"The border-search exception applies to items crossing as well as people.",
    why:"A leading statement that border searches are reasonable in themselves.",
    source:"United States v. Ramsey, 431 U.S. 606 (1977)", verified:"https://law.cornell.edu/supremecourt/text/431/606" },
  { id:"cl-alisigwe", type:"flip", cat:"Border & Checkpoints", binding:"2d Cir.",
    front:"United States v. Alisigwe", cite:"No. 24-960 (2d Cir. Sept. 17, 2026)", year:2026,
    back:"Manual searches of a traveler's cell phone at the border (scrolling through and photographing what's on it) may be done without a warrant and without any suspicion. The court left open whether a forensic search requires reasonable suspicion.",
    rule:"In the 2d Circuit, a manual phone search at the border is routine. Forensic extraction is undecided.",
    field:"Binding in Vermont. For a forensic search, have reasonable suspicion articulated; the question is still open here.",
    why:"Current binding law in Vermont on border device searches.",
    flag:"Decided Sept. 2026. Watch for rehearing en banc or Supreme Court review.",
    source:"United States v. Alisigwe, No. 24-960 (2d Cir. Sept. 17, 2026)", verified:"https://law.justia.com/cases/federal/appellate-courts/ca2/24-960/24-960-2026-09-17.html" },
  { id:"cl-cotterman", type:"flip", cat:"Border & Checkpoints", binding:"persuasive (9th Cir.)",
    front:"United States v. Cotterman", cite:"709 F.3d 952 (9th Cir. 2013) (en banc)", year:2013,
    back:"A forensic examination of a laptop seized at the border required reasonable suspicion because of how comprehensive and intrusive it is. Reasonable suspicion existed on those facts.",
    rule:"Ninth Circuit: forensic device search at the border = reasonable suspicion.",
    field:"Not binding in Vermont. It shows how other circuits treat forensic searches, which the 2d Circuit hasn't decided.",
    why:"The most-cited case on the forensic-search question the 2d Circuit left open.",
    source:"United States v. Cotterman, 709 F.3d 952 (9th Cir. 2013) (en banc)", verified:"https://en.wikipedia.org/wiki/United_States_v._Cotterman" },
  { id:"cl-irving", type:"flip", cat:"Border & Checkpoints", binding:"2d Cir.",
    front:"United States v. Irving", cite:"452 F.3d 110 (2d Cir. 2006)", year:2006,
    back:"Routine border searches of belongings need no suspicion. More invasive non-routine searches need reasonable suspicion, which can rest on unusual conduct, incriminating finds in a routine search, records showing propensity, or a suspicious itinerary.",
    rule:"2d Cir.: routine border search = none; non-routine = reasonable suspicion.",
    field:"Lists the reasonable-suspicion factors this circuit accepts at the border.",
    why:"The 2d Circuit's routine / non-routine framework.",
    source:"United States v. Irving, 452 F.3d 110 (2d Cir. 2006)", verified:"https://law.resource.org/pub/us/case/reporter/F3/452/452.F3d.110.04-0971-.html" },
  { id:"cl-tabbaa", type:"flip", cat:"Border & Checkpoints", binding:"2d Cir.",
    front:"Tabbaa v. Chertoff", cite:"509 F.3d 89 (2d Cir. 2007)", year:2007,
    back:"Detaining U.S. citizens returning from Canada for several hours of questioning, pat-down, fingerprinting and photographing, without individualized suspicion, was a routine border search the Fourth Amendment permits.",
    rule:"2d Cir.: multi-hour questioning, fingerprinting and photographing at entry can still be routine.",
    field:"Shows how broadly the 2d Circuit reads 'routine' for travelers entering from Canada.",
    why:"A northern-border application of the routine-search doctrine.",
    source:"Tabbaa v. Chertoff, 509 F.3d 89 (2d Cir. 2007)", verified:"https://pnj.prisonlegalnews.org/news/2007/oct/1/tabbaa-v-chertoff-no-06-0119-cv-2nd-cir-509-f3d-89-november-26-2007-judge-chester-j-straub-1/" },
  { id:"cl-singh", type:"flip", cat:"Border & Checkpoints", binding:"2d Cir.",
    front:"United States v. Singh", cite:"415 F.3d 288 (2d Cir. 2005)", year:2005,
    back:"A Border Patrol roving stop near the Canadian border was supported by reasonable suspicion under Brignoni-Ponce. The aliens found in the vehicle were admissible and the § 1324 transporting conviction was affirmed.",
    rule:"2d Cir. applies Brignoni-Ponce and Cortez to northern-border roving stops.",
    field:"Brignoni-Ponce is the standard on the northern border as well as the southern.",
    why:"Binding 2d Circuit application of the roving-patrol standard.",
    source:"United States v. Singh, 415 F.3d 288 (2d Cir. 2005)", verified:"https://case-law.vlex.com/vid/u-s-v-singh-894865920" },
  { id:"cl-compton", type:"flip", cat:"Border & Checkpoints", binding:"2d Cir.",
    front:"United States v. Compton", cite:"830 F.3d 55 (2d Cir. 2016)", year:2016,
    back:"Agents had reasonable suspicion for a Terry stop of a driver who appeared to avoid an immigration checkpoint near the Canadian border, and did not unreasonably extend the stop.",
    rule:"2d Cir.: apparent checkpoint avoidance is a relevant reasonable-suspicion factor.",
    field:"Document exactly what the avoidance looked like: abrupt slowing, turning off before the checkpoint, timing.",
    why:"Binding authority that checkpoint avoidance counts.",
    source:"United States v. Compton, 830 F.3d 55 (2d Cir. 2016)", verified:"https://case-law.vlex.com/vid/830-f-3d-55-683725773" },
  { id:"cl-lopez-mendoza", type:"flip", cat:"Border & Checkpoints", binding:"SCOTUS",
    front:"INS v. Lopez-Mendoza", cite:"468 U.S. 1032", year:1984,
    back:"The exclusionary rule does not generally apply in civil deportation proceedings, and a person's identity is not suppressible as the fruit of an unlawful arrest.",
    rule:"Civil removal case: evidence generally isn't suppressed for a Fourth Amendment violation. Criminal case: it can be.",
    field:"A bad stop can still lose a § 1325/1326/1324 prosecution. Lopez-Mendoza doesn't save a criminal case.",
    why:"Explains why the same stop can play out differently in immigration court and federal court.",
    source:"INS v. Lopez-Mendoza, 468 U.S. 1032 (1984)", verified:"https://www.law.cornell.edu/wex/i.n.s._v._lopez-mendoza" },

  // ---------------- Vehicles & Searches ----------------
  { id:"cl-carroll", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Carroll v. United States", cite:"267 U.S. 132", year:1925,
    back:"Officers may search a vehicle without a warrant when they have probable cause to believe it contains contraband, because a vehicle can be quickly moved.",
    rule:"Automobile exception: probable cause, no warrant needed.",
    field:"Probable cause for the vehicle (not reasonable suspicion) is what lets you search it without a warrant.",
    why:"Origin of the automobile exception (a Prohibition-era liquor-smuggling case).",
    source:"Carroll v. United States, 267 U.S. 132 (1925)", verified:"https://www.pastpaperhero.com/resources/carroll-v-united-states-267-us-132-1925" },
  { id:"cl-whren", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Whren v. United States", cite:"517 U.S. 806", year:1996,
    back:"A traffic stop supported by probable cause of a traffic violation is reasonable regardless of the officer's subjective motive.",
    rule:"Objective probable cause of a violation = valid stop. A pretextual motive doesn't matter under the Fourth Amendment.",
    field:"If you rely on a traffic violation, it must actually have happened. Document it.",
    why:"Allows pretext stops when an objective violation exists.",
    source:"Whren v. United States, 517 U.S. 806 (1996)", verified:"https://law.justia.com/cases/federal/us/517/806/" },
  { id:"cl-rodriguez", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Rodriguez v. United States", cite:"575 U.S. 348", year:2015,
    back:"Without reasonable suspicion, officers may not extend a completed traffic stop to conduct a dog sniff. Authority for the stop ends when its mission is, or reasonably should be, finished.",
    rule:"The stop lasts only as long as its mission. Extending it needs its own reasonable suspicion.",
    field:"Develop reasonable suspicion before the original tasks are done, or let them go.",
    why:"Every extra minute of a stop needs a reason.",
    source:"Rodriguez v. United States, 575 U.S. 348 (2015)", verified:"https://law.justia.com/cases/federal/us/575/13-9972/" },
  { id:"cl-riley", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Riley v. California", cite:"573 U.S. 373", year:2014,
    back:"Police generally may not search the digital contents of a cell phone seized during an arrest without a warrant. Exigent circumstances, such as an imminent remote wipe, can still apply.",
    rule:"Phone seized at arrest: get a warrant before searching its contents.",
    field:"Inland arrest: secure the phone and get a warrant. Border searches are governed by Alisigwe in the 2d Cir.",
    why:"Separates arrest phone searches from border phone searches.",
    source:"Riley v. California, 573 U.S. 373 (2014)", verified:"https://www.pastpaperhero.com/resources/riley-v-california-573-us-373-2014" },
  { id:"cl-mimms", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Pennsylvania v. Mimms", cite:"434 U.S. 106", year:1977,
    back:"An officer may, as a matter of course, order the driver of a lawfully stopped car to get out.",
    rule:"Lawful stop = you may order the driver out. No further justification needed.",
    field:"Exit orders are an officer-safety tool on any lawful stop.",
    why:"Gives you control of the driver's position.",
    source:"Pennsylvania v. Mimms, 434 U.S. 106 (1977)", verified:"https://en.wikipedia.org/wiki/Maryland_v._Wilson" },
  { id:"cl-wilson", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Maryland v. Wilson", cite:"519 U.S. 408", year:1997,
    back:"The Mimms rule extends to passengers: an officer may order passengers out of a lawfully stopped car.",
    rule:"Lawful stop = you may order passengers out too.",
    field:"Control everyone in the vehicle, not only the driver.",
    why:"Extends exit orders to passengers.",
    source:"Maryland v. Wilson, 519 U.S. 408 (1997)", verified:"https://law.justia.com/cases/federal/us/519/408/" },
  { id:"cl-brendlin", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Brendlin v. California", cite:"551 U.S. 249", year:2007,
    back:"In a traffic stop, a passenger is seized just as the driver is, and may challenge the stop's legality.",
    rule:"Passengers are seized. A bad stop taints evidence against them too.",
    field:"The basis for the stop protects (or sinks) the case against every occupant.",
    why:"Passengers have standing to challenge the stop.",
    source:"Brendlin v. California, 551 U.S. 249 (2007)", verified:"https://case-law.vlex.com/vid/551-u-s-249-605969122" },
  { id:"cl-johnson", type:"flip", cat:"Vehicles & Searches", binding:"SCOTUS",
    front:"Arizona v. Johnson", cite:"555 U.S. 323", year:2009,
    back:"During a lawful traffic stop, an officer may frisk a passenger if the officer reasonably suspects the passenger is armed and dangerous, even without suspecting the passenger of a crime.",
    rule:"Frisk passenger = reasonable suspicion of armed and dangerous.",
    field:"The lawful stop supplies the detention. You still need the armed-and-dangerous articulation.",
    why:"Applies Terry frisks to passengers.",
    source:"Arizona v. Johnson, 555 U.S. 323 (2009)", verified:"https://supreme.justia.com/cases/federal/us/555/323" },

  // ---------------- Statements ----------------
  { id:"cl-miranda", type:"flip", cat:"Statements", binding:"SCOTUS",
    front:"Miranda v. Arizona", cite:"384 U.S. 436", year:1966,
    back:"Statements from custodial interrogation are inadmissible unless the suspect was warned of the right to silence, that statements can be used in court, the right to an attorney, and appointed counsel if indigent, and then waived those rights knowingly, voluntarily and intelligently.",
    rule:"Custody + interrogation = warnings and a valid waiver before questioning.",
    field:"Once a subject is in custody, warn before asking about the crime.",
    why:"Protects the admissibility of your best evidence.",
    source:"Miranda v. Arizona, 384 U.S. 436 (1966)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-384/pdf/USREPORTS-384-436.pdf" },

  // ---------------- Force ----------------
  { id:"cl-graham", type:"flip", cat:"Force", binding:"SCOTUS",
    front:"Graham v. Connor", cite:"490 U.S. 386", year:1989,
    back:"Excessive-force claims arising from an arrest, stop or other seizure are judged by objective reasonableness: from the view of a reasonable officer on the scene, not with 20/20 hindsight, allowing for split-second decisions. Factors include the severity of the crime, whether the suspect is an immediate threat, and whether the suspect is actively resisting or trying to flee.",
    rule:"Objective reasonableness, judged by a reasonable officer on the scene. Intent is irrelevant.",
    field:"Write the facts as you perceived them at the time, covering each Graham factor.",
    why:"The constitutional test for every use of force.",
    source:"Graham v. Connor, 490 U.S. 386 (1989)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-490/pdf/USREPORTS-490-386.pdf" },
  { id:"cl-garner", type:"flip", cat:"Force", binding:"SCOTUS",
    front:"Tennessee v. Garner", cite:"471 U.S. 1", year:1985,
    back:"Deadly force to prevent a suspect's escape is a Fourth Amendment seizure and is allowed only if the officer has probable cause to believe the suspect poses a significant threat of death or serious physical injury to the officer or others.",
    rule:"Fleeing alone never justifies deadly force. A significant threat of death or serious injury must exist.",
    field:"An unarmed subject running away is not a deadly-force situation.",
    why:"Ended the common-law 'fleeing felon' rule.",
    source:"Tennessee v. Garner, 471 U.S. 1 (1985)", verified:"https://law.justia.com/cases/federal/us/471/1/" },
  { id:"cl-scott", type:"flip", cat:"Force", binding:"SCOTUS",
    front:"Scott v. Harris", cite:"550 U.S. 372", year:2007,
    back:"An officer's attempt to end a dangerous high-speed chase by ramming the fleeing car was reasonable, because the driver's reckless flight posed a substantial and immediate risk of serious injury to others. The Court weighed the number of lives at risk and the relative culpability of the parties.",
    rule:"Force to end a chase is weighed against the danger the fleeing driver creates to the public.",
    field:"Document the danger the flight created: speeds, traffic, near-misses.",
    why:"The leading vehicle-pursuit force case.",
    source:"Scott v. Harris, 550 U.S. 372 (2007)", verified:"https://law.justia.com/cases/federal/us/550/372/" },
  { id:"cl-barnes", type:"flip", cat:"Force", binding:"SCOTUS",
    front:"Barnes v. Felix", cite:"605 U.S. 73", year:2025,
    back:"Courts must judge excessive force by the totality of the circumstances. They may not look only at the 'moment of the threat' and ignore what led up to it.",
    rule:"Events before the moment force is used are part of the reasonableness analysis.",
    field:"Your actions before the critical moment (positioning, tactics) will be weighed.",
    why:"Rejected the narrow test the 2d Circuit had used. The whole encounter now counts in Vermont.",
    flag:"Changes prior 2d Cir. law, which used the narrower 'moment of threat' approach.",
    source:"Barnes v. Felix, 605 U.S. 73 (2025)", verified:"https://en.wikipedia.org/wiki/Barnes_v._Felix" },

  // ---------------- Liability ----------------
  { id:"cl-hernandez-mesa", type:"flip", cat:"Liability", binding:"SCOTUS",
    front:"Hernandez v. Mesa", cite:"589 U.S. 93", year:2020,
    back:"No Bivens damages action is available for a cross-border shooting by a Border Patrol agent standing in the U.S., because the claim implicates foreign relations and national security.",
    rule:"Courts won't extend Bivens into new contexts like cross-border shootings.",
    field:"Personal damages suits against agents under Bivens are now very limited.",
    why:"Defines federal agents' personal civil exposure.",
    source:"Hernandez v. Mesa, 589 U.S. 93 (2020)", verified:"https://www.supremecourt.gov/opinions/19pdf/17-1678_m6io.pdf" },
  { id:"cl-egbert", type:"flip", cat:"Liability", binding:"SCOTUS",
    front:"Egbert v. Boule", cite:"596 U.S. 482", year:2022,
    back:"Bivens does not extend to a Fourth Amendment excessive-force claim against a Border Patrol agent, or to a First Amendment retaliation claim. Courts won't create damages remedies in new contexts touching national security or where an alternative remedial structure exists.",
    rule:"No Bivens claim for excessive force by a BP agent, even inside the U.S.",
    field:"The facts arose on the northern border, at a property next to the Canadian line.",
    why:"The leading case on agents' personal damages liability.",
    source:"Egbert v. Boule, 596 U.S. 482 (2022)", verified:"https://law.justia.com/cases/federal/us/596/21-147/" },

  // ---------------- Which Case Governs? ----------------
  { id:"cl-sc-roving", type:"scenario", cat:"Which Case Governs?",
    setup:"On roving patrol well inland, you see a vehicle you want to stop. Your only observation so far is the occupants' apparent ethnicity.",
    q:"Which case controls, and can you stop it?",
    choices:["Brignoni-Ponce: no, ethnicity alone isn't reasonable suspicion","Martinez-Fuerte: yes, no suspicion needed","Whren: yes, motive doesn't matter","Flores-Montano: yes, border search"],
    answer:0, explain:"Roving stops need specific articulable facts. Apparent ancestry can be one factor, never the only one.",
    source:"United States v. Brignoni-Ponce, 422 U.S. 873 (1975)", verified:"https://en.wikipedia.org/wiki/United_States_v._Brignoni-Ponce" },
  { id:"cl-sc-checkpoint-search", type:"scenario", cat:"Which Case Governs?",
    setup:"At an interior immigration checkpoint you've referred a car to secondary. The driver's answers are fine. You want to look in the trunk; the driver says no.",
    q:"What do you need to search the trunk?",
    choices:["Nothing: checkpoints are suspicionless (Martinez-Fuerte)","Probable cause or consent (Ortiz)","Reasonable suspicion (Brignoni-Ponce)","A warrant in every case (Riley)"],
    answer:1, explain:"Checkpoint stops and questioning are suspicionless, but searching the vehicle at an interior checkpoint needs consent or probable cause.",
    source:"United States v. Ortiz, 422 U.S. 891 (1975)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-422/pdf/USREPORTS-422-891.pdf" },
  { id:"cl-sc-factors", type:"scenario", cat:"Which Case Governs?",
    setup:"Defense counsel argues each of your six stop factors has an innocent explanation, so each should get zero weight.",
    q:"Which case answers that argument?",
    choices:["Terry v. Ohio","United States v. Arvizu","Tennessee v. Garner","Riley v. California"],
    answer:1, explain:"Arvizu rejects 'divide-and-conquer'. Factors are weighed together under the totality of the circumstances.",
    source:"United States v. Arvizu, 534 U.S. 266 (2002)", verified:"https://www.law.cornell.edu/supct/html/00-1519.ZS.html" },
  { id:"cl-sc-dog", type:"scenario", cat:"Which Case Governs?",
    setup:"Traffic stop. Citation written and documents returned. Nothing else suggests a crime, but you want to hold the car ten minutes for a K-9.",
    q:"Can you?",
    choices:["Yes: Whren allows any pretext","Yes: a dog sniff isn't a search","No: Rodriguez. The mission is over, and extending it needs reasonable suspicion","No: Riley requires a warrant"],
    answer:2, explain:"Authority ends when the stop's tasks are or should be done. A sniff isn't part of the traffic mission.",
    source:"Rodriguez v. United States, 575 U.S. 348 (2015)", verified:"https://law.justia.com/cases/federal/us/575/13-9972/" },
  { id:"cl-sc-phone-border", type:"scenario", cat:"Which Case Governs?",
    setup:"A traveler entering from Canada is in secondary. You want to scroll through the traveler's unlocked phone. No specific suspicion yet.",
    q:"In Vermont today, what governs?",
    choices:["Riley: warrant required","Cotterman: reasonable suspicion required","Alisigwe (2d Cir.): manual border search needs no suspicion","Terry: reasonable suspicion of armed and dangerous"],
    answer:2, explain:"Alisigwe is binding in the 2d Circuit for manual searches. Cotterman (9th Cir.) is only persuasive here, and the forensic-search question is still open.",
    source:"United States v. Alisigwe, No. 24-960 (2d Cir. Sept. 17, 2026)", verified:"https://law.justia.com/cases/federal/appellate-courts/ca2/24-960/24-960-2026-09-17.html" },
  { id:"cl-sc-phone-arrest", type:"scenario", cat:"Which Case Governs?",
    setup:"You arrest a driver inland for § 1324 transporting. The driver's phone is on the seat.",
    q:"Can you go through the phone's contents now?",
    choices:["Yes: search incident to arrest","Yes: Alisigwe","No: Riley. Secure it and get a warrant, absent an exigency","Yes: automobile exception (Carroll)"],
    answer:2, explain:"Away from the border, Riley controls. Seize and secure the phone and get a warrant unless there's a real exigency.",
    source:"Riley v. California, 573 U.S. 373 (2014)", verified:"https://www.pastpaperhero.com/resources/riley-v-california-573-us-373-2014" },
  { id:"cl-sc-flee", type:"scenario", cat:"Which Case Governs?",
    setup:"A subject you believe entered illegally runs from you into the woods. You see no weapon and nothing indicates a threat to anyone.",
    q:"Is deadly force authorized to stop the escape?",
    choices:["Yes: a felony is being committed","No: Garner. Flight alone isn't a significant threat of death or serious injury","Yes: Scott v. Harris","Yes, if the subject ignores commands"],
    answer:1, explain:"Deadly force requires probable cause of a significant threat of death or serious physical injury. Escape alone is never enough.",
    source:"Tennessee v. Garner, 471 U.S. 1 (1985)", verified:"https://law.justia.com/cases/federal/us/471/1/" },
  { id:"cl-sc-avoid", type:"scenario", cat:"Which Case Governs?",
    setup:"A vehicle crests a hill, sees the checkpoint ahead, brakes hard and pulls into a roadside lot short of it.",
    q:"Which binding case says that conduct counts toward reasonable suspicion?",
    choices:["United States v. Compton (2d Cir.)","Illinois v. Wardlow","Kansas v. Glover","INS v. Delgado"],
    answer:0, explain:"Compton (2d Cir. 2016) treats apparent checkpoint avoidance as a relevant factor. Wardlow is about foot flight, not checkpoints.",
    source:"United States v. Compton, 830 F.3d 55 (2d Cir. 2016)", verified:"https://case-law.vlex.com/vid/830-f-3d-55-683725773" },
  { id:"cl-sc-plate", type:"scenario", cat:"Which Case Governs?",
    setup:"A records check shows the registered owner of a pickup has a revoked license. You can't see the driver clearly.",
    q:"Can you stop the truck?",
    choices:["No: you need to see the driver first","Yes: Kansas v. Glover","Only with probable cause","Only at a checkpoint"],
    answer:1, explain:"Absent information that someone else is driving, it's reasonable to infer the owner is driving.",
    source:"Kansas v. Glover, 589 U.S. ___, 140 S. Ct. 1183 (2020)", verified:"https://www.supremecourt.gov/opinions/19pdf/589us2r21_a7bf.pdf" },
  { id:"cl-sc-passenger", type:"scenario", cat:"Which Case Governs?",
    setup:"On a lawful stop, a rear passenger keeps reaching under a jacket and won't show his hands. You have no reason to think the passenger committed a crime.",
    q:"Can you order the passenger out and frisk him?",
    choices:["No: passengers aren't seized","Yes: Maryland v. Wilson (exit) + Arizona v. Johnson (frisk on armed-and-dangerous suspicion)","Only with probable cause","Only with consent"],
    answer:1, explain:"Exit orders to passengers are automatic on a lawful stop. The frisk needs reasonable suspicion the passenger is armed and dangerous.",
    source:"Arizona v. Johnson, 555 U.S. 323 (2009)", verified:"https://supreme.justia.com/cases/federal/us/555/323" },
  { id:"cl-sc-pretext", type:"scenario", cat:"Which Case Governs?",
    setup:"You suspect smuggling but don't yet have reasonable suspicion. The car then rolls through a stop sign.",
    q:"Can you stop it for the stop sign?",
    choices:["Yes: Whren. Objective probable cause of a violation makes the stop valid","No: your real motive is immigration","Only if you tell the driver your real reason","No: Brignoni-Ponce"],
    answer:0, explain:"Subjective motive is irrelevant under the Fourth Amendment if the traffic violation is real. Rodriguez still limits how long you can hold the car.",
    source:"Whren v. United States, 517 U.S. 806 (1996)", verified:"https://law.justia.com/cases/federal/us/517/806/" },
  { id:"cl-sc-bus", type:"scenario", cat:"Which Case Governs?",
    setup:"On a transportation check you board a bus and ask passengers where they're headed and about their status. You don't block the aisle or hold anyone's documents.",
    q:"Is each passenger seized?",
    choices:["Yes: confined space","No: Drayton/Bostick. A reasonable person would feel free to decline","Yes, unless you advise them they can refuse","Only foreign nationals are seized"],
    answer:1, explain:"No advisement of the right to refuse is required. The test is whether a reasonable person would feel free to decline.",
    source:"United States v. Drayton, 536 U.S. 194 (2002)", verified:"https://www.law.cornell.edu/supremecourt/text/536/194" },
  { id:"cl-mc-binding", type:"mc", cat:"Which Case Governs?",
    q:"Which of these is NOT binding on a federal court in Vermont?",
    choices:["United States v. Alisigwe","United States v. Cotterman","Tabbaa v. Chertoff","United States v. Brignoni-Ponce"],
    answer:1, explain:"Cotterman is a 9th Circuit case: persuasive only. Vermont is in the 2d Circuit.",
    source:"28 U.S.C. § 41 (2d Cir. = Connecticut, New York, Vermont); United States v. Cotterman, 709 F.3d 952 (9th Cir. 2013)", verified:"https://www.law.cornell.edu/uscode/text/28/41" },
  { id:"cl-mc-removal", type:"mc", cat:"Which Case Governs?",
    q:"A stop is later found unlawful. In which proceeding is suppression most likely to matter?",
    choices:["Civil removal hearing","Federal criminal prosecution under § 1326","Neither","Both equally"],
    answer:1, explain:"Lopez-Mendoza: the exclusionary rule generally doesn't apply in civil deportation proceedings. It does apply in criminal cases.",
    source:"INS v. Lopez-Mendoza, 468 U.S. 1032 (1984)", verified:"https://www.law.cornell.edu/wex/i.n.s._v._lopez-mendoza" },
  ],
};
