// FIELD PROBLEMS — chained scenarios across decks. Not a card deck: problems don't enter Shuffle All.
// Step = { ref:"card-id" }        reuse a deck card; graded into its SRS normally
//      | { type:"mc"|"scenario"|"order", deck, feeds:[card ids], ... }   inline; a miss demotes every fed card
// Inline steps add no new facts: each restates what the cards it feeds already teach (and inherits their source).
// OPSEC: generic settings only. No places, routes, landmarks, sensors or local procedure.
export default [
// ---------------------------------------------------------------- 1
{ id:"fp-roving-dusk", title:"Roving Stop at Dusk",
  situation:"Late afternoon on a rural two-lane road a few miles from the line. An overloaded sedan with rear windows covered passes you, slows sharply, and the driver avoids eye contact.",
  steps:[
  { narrative:"You want to stop it. A trainee riding with you says the passengers 'look foreign'.",
    type:"scenario", deck:"caselaw", feeds:["cl-brignoni","cl-sc-roving"],
    setup:"Your factors: riding heavy, covered windows, abrupt slowing, avoiding eye contact, a road used to bypass the port. The trainee adds the occupants' appearance.",
    q:"What is the legal basis for the stop, and how should appearance figure?",
    choices:["Reasonable suspicion from the articulable factors; appearance alone can never carry it","No basis needed within 100 air miles","Probable cause is required for any roving stop","Appearance is enough near the border"],
    answer:0, explain:"Brignoni-Ponce: specific articulable facts amounting to reasonable suspicion. Apparent ancestry can be one factor, never the whole basis." },
  { narrative:"Defense will later argue each factor has an innocent explanation.", ref:"cl-sc-factors" },
  { narrative:"The driver rolls down the window and answers only in Spanish.",
    type:"mc", deck:"spanish", feeds:["es-p20"],
    q:"Ask the driver's country of citizenship.",
    choices:["¿De qué país es usted ciudadano?","¿Dónde vive usted?","¿Adónde va?","¿Cómo se llama usted?"],
    answer:0, explain:"Citizenship uses ser: « ¿De qué país es usted ciudadano? ». Where someone lives or is going isn't citizenship." },
  { narrative:"You ask when they crossed. The driver says « Hace dos días. »",
    type:"mc", deck:"spanish", feeds:["es-p104","es-p41"],
    q:"What did the driver tell you?",
    choices:["Two days ago","In two days","For two days","Two times"],
    answer:0, explain:"Hace + time = ago. « Hace dos días » = two days ago." },
  { narrative:"A rear passenger keeps reaching under a jacket and won't show his hands.", ref:"cl-sc-passenger" },
  { narrative:"Four occupants admit entering illegally. The driver says he was 'just giving rides'.", ref:"st-sc-driver" },
  { narrative:"Dispatch reads back the plate and you lose the last half in static.", ref:"rd-sc-sayagain" },
  ]},

// ---------------------------------------------------------------- 2
{ id:"fp-snow-sign", title:"Sign in Fresh Snow",
  situation:"Early morning after overnight snow. You cut fresh foot sign of a small group heading away from the line into hardwoods. Your GPS battery is failing in the cold.",
  steps:[
  { narrative:"The sign runs along a stream for most of a kilometer before turning uphill.", ref:"ln-sc-handrail" },
  { narrative:"A road crosses about 300 m past where you expect to catch them.", ref:"ln-sc-catching" },
  { narrative:"You plot the direction of travel on your map as a grid azimuth and need to follow it by compass.", ref:"ln-conv-w" },
  { narrative:"Deep snow, uphill, light snowfall. You're keeping a pace count.", ref:"ln-pace-snow" },
  { narrative:"You close on the group. One runs, empty-handed, toward thicker cover.", ref:"uf-sc-runner" },
  { narrative:"The others stop. One is shivering, clothes soaked from a stream crossing, and speaks only French.",
    type:"mc", deck:"french", feeds:["fr-m-froid","fr-m-mouille"],
    q:"Which two questions fit what you're seeing?",
    choices:["« Avez-vous froid ? » and « Vos vêtements sont-ils mouillés ? »","« Où allez-vous ? » and « D'où venez-vous ? »","« Avez-vous des armes ? » and « Ne bougez pas. »","« Comment vous appelez-vous ? » and « Merci. »"],
    answer:0, explain:"Cold and wet clothing are the immediate hazards. Ask them first." },
  { narrative:"Dispatch: 'Hold the group there, transport en route.' You understand and will comply.", ref:"rd-sc-wilco" },
  ]},

// ---------------------------------------------------------------- 3
{ id:"fp-checkpoint", title:"Checkpoint Secondary",
  situation:"You're working an interior immigration checkpoint. A minivan is referred to secondary after the driver gives inconsistent answers about the trip.",
  steps:[
  { narrative:"Before the referral, a car crested the hill, braked hard and turned into a roadside lot short of the checkpoint.", ref:"cl-sc-avoid" },
  { narrative:"In secondary the driver declines a search of the cargo area.", ref:"cl-sc-checkpoint-search" },
  { narrative:"Documents check out, and you've finished every immigration and traffic task. A K-9 is 15 minutes out.", ref:"cl-sc-dog" },
  { narrative:"The front passenger's name returns a prior removal with no consent to reapply.", ref:"st-sc-found-in" },
  { narrative:"The passenger speaks only Spanish. You confirm birthplace.",
    type:"mc", deck:"spanish", feeds:["es-p22"],
    q:"Ask where they were born.",
    choices:["¿Dónde nació usted?","¿Dónde vive usted?","¿De dónde viene?","¿Adónde va?"],
    answer:0, explain:"Preterite of nacer: « ¿Dónde nació usted? ». « ¿De dónde viene? » only asks where they're coming from." },
  { narrative:"Records also show an aggravated-felony conviction before that removal.", ref:"st-1326b" },
  { narrative:"The passenger is now under arrest and you want to ask about the reentry.",
    type:"scenario", deck:"caselaw", feeds:["cl-miranda"],
    setup:"The passenger is handcuffed in your vehicle. You want to ask when and how they came back in.",
    q:"What has to happen first?",
    choices:["Miranda warnings and a knowing, voluntary waiver","Nothing; immigration questions are exempt","Only a supervisor's approval","A warrant"],
    answer:0, explain:"Custody plus interrogation: warn and get a valid waiver, or the statements can't be used at trial." },
  ]},

// ---------------------------------------------------------------- 4
{ id:"fp-farm-field", title:"Farm Field Follow-Up",
  situation:"A landowner reports people crossing a back field toward a barn. You follow tracks across private land a few miles from the boundary.",
  steps:[
  { narrative:"The tracks cross open fields past the farmhouse and toward the barn.", ref:"st-sc-land" },
  { narrative:"Two people step out from behind the barn. You identify yourself in Spanish and order them to stop.",
    type:"mc", deck:"spanish", feeds:["es-p1"],
    q:"Your command?",
    choices:["¡Alto! Patrulla Fronteriza.","¡Venga acá!","Buenos días.","¿Me entiende?"],
    answer:0, explain:"« ¡Alto! » is the universal halt command, and it identifies you in the same breath." },
  { narrative:"One keeps a hand in a pocket.",
    type:"mc", deck:"spanish", feeds:["es-p6","es-p73"],
    q:"Best next words?",
    choices:["Muéstreme las manos.","Siéntese.","Firme aquí, por favor.","Gracias."],
    answer:0, explain:"Hands first. Then « ¿Tiene algo en los bolsillos que me pueda lastimar? » before the pat-down." },
  { narrative:"The second subject twists away as you reach for an arm. Nothing suggests a weapon.", ref:"uf-287-nondeadly" },
  { narrative:"Both admit being unlawfully present. One has a bus ticket out of state for tonight. No warrant exists.", ref:"st-sc-arrest-interior" },
  { narrative:"You make the arrest.", ref:"st-2878-c2iii" },
  { narrative:"Tell them in Spanish that they're detained.",
    type:"mc", deck:"spanish", feeds:["es-p80"],
    q:"Which is correct?",
    choices:["Usted está detenido.","Usted es detenido.","Usted hay detenido.","Usted tiene detenido."],
    answer:0, explain:"ESTAR + past participle for the resulting state. « Detenida » for a woman." },
  ]},

// ---------------------------------------------------------------- 5
{ id:"fp-port-phone", title:"Traveler's Phone",
  situation:"You're assisting at a port of entry. A traveler arriving from Canada is in secondary. Answers about the trip don't line up, and the traveler speaks Québécois French.",
  steps:[
  { narrative:"The traveler says « On s'est arrêtés pour dîner, puis on a traversé. »", ref:"fr-q-mc-diner" },
  { narrative:"The traveler keeps calling you « tu ».", ref:"fr-q-tu" },
  { narrative:"Before the phone, you want to search the traveler's bag for documents that would show inadmissibility.", ref:"st-1357-c" },
  { narrative:"You want to scroll through the unlocked phone. There's no specific suspicion yet.", ref:"cl-sc-phone-border" },
  { narrative:"A colleague suggests a full forensic extraction instead.",
    type:"scenario", deck:"caselaw", feeds:["cl-alisigwe","cl-cotterman"],
    setup:"Forensic extraction of the same phone, at the border, in the 2d Circuit.",
    q:"Where does the law stand?",
    choices:["Undecided in the 2d Circuit. The 9th Circuit (persuasive) requires reasonable suspicion, so have it articulated","Clearly allowed with no suspicion in the 2d Circuit","Always requires a warrant","Prohibited"],
    answer:0, explain:"Alisigwe decided manual searches only. Cotterman (9th Cir.) is persuasive, not binding here." },
  { narrative:"The traveler says « Je veux parler à un avocat. »", ref:"fr-h-mc" },
  { narrative:"Days later, a different subject is arrested inland and their phone is seized.", ref:"cl-sc-phone-arrest" },
  ]},

// ---------------------------------------------------------------- 6
{ id:"fp-night-pursuit", title:"Night Vehicle Flight",
  situation:"After dark, a vehicle you've signaled to stop accelerates away on a winding rural road with oncoming traffic.",
  steps:[
  { narrative:"You call in the plate as you follow: K Z R.", ref:"rd-l-plate" },
  { narrative:"The driver passes on blind curves and forces an oncoming car onto the shoulder.", ref:"uf-scott" },
  { narrative:"The vehicle crashes into a ditch. The driver bails out and runs, unarmed as far as you can see.", ref:"uf-garner" },
  { narrative:"A passenger climbs out holding a knife. He's shouting in French.",
    type:"mc", deck:"french", feeds:["fr-c-arme"],
    q:"Your command?",
    choices:["« Lâchez l'arme ! »","« Calmez-vous. »","« Venez ici. »","« Bonsoir. »"],
    answer:0, explain:"« Lâchez l'arme ! » = Drop the weapon!" },
  { narrative:"He keeps advancing on your partner, ignoring commands.", ref:"uf-sc-knife" },
  { narrative:"Afterward, review will look at the whole encounter, including the chase.", ref:"uf-barnes" },
  { narrative:"The passenger is injured.", ref:"uf-dhs-aid" },
  { narrative:"Now you write it up.", ref:"uf-sc-report" },
  ]},
// ---------------------------------------------------------------- 7
{ id:"fp-open-field", title:"Open Field, Locked Gate",
  situation:"Before dawn you cut sign of two people crossing a posted, gated hayfield toward a farmstead. Snow on the ground, single digits.",
  steps:[
  { narrative:"The tracks go under a No Trespassing gate into the field, half a mile from the house.", ref:"cl-sc-open-field" },
  { narrative:"They lead to a barn about 60 yards from the house, outside its fence.", ref:"cl-sc-barn" },
  { narrative:"Your supervisor asks whether the farm rule in § 1357(e) applies out here.", ref:"st-1357-e" },
  { narrative:"You plot your GPS position on the paper map and it lands you in the farm pond.", ref:"ln-datum-sc" },
  { narrative:"Behind the barn you find one subject shaking, boots soaked. He speaks Spanish.",
    type:"mc", deck:"spanish", feeds:["es-w1","es-w4"],
    q:"Which two questions come first?",
    choices:["« ¿Siente los dedos de los pies? » and « ¿Se mojó? »","« ¿Adónde va? » and « ¿Cuánto pagó? »","« ¿Qué hora es? » and « ¿Cómo se llama? »","« Firme aquí » and « Gracias »"],
    answer:0, explain:"Feeling in the feet and whether he got wet go straight to cold exposure. Status questions can wait." },
  { narrative:"Getting him to the unit: offer warmth in his language.",
    type:"mc", deck:"spanish", feeds:["es-w5","es-w6"],
    q:"Which phrase?",
    choices:["Suba al vehículo; hay calefacción.","Espere aquí.","No se mueva.","Vacíe sus bolsillos."],
    answer:0, explain:"« Suba al vehículo; hay calefacción. » = Get in, the heat's on. Pair it with « Aquí tiene una manta. »" },
  { narrative:"The second subject is still out. A second unit wants your night compass preset for 135°.", ref:"ln-bezel-calc" },
  ]},

// ---------------------------------------------------------------- 8
{ id:"fp-papers", title:"Papers That Don't Add Up",
  situation:"A vehicle stop on a lawful basis. The front passenger hands over a permanent resident card. The driver answers your French questions about the trip.",
  steps:[
  { narrative:"The card's security features are wrong and records show no such card was issued.", ref:"st-sc-fake-card" },
  { narrative:"The passenger then gives a false name and claims U.S. citizenship. Prints show otherwise.", ref:"st-sc-false-name" },
  { narrative:"The driver gives a date of birth in French: « le cinq mars mille neuf cent quatre-vingt-dix ».",
    type:"mc", deck:"french", feeds:["fr-n12","fr-n6"],
    q:"What date was given?",
    choices:["March 5, 1990","May 3, 1990","March 5, 1980","March 15, 1970"],
    answer:0, explain:"Le cinq mars = 5 March. Quatre-vingt-dix = 90." },
  { narrative:"You ask the driver, 'Can I search the car for anyone hiding or any IDs?' — 'Sure.' There's a locked hard case in the trunk.", ref:"cl-sc-consent-scope" },
  { narrative:"The passenger is arrested and handcuffed in your unit.", ref:"cl-sc-gant" },
  { narrative:"Before transport, the passenger says they're afraid to go back to their country.", ref:"st-sc-fear" },
  ]},

// ---------------------------------------------------------------- 9
{ id:"fp-911", title:"The 911 Call",
  situation:"Dispatch relays a 911 call: a specific pickup just ran the caller off the road. Plate, color and direction given. You spot it minutes later.",
  steps:[
  { narrative:"The pickup is driving normally when you find it.", ref:"cl-sc-911" },
  { narrative:"Dispatch reads the plate number back with « FIFE » in it.", ref:"rd-n-mc" },
  { narrative:"At the window the driver answers only in Spanish. You ask what time they left.",
    type:"mc", deck:"spanish", feeds:["es-n13","es-n14"],
    q:"The driver says « a las ocho de la noche ». When?",
    choices:["8 a.m.","8 p.m.","At night, 8 hours ago","Eight days ago"],
    answer:1, explain:"De la noche = in the evening or at night. 8 p.m." },
  { narrative:"A few roadside questions later, the driver is handcuffed and in your unit.", ref:"cl-sc-custody" },
  { narrative:"A passenger grabs a tire iron and swings it at you.", ref:"st-18-111-mc" },
  { narrative:"Your report on the force you used to stop the swing.", ref:"uf-graham-order" },
  ]},
];
