// USE OF FORCE — CBP Use of Force Policy (HB 4500-002A, Jan. 2021), DHS Policy Statement 044-05 Rev. 01
// (Feb. 2023), 8 C.F.R. 287.8(a), Graham v. Connor, Tennessee v. Garner, Scott v. Harris, Barnes v. Felix.
// Policy cards carry only provisions confirmed in public sources; status flags note what to confirm locally.
export default {
  meta: { id:"force", name:"Use of Force", short:"UOF", color:"#B07A9E", order:5, requireVerified:true,
    blurb:"Graham factors, Garner, the regulation, and published CBP/DHS policy.",
    subModes:["browse"] },
  categories: {
    "Constitutional Standard": { why:"Courts judge every use of force against this standard." },
    "Policy": { why:"Policy can be stricter than the Constitution, and you are held to both." },
    "Scenarios": { why:"Applying the standard under stress is the skill being tested." },
  },
  cards: [
  // ---------------- Constitutional ----------------
  { id:"uf-graham-order", type:"order", cat:"Constitutional Standard", binding:"SCOTUS",
    q:"Graham v. Connor: put the three factors in the order the Court listed them.",
    steps:["Severity of the crime at issue","Whether the suspect poses an immediate threat to the safety of officers or others","Whether the suspect is actively resisting arrest or attempting to evade arrest by flight"],
    explain:"Severity → immediate threat → resisting or evading, judged from the view of a reasonable officer on the scene.",
    why:"Your report should address each factor.",
    source:"Graham v. Connor, 490 U.S. 386 (1989)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-490/pdf/USREPORTS-490-386.pdf" },
  { id:"uf-graham-perspective", type:"mc", cat:"Constitutional Standard", binding:"SCOTUS",
    q:"Under Graham, from whose perspective is the reasonableness of force judged?",
    choices:["The subject's","A reasonable officer on the scene, without 20/20 hindsight","The reviewing judge with all facts later learned","The officer's own good-faith intent"],
    answer:1, explain:"Objective test, at the moment, allowing for split-second decisions. The officer's intent, good or bad, is irrelevant.",
    why:"Write what you perceived at the time, not what you learned afterward.",
    source:"Graham v. Connor, 490 U.S. 386 (1989)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-490/pdf/USREPORTS-490-386.pdf" },
  { id:"uf-garner", type:"mc", cat:"Constitutional Standard", binding:"SCOTUS",
    q:"Tennessee v. Garner: deadly force to stop a fleeing suspect is allowed only when the officer has probable cause to believe the suspect…",
    choices:["committed any felony","poses a significant threat of death or serious physical injury to the officer or others","is likely to escape","refuses lawful commands"],
    answer:1, explain:"Flight alone, even from a felony, is not enough.",
    why:"The constitutional floor for deadly force on a fleeing subject.",
    source:"Tennessee v. Garner, 471 U.S. 1 (1985)", verified:"https://law.justia.com/cases/federal/us/471/1/" },
  { id:"uf-barnes", type:"mc", cat:"Constitutional Standard", binding:"SCOTUS",
    q:"After Barnes v. Felix (2025), a court reviewing a shooting may consider…",
    choices:["Only the final seconds before the shot","The totality of the circumstances, including events leading up to the threat","Only the officer's stated reasons","Only what the subject knew"],
    answer:1, explain:"The Court unanimously rejected the 'moment of the threat' test.",
    flag:"The 2d Circuit had used the narrower moment-of-threat approach. Barnes overrides it.",
    why:"Your tactics before the critical moment are part of the review.",
    source:"Barnes v. Felix, 605 U.S. 73 (2025)", verified:"https://en.wikipedia.org/wiki/Barnes_v._Felix" },
  { id:"uf-scott", type:"flip", cat:"Constitutional Standard", binding:"SCOTUS",
    front:"Ending a dangerous vehicle flight with force — the test", back:"Scott v. Harris: weigh the risk the force creates for the fleeing driver against the actual and imminent threat the driver's reckless flight poses to others, considering the number of lives at risk and the relative culpability of the parties.",
    why:"The framework for pursuits and vehicle interventions.",
    source:"Scott v. Harris, 550 U.S. 372 (2007)", verified:"https://law.justia.com/cases/federal/us/550/372/" },
  { id:"uf-287-nondeadly", type:"flip", cat:"Constitutional Standard", binding:"regulation",
    front:"8 C.F.R. 287.8(a): when may you move up to a higher level of non-deadly force?", back:"Only when warranted by the subject's actions, apparent intentions, and apparent capabilities. Always use the minimum non-deadly force necessary to accomplish the mission.",
    why:"The regulation adds a 'minimum necessary' rule on top of Graham.",
    source:"8 C.F.R. § 287.8(a)(1)", verified:"https://chanrobles.com/usa/uslaws/cfr/title08/8-1.0.1.2.57.0.1.8.php" },

  // ---------------- Policy ----------------
  { id:"uf-cbp-standard", type:"flip", cat:"Policy", binding:"policy",
    front:"CBP Use of Force Policy (2021): the general standard", back:"Officers and agents shall use only the force that is objectively reasonable to effectively bring an incident under control, while protecting the life of the officer/agent or others.",
    why:"CBP's own baseline, which tracks Graham.",
    flag:"Confirm against the current version issued to you. This is the publicly posted 2021 text.",
    source:"CBP Use of Force Policy, HB 4500-002A (Jan. 2021)", verified:"https://www.cbp.gov/sites/default/files/assets/documents/2021-Jul/cbp-use-of-force-policy_4500-002A.pdf" },
  { id:"uf-cbp-deadly", type:"flip", cat:"Policy", binding:"policy",
    front:"CBP policy: when is deadly force 'necessary'?", back:"When the officer/agent has a reasonable belief that the subject poses an imminent danger of death or serious bodily injury to the officer/agent or to another person.",
    why:"The policy deadly-force trigger.",
    flag:"Confirm against the current version issued to you.",
    source:"CBP Use of Force Policy, HB 4500-002A (Jan. 2021)", verified:"https://www.cbp.gov/sites/default/files/assets/documents/2021-Jul/cbp-use-of-force-policy_4500-002A.pdf" },
  { id:"uf-cbp-escape", type:"mc", cat:"Policy", binding:"policy",
    q:"CBP/DHS policy: may deadly force be used solely to prevent the escape of a fleeing subject?",
    choices:["Yes, if the subject is a felon","No","Yes, after a verbal warning","Only near the border"],
    answer:1, explain:"\"Deadly force shall not be used solely to prevent the escape of a fleeing subject.\" A fleeing subject who poses a significant threat of death or serious harm is a different analysis (Garner).",
    why:"Policy and Garner point the same way.",
    source:"CBP Use of Force Policy, HB 4500-002A (Jan. 2021); DHS Policy Statement 044-05", verified:"https://www.justsecurity.org/128498/dhs-doj-cbp-policy-force-vehicles/" },
  { id:"uf-cbp-deesc", type:"flip", cat:"Policy", binding:"policy",
    front:"CBP policy: de-escalation", back:"When it is feasible and safe to do so, use de-escalation tactics and techniques to minimize the likelihood of needing force, or to minimize the force used.",
    why:"Expected whenever time and distance allow, and reviewed afterward.",
    flag:"Confirm against the current version issued to you.",
    source:"CBP Use of Force Policy, HB 4500-002A (Jan. 2021)", verified:"https://www.cbp.gov/sites/default/files/assets/documents/2021-Jul/cbp-use-of-force-policy_4500-002A.pdf" },
  { id:"uf-cbp-intervene", type:"flip", cat:"Policy", binding:"policy",
    front:"CBP policy: another agent is using clearly improper force", back:"The 2021 policy contains a duty to intervene in, and report, improper use of force.",
    why:"Silence carries its own exposure.",
    flag:"Confirm the exact wording and reporting chain in your current policy.",
    source:"CBP Use of Force Policy, HB 4500-002A (Jan. 2021)", verified:"https://www.cbp.gov/sites/default/files/assets/documents/2021-Jul/cbp-use-of-force-policy_4500-002A.pdf" },
  { id:"uf-dhs-choke", type:"mc", cat:"Policy", binding:"policy",
    q:"DHS Policy 044-05 Rev. 01 (2023): chokeholds and carotid restraints are…",
    choices:["Allowed at any level of resistance","Prohibited unless deadly force is otherwise authorized","Allowed if the subject is resisting","Prohibited in all circumstances"],
    answer:1, explain:"Prohibited unless the legal standard for deadly force is met.",
    flag:"DHS 044-05 Rev. 01 (Feb. 2023) status after 2025 is unclear in public sources. Confirm the policy currently in force.",
    why:"A department-wide rule that sits on top of CBP policy.",
    source:"DHS Policy Statement 044-05 Rev. 01 (Feb. 6, 2023)", verified:"https://www.dhs.gov/news/2023/02/07/dhs-updates-department-wide-use-force-policy-advance-effective-accountable-law" },
  { id:"uf-dhs-aid", type:"flip", cat:"Policy", binding:"policy",
    front:"DHS 2023 policy: after you use force and someone is injured", back:"There is an affirmative duty to request and/or render medical aid.",
    flag:"Confirm the policy currently in force (see 044-05 status note).",
    why:"Aid after force is a policy duty, not a courtesy.",
    source:"DHS Policy Statement 044-05 Rev. 01 (Feb. 6, 2023)", verified:"https://www.dhs.gov/news/2023/02/07/dhs-updates-department-wide-use-force-policy-advance-effective-accountable-law" },
  { id:"uf-dhs-self", type:"mc", cat:"Policy", binding:"policy",
    q:"DHS 2023 policy: may deadly force be used against a person who is a threat only to themselves or to property?",
    choices:["Yes","No","Only with a supervisor's approval","Only if the property is a vehicle"],
    answer:1, explain:"The 2023 update bars deadly force against someone who is only a threat to themselves or property.",
    flag:"Confirm the policy currently in force (see 044-05 status note).",
    why:"A suicidal subject or property damage alone doesn't meet the deadly-force threshold.",
    source:"DHS Policy Statement 044-05 Rev. 01 (Feb. 6, 2023)", verified:"https://www.dhs.gov/news/2023/02/07/dhs-updates-department-wide-use-force-policy-advance-effective-accountable-law" },

  // ---------------- Scenarios ----------------
  { id:"uf-sc-runner", type:"scenario", cat:"Scenarios",
    setup:"A subject who just crossed runs from you across an open field. Hands visible and empty, no weapon seen, no threat made.",
    q:"What force options are consistent with Garner and policy?",
    choices:["Deadly force to stop the escape","Pursue and use the minimum non-deadly force necessary to apprehend","Deadly force after a second ignored command","None. Let the subject go."],
    answer:1, explain:"No significant threat means no deadly force. Non-deadly force is limited to what's necessary, scaled to actions, apparent intentions and apparent capabilities.",
    source:"Tennessee v. Garner, 471 U.S. 1 (1985); 8 C.F.R. § 287.8(a)", verified:"https://law.justia.com/cases/federal/us/471/1/" },
  { id:"uf-sc-knife", type:"scenario", cat:"Scenarios",
    setup:"At about 15 feet, a subject pulls a knife and advances on your partner, ignoring commands.",
    q:"Which standard decides whether deadly force is justified?",
    choices:["Whether the subject committed a felony","Reasonable belief of imminent danger of death or serious bodily injury to your partner","Whether the subject is fleeing","Whether a supervisor approves"],
    answer:1, explain:"The regulation, CBP policy and Graham's threat factor all turn on imminent danger of death or serious bodily injury, judged as a reasonable officer would see it then.",
    source:"8 C.F.R. § 287.8(a)(2); CBP Use of Force Policy (2021)", verified:"https://www.law.cornell.edu/cfr/text/8/287.8" },
  { id:"uf-sc-report", type:"scenario", cat:"Scenarios",
    setup:"You used a takedown on a resisting subject. Now you're writing the report.",
    q:"What should the narrative cover?",
    choices:["Only that force was 'necessary'","Each Graham factor as you perceived it at the time, the subject's actions, and the de-escalation tried","Your intent to be fair","What you later learned from records"],
    answer:1, explain:"Graham judges the facts as a reasonable officer perceived them then. Barnes adds that the lead-up counts too.",
    source:"Graham v. Connor, 490 U.S. 386 (1989); Barnes v. Felix, 605 U.S. 73 (2025)", verified:"https://www.govinfo.gov/content/pkg/USREPORTS-490/pdf/USREPORTS-490-386.pdf" },
  ],
};
