// FRENCH — field French for the Québec line. Formal "vous" throughout.
// Phrases are standard French written for this app (deck-level source). Every Québec-usage card
// carries its own source + `verified` URL; usage that couldn't be sourced is in UNVERIFIED.md, not here.
export default {
  meta: { id:"french", name:"French", short:"FR", color:"#5B8FC9", lang:"fr-CA", order:2,
    blurb:"Field French for the Québec line: commands, status questions, medical, and Québécois usage.",
    source:"Patrol Kit French deck: standard French field phrases written for this app",
    subModes:["browse"] },
  categories: {
    "Greetings & Courtesy":   { why:"A polite Bonjour sets the tone, and in Québec it's expected." },
    "Commands & Control":     { why:"Clear commands in the subject's language cut confusion and the need for force." },
    "Identity & Citizenship": { why:"Alienage and status questions are the legal core of the encounter." },
    "Travel & Crossing":      { why:"Pins down time, place and manner of entry, and who else is out there." },
    "Medical & Safety":       { why:"Catch injuries, cold exposure and weapons early." },
    "What You'll Hear":       { why:"Recognizing common answers matters as much as asking the question." },
    "Québec Usage":           { why:"Québécois words differ from textbook French. Knowing them keeps you from misreading an answer." },
  },
  cards: [
  // ---------- Greetings & Courtesy ----------
  { id:"fr-g-bonjour", type:"flip", cat:"Greetings & Courtesy", front:"Bonjour.", back:"Hello. / Good morning.", note:"Used through the day until evening." },
  { id:"fr-g-bonsoir", type:"flip", cat:"Greetings & Courtesy", front:"Bonsoir.", back:"Good evening." },
  { id:"fr-g-agent", type:"flip", cat:"Greetings & Courtesy", front:"Je suis agent de la Patrouille frontalière des États-Unis.", back:"I am a United States Border Patrol agent.", note:"A female agent says « agente »." },
  { id:"fr-g-anglais", type:"flip", cat:"Greetings & Courtesy", front:"Parlez-vous anglais ?", back:"Do you speak English?" },
  { id:"fr-g-unpeu", type:"flip", cat:"Greetings & Courtesy", front:"Je parle un peu français.", back:"I speak a little French." },
  { id:"fr-g-lentement", type:"flip", cat:"Greetings & Courtesy", front:"Parlez plus lentement, s'il vous plaît.", back:"Speak more slowly, please." },
  { id:"fr-g-repeter", type:"flip", cat:"Greetings & Courtesy", front:"Pouvez-vous répéter, s'il vous plaît ?", back:"Can you repeat that, please?" },
  { id:"fr-g-comprends", type:"flip", cat:"Greetings & Courtesy", front:"Je ne comprends pas.", back:"I don't understand." },
  { id:"fr-g-comprenez", type:"flip", cat:"Greetings & Courtesy", front:"Vous me comprenez ?", back:"Do you understand me?" },
  { id:"fr-g-merci", type:"flip", cat:"Greetings & Courtesy", front:"Merci. — Je vous en prie.", back:"Thank you. — You're welcome." },
  { id:"fr-g-excusez", type:"flip", cat:"Greetings & Courtesy", front:"Excusez-moi.", back:"Excuse me." },

  // ---------- Commands & Control ----------
  { id:"fr-c-arretez", type:"flip", cat:"Commands & Control", front:"Arrêtez ! Patrouille frontalière !", back:"Stop! Border Patrol!" },
  { id:"fr-c-bougez", type:"flip", cat:"Commands & Control", front:"Ne bougez pas.", back:"Don't move." },
  { id:"fr-c-courez", type:"flip", cat:"Commands & Control", front:"Ne courez pas.", back:"Don't run." },
  { id:"fr-c-mains", type:"flip", cat:"Commands & Control", front:"Montrez-moi vos mains.", back:"Show me your hands." },
  { id:"fr-c-levez", type:"flip", cat:"Commands & Control", front:"Levez les mains.", back:"Raise your hands." },
  { id:"fr-c-tete", type:"flip", cat:"Commands & Control", front:"Mettez les mains sur la tête.", back:"Put your hands on your head." },
  { id:"fr-c-arme", type:"flip", cat:"Commands & Control", front:"Lâchez l'arme !", back:"Drop the weapon!" },
  { id:"fr-c-genoux", type:"flip", cat:"Commands & Control", front:"Mettez-vous à genoux.", back:"Get on your knees." },
  { id:"fr-c-retournez", type:"flip", cat:"Commands & Control", front:"Retournez-vous.", back:"Turn around." },
  { id:"fr-c-attendez", type:"flip", cat:"Commands & Control", front:"Attendez ici.", back:"Wait here." },
  { id:"fr-c-venez", type:"flip", cat:"Commands & Control", front:"Venez ici.", back:"Come here." },
  { id:"fr-c-calmez", type:"flip", cat:"Commands & Control", front:"Calmez-vous.", back:"Calm down." },
  { id:"fr-c-moteur", type:"flip", cat:"Commands & Control", front:"Coupez le moteur.", back:"Turn off the engine." },
  { id:"fr-c-cles", type:"flip", cat:"Commands & Control", front:"Donnez-moi les clés.", back:"Give me the keys." },
  { id:"fr-c-restez", type:"flip", cat:"Commands & Control", front:"Restez dans le véhicule.", back:"Stay in the vehicle." },
  { id:"fr-c-sortez", type:"flip", cat:"Commands & Control", front:"Sortez du véhicule.", back:"Get out of the vehicle." },
  { id:"fr-c-mc", type:"mc", cat:"Commands & Control", q:"« Coupez le moteur » means…", choices:["Open the trunk","Turn off the engine","Get out of the car","Show me the registration"], answer:1, explain:"Couper = to cut / switch off. Le moteur = the engine." },

  // ---------- Identity & Citizenship ----------
  { id:"fr-i-citoyen", type:"flip", cat:"Identity & Citizenship", front:"De quel pays êtes-vous citoyen ?", back:"Of what country are you a citizen?", note:"To a woman: « citoyenne »." },
  { id:"fr-i-nationalite", type:"flip", cat:"Identity & Citizenship", front:"Quelle est votre nationalité ?", back:"What is your nationality?" },
  { id:"fr-i-ne", type:"flip", cat:"Identity & Citizenship", front:"Où êtes-vous né ?", back:"Where were you born?", note:"To a woman: « née » (same sound)." },
  { id:"fr-i-nom", type:"flip", cat:"Identity & Citizenship", front:"Comment vous appelez-vous ?", back:"What is your name?" },
  { id:"fr-i-nomfamille", type:"flip", cat:"Identity & Citizenship", front:"Quel est votre nom de famille ?", back:"What is your last name?" },
  { id:"fr-i-naissance", type:"flip", cat:"Identity & Citizenship", front:"Quelle est votre date de naissance ?", back:"What is your date of birth?" },
  { id:"fr-i-piece", type:"flip", cat:"Identity & Citizenship", front:"Avez-vous une pièce d'identité ?", back:"Do you have identification?" },
  { id:"fr-i-passeport", type:"flip", cat:"Identity & Citizenship", front:"Avez-vous votre passeport ?", back:"Do you have your passport?" },
  { id:"fr-i-permis", type:"flip", cat:"Identity & Citizenship", front:"Avez-vous un permis de conduire ?", back:"Do you have a driver's license?" },
  { id:"fr-i-documents", type:"flip", cat:"Identity & Citizenship", front:"Avez-vous des documents qui vous autorisent à être aux États-Unis ?", back:"Do you have documents that allow you to be in the United States?" },
  { id:"fr-i-habitez", type:"flip", cat:"Identity & Citizenship", front:"Où habitez-vous ?", back:"Where do you live?" },
  { id:"fr-i-mc", type:"mc", cat:"Identity & Citizenship", q:"Best way to ask someone's citizenship?", choices:["Où habitez-vous ?","De quel pays êtes-vous citoyen ?","Comment allez-vous ?","D'où venez-vous ?"], answer:1, explain:"Where someone lives or came from isn't their citizenship. Ask directly." },

  // ---------- Travel & Crossing ----------
  { id:"fr-t-allez", type:"flip", cat:"Travel & Crossing", front:"Où allez-vous ?", back:"Where are you going?" },
  { id:"fr-t-venez", type:"flip", cat:"Travel & Crossing", front:"D'où venez-vous ?", back:"Where are you coming from?" },
  { id:"fr-t-entre", type:"flip", cat:"Travel & Crossing", front:"Comment êtes-vous entré aux États-Unis ?", back:"How did you enter the United States?" },
  { id:"fr-t-quand", type:"flip", cat:"Travel & Crossing", front:"Quand avez-vous traversé la frontière ?", back:"When did you cross the border?" },
  { id:"fr-t-point", type:"flip", cat:"Travel & Crossing", front:"Êtes-vous passé par un point d'entrée officiel ?", back:"Did you go through an official port of entry?" },
  { id:"fr-t-autres", type:"flip", cat:"Travel & Crossing", front:"Y a-t-il d'autres personnes avec vous ?", back:"Are there other people with you?" },
  { id:"fr-t-combien", type:"flip", cat:"Travel & Crossing", front:"Combien de personnes ?", back:"How many people?" },
  { id:"fr-t-vehicule", type:"flip", cat:"Travel & Crossing", front:"À qui appartient ce véhicule ?", back:"Whose vehicle is this?" },
  { id:"fr-t-but", type:"flip", cat:"Travel & Crossing", front:"Quel est le but de votre voyage ?", back:"What is the purpose of your trip?" },
  { id:"fr-t-aide", type:"flip", cat:"Travel & Crossing", front:"Qui vous a aidé à traverser ?", back:"Who helped you cross?" },
  { id:"fr-t-paye", type:"flip", cat:"Travel & Crossing", front:"Combien avez-vous payé ?", back:"How much did you pay?" },

  // ---------- Medical & Safety ----------
  { id:"fr-m-blesse", type:"flip", cat:"Medical & Safety", front:"Êtes-vous blessé ?", back:"Are you hurt?", note:"To a woman: « blessée »." },
  { id:"fr-m-mal", type:"flip", cat:"Medical & Safety", front:"Où avez-vous mal ?", back:"Where does it hurt?" },
  { id:"fr-m-froid", type:"flip", cat:"Medical & Safety", front:"Avez-vous froid ?", back:"Are you cold?", note:"Like Spanish « tener frío », French uses avoir: « j'ai froid »." },
  { id:"fr-m-mouille", type:"flip", cat:"Medical & Safety", front:"Vos vêtements sont-ils mouillés ?", back:"Are your clothes wet?" },
  { id:"fr-m-marcher", type:"flip", cat:"Medical & Safety", front:"Pouvez-vous marcher ?", back:"Can you walk?" },
  { id:"fr-m-medecin", type:"flip", cat:"Medical & Safety", front:"Avez-vous besoin d'un médecin ?", back:"Do you need a doctor?" },
  { id:"fr-m-medicaments", type:"flip", cat:"Medical & Safety", front:"Prenez-vous des médicaments ?", back:"Do you take any medication?" },
  { id:"fr-m-sante", type:"flip", cat:"Medical & Safety", front:"Avez-vous des problèmes de santé ?", back:"Do you have any health problems?" },
  { id:"fr-m-enceinte", type:"flip", cat:"Medical & Safety", front:"Êtes-vous enceinte ?", back:"Are you pregnant?" },
  { id:"fr-m-armes", type:"flip", cat:"Medical & Safety", front:"Avez-vous des armes ?", back:"Do you have any weapons?" },
  { id:"fr-m-poches", type:"flip", cat:"Medical & Safety", front:"Avez-vous quelque chose de pointu dans vos poches ?", back:"Do you have anything sharp in your pockets?" },
  { id:"fr-m-secours", type:"flip", cat:"Medical & Safety", front:"Les secours arrivent.", back:"Help is on the way." },
  { id:"fr-m-respirez", type:"flip", cat:"Medical & Safety", front:"Respirez lentement.", back:"Breathe slowly." },

  // ---------- What You'll Hear ----------
  { id:"fr-h-sais", type:"flip", cat:"What You'll Hear", front:"Je ne sais pas.", back:"I don't know." },
  { id:"fr-h-perdu", type:"flip", cat:"What You'll Hear", front:"Je suis perdu.", back:"I'm lost.", note:"Woman: « perdue »." },
  { id:"fr-h-canadien", type:"flip", cat:"What You'll Hear", front:"Je suis canadien.", back:"I'm Canadian.", note:"Woman: « canadienne »." },
  { id:"fr-h-rando", type:"flip", cat:"What You'll Hear", front:"Je fais de la randonnée.", back:"I'm hiking." },
  { id:"fr-h-rien", type:"flip", cat:"What You'll Hear", front:"Je n'ai rien fait.", back:"I didn't do anything." },
  { id:"fr-h-avocat", type:"flip", cat:"What You'll Hear", front:"Je veux parler à un avocat.", back:"I want to speak to a lawyer.", note:"« Avocat » = lawyer (and avocado). Treat it as a request for counsel." },
  { id:"fr-h-aide", type:"flip", cat:"What You'll Hear", front:"J'ai besoin d'aide.", back:"I need help." },
  { id:"fr-h-mc", type:"mc", cat:"What You'll Hear", q:"A subject says « Je veux parler à un avocat. » What is the request?", choices:["Food","A lawyer","An interpreter","The consulate"], answer:1, explain:"Avocat = lawyer." },

  // ---------- Québec Usage (each sourced) ----------
  { id:"fr-q-repas", type:"flip", cat:"Québec Usage", front:"In Québec: déjeuner / dîner / souper", speak:"déjeuner, dîner, souper", back:"Breakfast / lunch / supper.", flag:"In France: petit-déjeuner / déjeuner / dîner. « Dîner » means lunch in Québec but dinner in France.",
    why:"« J'ai mangé au dîner » gives a noon time in Québec. That matters for a timeline.",
    source:"OQLF, Vitrine linguistique: meal names (déjeuner, dîner, souper)", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/redirection/ficheuid/8872574" },
  { id:"fr-q-cell", type:"flip", cat:"Québec Usage", front:"« cellulaire » / « cell »", back:"Cell phone.", flag:"France: « portable ». Québec: « cellulaire ».",
    source:"OQLF, Grand dictionnaire terminologique: téléphone cellulaire", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/8393991/telephone-cellulaire" },
  { id:"fr-q-stationnement", type:"flip", cat:"Québec Usage", front:"« stationnement »", back:"Parking / parking lot.", flag:"France commonly says « parking ». The OQLF discourages it; Québec signage uses « stationnement ».",
    source:"OQLF, Grand dictionnaire terminologique: parc de stationnement", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/fiche-gdt/fiche/1298970/parc-de-stationnement" },
  { id:"fr-q-bienvenue", type:"flip", cat:"Québec Usage", front:"« Merci ! » — « Bienvenue ! »", back:"Thank you! — You're welcome!", flag:"Heard in Québec as a calque of English \"you're welcome\". The OQLF discourages it. Standard: « Je vous en prie » or « De rien ».",
    source:"OQLF, Banque de dépannage linguistique: emploi déconseillé de l'emprunt « bienvenue »", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/21469/les-emprunts-a-langlais/emprunts-semantiques/emploi-deconseille-de-lemprunt-bienvenue" },
  { id:"fr-q-depanneur", type:"flip", cat:"Québec Usage", front:"« le dépanneur »", back:"Convenience store.", note:"From dépanner, to help out of a jam. Common in Québec English too.",
    why:"A frequent stop or meeting point in a timeline.",
    source:"The Canadian Encyclopedia: Dépanneur", verified:"https://prod-front.thecanadianencyclopedia.ca/en/article/depanneur" },
  { id:"fr-q-arret", type:"flip", cat:"Québec Usage", front:"Stop sign reading « ARRÊT »", speak:"Arrêt", back:"Stop.", flag:"Québec signs say ARRÊT (or STOP, but not both on one sign since 1992). France uses STOP.",
    source:"OQLF, Grand dictionnaire terminologique: panneau ARRÊT", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/redirection/ficheuid/8366697" },
  { id:"fr-q-piastre", type:"flip", cat:"Québec Usage", front:"« une piastre » / « une piasse »", back:"A dollar (informal).", note:"« Vingt piasses » = twenty bucks.",
    why:"Comes up when you ask « Combien avez-vous payé ? ».",
    source:"OQLF, Banque de dépannage linguistique: différence entre dollar et piastre", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/23978/le-vocabulaire/nuances-semantiques/difference-entre-dollar-et-piastre" },
  { id:"fr-q-char", type:"flip", cat:"Québec Usage", front:"« mon char »", back:"My car (informal Québécois).", flag:"Standard: « ma voiture ». In standard French « char » usually means a tank.",
    source:"Larousse French-English dictionary: char (Québec, familiar)", verified:"https://www.larousse.fr/dictionnaires/francais-anglais/char/14579" },
  { id:"fr-q-chum", type:"flip", cat:"Québec Usage", front:"« mon chum » / « ma blonde »", back:"My boyfriend / my girlfriend.", note:"« Blonde » = girlfriend whatever her hair color. « Chum » can also mean a buddy.",
    why:"How a subject will describe who they're traveling with or meeting.",
    flag:"Secondary source only. See UNVERIFIED.md.",
    source:"Québec City tourism glossary: 100 expressions québécoises", verified:"https://www.quebec-cite.com/fr/ville-quebec/expressions-quebecoises" },
  { id:"fr-q-tu", type:"flip", cat:"Québec Usage", front:"A Québécois subject calls you « tu »", speak:"tu, vous", back:"Common in Québec, where « tu » is used far more than in France, including with strangers. It isn't necessarily disrespect. Keep using « vous » yourself.",
    source:"Université Laval, Life and culture in Québec: French", verified:"https://www.ulaval.ca/en/student-zone/international-student-community/life-and-culture-in-quebec/french" },
  { id:"fr-q-ramq", type:"flip", cat:"Québec Usage", front:"« ma carte d'assurance maladie » / « ma carte soleil »", back:"My Québec health insurance card (issued by the RAMQ).",
    why:"A common piece of ID a Québec resident may offer.",
    source:"Immigrant Québec: carte d'assurance maladie (RAMQ)", verified:"https://immigrantquebec.com/fr/reussir-votre-installation/demarches-des-premiers-jours/" },
  { id:"fr-q-saaq", type:"flip", cat:"Québec Usage", front:"« mon permis de la SAAQ »", back:"My Québec driver's license (issued by the Société de l'assurance automobile du Québec).",
    source:"Société de l'assurance automobile du Québec (SAAQ)", verified:"https://saaq.gouv.qc.ca/prendre-un-rendez-vous/details/2" },
  { id:"fr-q-mc-diner", type:"mc", cat:"Québec Usage", q:"A Québécois driver says « On s'est arrêtés pour dîner. » Around what time?",
    choices:["Morning","Midday","Evening","Late night"], answer:1, explain:"In Québec, dîner is the midday meal.",
    source:"OQLF, Vitrine linguistique: meal names (déjeuner, dîner, souper)", verified:"https://vitrinelinguistique.oqlf.gouv.qc.ca/redirection/ficheuid/8872574" },
  ],
};
