// LAND NAV — navigation terms and strategies, compass, declination, pace count, terrain. Source: TC 3-25.26 (U.S. Army,
// Map Reading and Land Navigation) unless a card says otherwise. Arithmetic cards are self-checking.
// No real grids, place names or local declination values (OPSEC): every example is generic.
const TC = "TC 3-25.26, Map Reading and Land Navigation (U.S. Army)";
const ORI = "Orienteering technique (common land-navigation usage; not TC 3-25.26 wording)";
export default {
  meta: { id:"landnav", name:"Land Nav", short:"NAV", color:"#A3B86C", order:10,
    blurb:"Basic navigation terms, compass use, pace count and terrain features.",
    source: TC,
    subModes:["browse"] },
  categories: {
    "Terms & Strategies": { why:"Choosing the right technique for the leg is most of navigation." },
    "Compass & Declination": { why:"A wrong conversion puts you a few hundred meters off per kilometer walked." },
    "Pace & Distance": { why:"When GPS fails in deep woods or cold, pace count is how you know how far you've gone." },
    "Terrain": { why:"Matching contour shapes to the ground is how you confirm where you are." },
    "Map": { why:"Reading the map's colors and margin quickly saves time on the ground." },
  },
  cards: [
  // ---------------- terms & strategies ----------------
  { id:"ln-azimuth", type:"flip", cat:"Terms & Strategies",
    front:"Azimuth",
    back:"A horizontal angle measured clockwise from a north base line, 0° to 360°. East = 90°, south = 180°, west = 270°.",
    note:"Always know which north it's measured from: grid, magnetic or true.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Azimuth" },
  { id:"ln-norths", type:"flip", cat:"Terms & Strategies",
    front:"The three norths",
    back:"True north: toward the geographic North Pole (where meridians meet). Magnetic north: where the compass needle points; it drifts over time. Grid north: the direction of the map's vertical grid lines.",
    source:TC, verified:"https://maptools.com/learn/north-references" },
  { id:"ln-norths-mc", type:"mc", cat:"Terms & Strategies",
    q:"Your compass needle points to…",
    choices:["True north","Magnetic north","Grid north","Whichever north the map uses"],
    answer:1, explain:"The needle points to magnetic north. Grid north is the map's grid lines. True north is the geographic pole.",
    source:TC, verified:"https://maptools.com/learn/north-references" },
  { id:"ln-orient", type:"flip", cat:"Terms & Strategies",
    front:"Orienting the map",
    back:"Turning the map so its north matches north on the ground, so the terrain lines up with what you see. By compass: account for declination, then turn the map until map north matches the needle. By terrain association: hold the map level and match map features to ground features.",
    note:"Army task standard for terrain association: oriented to within 30° of magnetic north.",
    source:TC, verified:"https://sofrep.com/specialoperations/selection-land-nav-basics-pinpoint-location-orient-map/" },
  { id:"ln-terrain-assoc", type:"flip", cat:"Terms & Strategies",
    front:"Terrain association",
    back:"Navigating by recognizing natural and man-made features around you and matching them to the map: hills, draws, streams, roads.",
    why:"Faster than compass-and-pace in good visibility, and it keeps you aware of where you are.",
    source:"TC 3-25.26, ch. 11 (terrain association navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-dead-reckoning", type:"flip", cat:"Terms & Strategies",
    front:"Dead reckoning",
    back:"Navigating from a known point by direction and distance: hold a set azimuth and keep a pace count to estimate where you are.",
    why:"Your method when terrain features are useless: dense woods, fog, darkness, flat ground.",
    source:"TC 3-25.26, ch. 11 (dead reckoning navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-handrail", type:"flip", cat:"Terms & Strategies",
    front:"Handrail",
    back:"A linear feature running along your route that you can follow: a stream, fence, road, power line, firebreak.",
    source:ORI, verified:"https://brainscape.com/flashcards/navigation-definitions-8369224/packs/14191102" },
  { id:"ln-catching", type:"flip", cat:"Terms & Strategies",
    front:"Catching feature",
    back:"An obvious feature (usually linear) just beyond your objective. If you hit it, you know you've gone too far.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-collecting", type:"flip", cat:"Terms & Strategies",
    front:"Collecting features",
    back:"Distinctive features you pass along the route that confirm you're on track and tell you how far you've come.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-attack", type:"flip", cat:"Terms & Strategies",
    front:"Attack point",
    back:"An obvious, easy-to-find feature close to your objective. Navigate fast to it, then make a short, careful compass-and-pace leg to the objective.",
    source:ORI, verified:"https://oq.orienteering.asn.au/forms-and-downloads/download/attack-points-pamphlet-2" },
  { id:"ln-holds", type:"flip", cat:"Terms & Strategies",
    front:"Center-hold vs. compass-to-cheek",
    back:"Center-hold: compass held at the belly, turn your whole body. Used on the move to hold a general direction. Compass-to-cheek: sight through the wire to the target. Used when you need a precise azimuth.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-detour", type:"order", cat:"Terms & Strategies",
    q:"Bypassing an obstacle with 90° turns (detour method). Put the legs in order.",
    steps:["Turn 90° right (add 90°) and pace until you clear the obstacle's width","Turn back to the original azimuth and pace along the obstacle's length — these paces count toward your route","Turn 90° left (subtract 90°) and pace the same width back","Turn to the original azimuth and continue"],
    explain:"Four legs around a box. The width legs cancel out, and the length leg adds to your route pace count.",
    source:"USMC detour method; TC 3-25.26 (bypassing obstacles)", verified:"https://snipercentral.com/nav-bypass.htm" },
  { id:"ln-stop", type:"order", cat:"Terms & Strategies",
    q:"You realize you're lost. Put the STOP steps in order.",
    steps:["Stop: halt and stay calm","Think: back to your last known point and the time since","Observe: orient the map, find north, look for features","Plan: pick your next move, or stay put if unsure"],
    explain:"Stop, Think, Observe, Plan. Moving without a plan usually makes it worse.",
    source:"STOP mnemonic (common wilderness-navigation practice)", verified:"https://www.people.vcu.edu/~albest/troop700/documents/StayingFoundWhatIfLost.pdf" },
  { id:"ln-sc-handrail", type:"scenario", cat:"Terms & Strategies",
    setup:"Your route parallels a stream for most of the leg before you cut uphill to your objective.",
    q:"What is the stream for that stretch?",
    choices:["A handrail","An attack point","A catching feature","A collecting feature only"],
    answer:0, explain:"Follow it as a handrail, then leave it at a planned point.",
    source:ORI, verified:"https://brainscape.com/flashcards/navigation-definitions-8369224/packs/14191102" },
  { id:"ln-sc-catching", type:"scenario", cat:"Terms & Strategies",
    setup:"A paved road runs east–west about 300 m past your objective.",
    q:"How do you use the road?",
    choices:["As a catching feature: hit the road and you know you overshot","As your attack point","As a handrail all the way","Ignore it"],
    answer:0, explain:"A catching feature stops an overshoot from turning into a long search.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-sc-attack", type:"scenario", cat:"Terms & Strategies",
    setup:"Your objective is a small spot in thick woods. 200 m from it there's an obvious stream junction.",
    q:"Best plan?",
    choices:["Move fast to the stream junction (attack point), then a short compass-and-pace leg in","One long compass leg from the start","Wander until you find it","Wait for daylight"],
    answer:0, explain:"Use the easy-to-find feature as your attack point and save the precise work for the short final leg.",
    source:ORI, verified:"https://oq.orienteering.asn.au/forms-and-downloads/download/attack-points-pamphlet-2" },
  { id:"ln-sc-fog", type:"scenario", cat:"Terms & Strategies",
    setup:"Thick fog in flat, featureless woods. You can't see any landmarks.",
    q:"Which method?",
    choices:["Terrain association","Dead reckoning: azimuth plus pace count","Follow the nearest handrail wherever it goes","Wait for the fog to lift"],
    answer:1, explain:"With no visible features to match, hold a compass azimuth and keep a pace count.",
    source:"TC 3-25.26, ch. 11 (dead reckoning navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-sc-hold", type:"mc", cat:"Terms & Strategies",
    q:"You need a precise azimuth to a distant hilltop. Which compass hold?",
    choices:["Center-hold","Compass-to-cheek","Either is equally precise","Hold it at arm's length"],
    answer:1, explain:"Compass-to-cheek sights through the wire, which is more precise. Center-hold is for holding direction on the move.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },

  // ---------------- Compass & Declination ----------------
  { id:"ln-backaz", type:"flip", cat:"Compass & Declination",
    front:"Back azimuth rule",
    back:"Azimuth less than 180°: add 180. Azimuth 180° or more: subtract 180.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-backaz-calc", type:"mc", cat:"Compass & Declination",
    q:"Back azimuth of 250°?",
    choices:["70°","430°","110°","160°"],
    answer:0, explain:"250 is 180 or more, so subtract 180: 70°.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-declination", type:"flip", cat:"Compass & Declination",
    front:"Declination",
    back:"The difference between where your compass points (magnetic north) and the map's north. The diagram in the map's margin shows the angle and tells you whether to add or subtract it.",
    note:"Read the margin of the map you're carrying. Don't guess.",
    source:TC, verified:"https://maptools.com/learn/north-references" },
  { id:"ln-pace-count", type:"flip", cat:"Pace & Distance",
    front:"Pace count",
    back:"The number of paces it takes you to walk 100 meters. Know yours, and count as you move to track how far you've gone.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-vehicle", type:"mc", cat:"Compass & Declination",
    q:"Minimum distance from a truck to get a trustworthy compass reading?",
    choices:["2 m","10 m","18 m","55 m"],
    answer:2, explain:"About 18 m for a truck, field gun or tank. Power lines need 55 m.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },

  // ---------------- Pace & Distance ----------------
  { id:"ln-pace-factors", type:"flip", cat:"Pace & Distance",
    front:"Five conditions that change your pace",
    back:"Slopes, winds, surfaces, elements, visibility.",
    note:"Uphill shortens the pace and downhill lengthens it. A headwind shortens it and a tailwind lengthens it. Sand, mud and snow shorten it. Falling snow, rain and ice shorten it. Poor visibility shortens it.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-snow", type:"scenario", cat:"Pace & Distance",
    setup:"Deep snow, going uphill, in a light snowfall. Your normal count is 120 per 100 m.",
    q:"What happens to your count per 100 m?",
    choices:["Goes down","Stays the same","Goes up: pace is shorter, so more paces per 100 m","Can't be predicted"],
    answer:2, explain:"Upslope, snow surface and falling snow all shorten the pace. Expect well over 120.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },

  // ---------------- Terrain ----------------
  { id:"ln-t-hill", type:"flip", cat:"Terrain", front:"From the top, ground slopes down in every direction.", back:"HILL (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-saddle", type:"flip", cat:"Terrain", front:"Dip between two hills: up on two sides, down on two sides.", back:"SADDLE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-valley", type:"flip", cat:"Terrain", front:"Low ground between higher areas, often with a stream.", back:"VALLEY (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-ridge", type:"flip", cat:"Terrain", front:"A sloping line of high ground.", back:"RIDGE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-depression", type:"flip", cat:"Terrain", front:"Low point or sinkhole, surrounded by higher ground.", back:"DEPRESSION (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-draw", type:"flip", cat:"Terrain", front:"A small valley, sometimes called a re-entrant.", back:"DRAW (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-spur", type:"flip", cat:"Terrain", front:"Short sloping high ground jutting out from a ridge.", back:"SPUR (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-cliff", type:"flip", cat:"Terrain", front:"Vertical or near-vertical drop.", back:"CLIFF (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  // ---------------- Map ----------------
  { id:"ln-color-mc", type:"mc", cat:"Map",
    q:"On a military topo map, green shows…",
    choices:["Water","Vegetation","Man-made features","Relief"],
    answer:1, explain:"Green = vegetation (woods, orchards). Blue = water, brown = relief, black = man-made.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/FMTBE/Student%20Materials/FMSO%20Manual/212.pdf" },
  // ---------------- batch 3 ----------------
  { id:"ln-slope-mc", type:"mc", cat:"Terrain",
    q:"Contour lines bunched tightly together mean…",
    choices:["Gentle slope","Steep slope","A depression","A road cut"],
    answer:1, explain:"Close spacing = steep. Wide spacing = gentle.",
    source:TC, verified:"https://alanwood.co.uk/news/understanding-contour-lines-on-topographic-maps" },
  ],
};
