// LAND NAV — navigation terms and strategies, compass, declination, pace count, terrain. Source: TC 3-25.26 (U.S. Army,
// Map Reading and Land Navigation) unless a card says otherwise. Arithmetic cards are self-checking.
// No real grids, place names or local declination values (OPSEC): every example is generic.
const TC = "TC 3-25.26, Map Reading and Land Navigation (U.S. Army)";
const ORI = "Orienteering technique (common land-navigation usage; not TC 3-25.26 wording)";
export default {
  meta: { id:"landnav", name:"Land Nav", short:"NAV", color:"#A3B86C", order:10,
    blurb:"Navigation terms and strategies, compass work, declination, pace count and terrain.",
    source: TC,
    subModes:["browse"] },
  categories: {
    "Terms & Strategies": { why:"Choosing the right technique for the leg is most of navigation." },
    "Compass & Declination": { why:"A wrong conversion puts you a few hundred meters off per kilometer walked." },
    "Pace & Distance": { why:"When GPS fails in deep woods or cold, pace count is how you know how far you've gone." },
    "Terrain": { why:"Matching contour shapes to the ground is how you confirm where you are." },
    "Map": { why:"Reading the map's colors and margin quickly saves time on the ground." },
  },
  cards: [
  // ---------------- terms & strategies ----------------
  { id:"ln-azimuth", type:"flip", cat:"Terms & Strategies",
    front:"Azimuth",
    back:"A horizontal angle measured clockwise from a north base line, 0° to 360°. East = 90°, south = 180°, west = 270°.",
    note:"Always know which north it's measured from: grid, magnetic or true.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Azimuth" },
  { id:"ln-norths", type:"flip", cat:"Terms & Strategies",
    front:"The three norths",
    back:"True north: toward the geographic North Pole (where meridians meet). Magnetic north: where the compass needle points; it drifts over time. Grid north: the direction of the map's vertical grid lines.",
    source:TC, verified:"https://maptools.com/learn/north-references" },
  { id:"ln-norths-mc", type:"mc", cat:"Terms & Strategies",
    q:"Your compass needle points to…",
    choices:["True north","Magnetic north","Grid north","Whichever north the map uses"],
    answer:1, explain:"The needle points to magnetic north. Grid north is the map's grid lines. True north is the geographic pole.",
    source:TC, verified:"https://maptools.com/learn/north-references" },
  { id:"ln-orient", type:"flip", cat:"Terms & Strategies",
    front:"Orienting the map",
    back:"Turning the map so its north matches north on the ground, so the terrain lines up with what you see. By compass: account for declination, then turn the map until map north matches the needle. By terrain association: hold the map level and match map features to ground features.",
    note:"Army task standard for terrain association: oriented to within 30° of magnetic north.",
    source:TC, verified:"https://sofrep.com/specialoperations/selection-land-nav-basics-pinpoint-location-orient-map/" },
  { id:"ln-terrain-assoc", type:"flip", cat:"Terms & Strategies",
    front:"Terrain association",
    back:"Navigating by recognizing natural and man-made features around you and matching them to the map: hills, draws, streams, roads.",
    why:"Faster than compass-and-pace in good visibility, and it keeps you aware of where you are.",
    source:"TC 3-25.26, ch. 11 (terrain association navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-dead-reckoning", type:"flip", cat:"Terms & Strategies",
    front:"Dead reckoning",
    back:"Navigating from a known point by direction and distance: hold a set azimuth and keep a pace count to estimate where you are.",
    why:"Your method when terrain features are useless: dense woods, fog, darkness, flat ground.",
    source:"TC 3-25.26, ch. 11 (dead reckoning navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-handrail", type:"flip", cat:"Terms & Strategies",
    front:"Handrail",
    back:"A linear feature running along your route that you can follow: a stream, fence, road, power line, firebreak.",
    source:ORI, verified:"https://brainscape.com/flashcards/navigation-definitions-8369224/packs/14191102" },
  { id:"ln-catching", type:"flip", cat:"Terms & Strategies",
    front:"Catching feature",
    back:"An obvious feature (usually linear) just beyond your objective. If you hit it, you know you've gone too far.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-collecting", type:"flip", cat:"Terms & Strategies",
    front:"Collecting features",
    back:"Distinctive features you pass along the route that confirm you're on track and tell you how far you've come.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-attack", type:"flip", cat:"Terms & Strategies",
    front:"Attack point",
    back:"An obvious, easy-to-find feature close to your objective. Navigate fast to it, then make a short, careful compass-and-pace leg to the objective.",
    source:ORI, verified:"https://oq.orienteering.asn.au/forms-and-downloads/download/attack-points-pamphlet-2" },
  { id:"ln-holds", type:"flip", cat:"Terms & Strategies",
    front:"Center-hold vs. compass-to-cheek",
    back:"Center-hold: compass held at the belly, turn your whole body. Used on the move to hold a general direction. Compass-to-cheek: sight through the wire to the target. Used when you need a precise azimuth.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-detour", type:"order", cat:"Terms & Strategies",
    q:"Bypassing an obstacle with 90° turns (detour method). Put the legs in order.",
    steps:["Turn 90° right (add 90°) and pace until you clear the obstacle's width","Turn back to the original azimuth and pace along the obstacle's length — these paces count toward your route","Turn 90° left (subtract 90°) and pace the same width back","Turn to the original azimuth and continue"],
    explain:"Four legs around a box. The width legs cancel out, and the length leg adds to your route pace count.",
    source:"USMC detour method; TC 3-25.26 (bypassing obstacles)", verified:"https://snipercentral.com/nav-bypass.htm" },
  { id:"ln-stop", type:"order", cat:"Terms & Strategies",
    q:"You realize you're lost. Put the STOP steps in order.",
    steps:["Stop: halt and stay calm","Think: back to your last known point and the time since","Observe: orient the map, find north, look for features","Plan: pick your next move, or stay put if unsure"],
    explain:"Stop, Think, Observe, Plan. Moving without a plan usually makes it worse.",
    source:"STOP mnemonic (common wilderness-navigation practice)", verified:"https://www.people.vcu.edu/~albest/troop700/documents/StayingFoundWhatIfLost.pdf" },
  { id:"ln-sc-handrail", type:"scenario", cat:"Terms & Strategies",
    setup:"Your route parallels a stream for most of the leg before you cut uphill to your objective.",
    q:"What is the stream for that stretch?",
    choices:["A handrail","An attack point","A catching feature","A collecting feature only"],
    answer:0, explain:"Follow it as a handrail, then leave it at a planned point.",
    source:ORI, verified:"https://brainscape.com/flashcards/navigation-definitions-8369224/packs/14191102" },
  { id:"ln-sc-catching", type:"scenario", cat:"Terms & Strategies",
    setup:"A paved road runs east–west about 300 m past your objective.",
    q:"How do you use the road?",
    choices:["As a catching feature: hit the road and you know you overshot","As your attack point","As a handrail all the way","Ignore it"],
    answer:0, explain:"A catching feature stops an overshoot from turning into a long search.",
    source:ORI, verified:"https://www.theoutbound.com/sarah-seads/3-easy-steps-to-navigating-the-backcountry" },
  { id:"ln-sc-attack", type:"scenario", cat:"Terms & Strategies",
    setup:"Your objective is a small spot in thick woods. 200 m from it there's an obvious stream junction.",
    q:"Best plan?",
    choices:["Move fast to the stream junction (attack point), then a short compass-and-pace leg in","One long compass leg from the start","Wander until you find it","Wait for daylight"],
    answer:0, explain:"Use the easy-to-find feature as your attack point and save the precise work for the short final leg.",
    source:ORI, verified:"https://oq.orienteering.asn.au/forms-and-downloads/download/attack-points-pamphlet-2" },
  { id:"ln-sc-fog", type:"scenario", cat:"Terms & Strategies",
    setup:"Thick fog in flat, featureless woods. You can't see any landmarks.",
    q:"Which method?",
    choices:["Terrain association","Dead reckoning: azimuth plus pace count","Resection","Intersection"],
    answer:1, explain:"With no visible features to match, hold a compass azimuth and keep a pace count.",
    source:"TC 3-25.26, ch. 11 (dead reckoning navigation)", verified:"https://armyrotc.mst.edu/media/academic/armyrotc/documents/manualsadpadrpfmetc/TC 3-25.26.pdf" },
  { id:"ln-sc-hold", type:"mc", cat:"Terms & Strategies",
    q:"You need a precise azimuth to a distant hilltop for a resection. Which compass hold?",
    choices:["Center-hold","Compass-to-cheek","Either is equally precise","Hold it at arm's length"],
    answer:1, explain:"Compass-to-cheek sights through the wire, which is more precise. Center-hold is for holding direction on the move.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },

  // ---------------- Compass & Declination ----------------
  { id:"ln-backaz", type:"flip", cat:"Compass & Declination",
    front:"Back azimuth rule",
    back:"Azimuth less than 180°: add 180. Azimuth 180° or more: subtract 180.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-backaz-calc", type:"mc", cat:"Compass & Declination",
    q:"Back azimuth of 250°?",
    choices:["70°","430°","110°","160°"],
    answer:0, explain:"250 is 180 or more, so subtract 180: 70°.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-backaz-calc2", type:"mc", cat:"Compass & Declination",
    q:"Back azimuth of 035°?",
    choices:["145°","215°","325°","395°"],
    answer:1, explain:"35 is less than 180, so add 180: 215°.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-gm-diagram", type:"flip", cat:"Compass & Declination",
    front:"Where do you get the G-M angle and the conversion direction?",
    back:"From the declination diagram in the map margin. It gives the grid-magnetic (G-M) angle and a note telling you whether to add or subtract for that sheet.",
    note:"Declination drifts over the years. Use the diagram on the map you're carrying.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-west", type:"flip", cat:"Compass & Declination",
    front:"WESTERLY G-M angle: converting",
    back:"Grid → magnetic: ADD the G-M angle. Magnetic → grid: SUBTRACT it.",
    note:"Magnetic north lies west of grid north, so magnetic azimuths read larger.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-east", type:"flip", cat:"Compass & Declination",
    front:"EASTERLY G-M angle: converting",
    back:"Magnetic → grid: ADD the G-M angle. Grid → magnetic: SUBTRACT it.",
    note:"The reverse of westerly. LARS (Left Add, Right Subtract) works off the diagram's arrows.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-conv-w", type:"scenario", cat:"Compass & Declination",
    setup:"You plot a grid azimuth of 090° on the map. The declination diagram shows a 10° westerly G-M angle.",
    q:"What magnetic azimuth do you set on the compass?",
    choices:["080°","090°","100°","270°"],
    answer:2, explain:"Westerly, grid → magnetic: add. 090 + 10 = 100°.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-conv-w2", type:"scenario", cat:"Compass & Declination",
    setup:"You shoot a magnetic azimuth of 200° to a landmark. G-M angle is 10° westerly.",
    q:"What grid azimuth do you plot?",
    choices:["190°","200°","210°","020°"],
    answer:0, explain:"Westerly, magnetic → grid: subtract. 200 − 10 = 190°.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-interference", type:"order", cat:"Compass & Declination",
    q:"Order these by safe compass distance, largest first.",
    steps:["High-tension power lines","Field gun, truck or tank","Telephone or barbed wire"],
    explain:"Power lines 55 m, field gun/truck/tank 18 m, telephone or barbed wire 10 m. Step away from the vehicle before you shoot an azimuth.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-vehicle", type:"mc", cat:"Compass & Declination",
    q:"Minimum distance from a truck to get a trustworthy compass reading?",
    choices:["2 m","10 m","18 m","55 m"],
    answer:2, explain:"About 18 m for a truck, field gun or tank. Power lines need 55 m.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },

  // ---------------- Pace & Distance ----------------
  { id:"ln-pace-calc", type:"mc", cat:"Pace & Distance",
    q:"Your pace count is 120 per 100 m. How many paces for 450 m?",
    choices:["375","450","540","570"],
    answer:2, explain:"4.5 × 120 = 540.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-dist", type:"mc", cat:"Pace & Distance",
    q:"Pace count 64 per 100 m. You've counted 256. Distance covered?",
    choices:["256 m","400 m","164 m","320 m"],
    answer:1, explain:"256 ÷ 64 = 4 hundreds = 400 m.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-factors", type:"flip", cat:"Pace & Distance",
    front:"Five conditions that change your pace",
    back:"Slopes, winds, surfaces, elements, visibility.",
    note:"Uphill shortens the pace and downhill lengthens it. A headwind shortens it and a tailwind lengthens it. Sand, mud and snow shorten it. Falling snow, rain and ice shorten it. Poor visibility shortens it.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-snow", type:"scenario", cat:"Pace & Distance",
    setup:"Deep snow, going uphill, in a light snowfall. Your normal count is 120 per 100 m.",
    q:"What happens to your count per 100 m?",
    choices:["Goes down","Stays the same","Goes up: pace is shorter, so more paces per 100 m","Can't be predicted"],
    answer:2, explain:"Upslope, snow surface and falling snow all shorten the pace. Expect well over 120.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },

  // ---------------- Terrain ----------------
  { id:"ln-t-hill", type:"flip", cat:"Terrain", front:"From the top, ground slopes down in every direction.", back:"HILL (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-saddle", type:"flip", cat:"Terrain", front:"Dip between two hills: up on two sides, down on two sides.", back:"SADDLE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-valley", type:"flip", cat:"Terrain", front:"Low ground between higher areas, often with a stream.", back:"VALLEY (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-ridge", type:"flip", cat:"Terrain", front:"A sloping line of high ground.", back:"RIDGE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-depression", type:"flip", cat:"Terrain", front:"Low point or sinkhole, surrounded by higher ground.", back:"DEPRESSION (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-draw", type:"flip", cat:"Terrain", front:"A small valley, sometimes called a re-entrant.", back:"DRAW (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-spur", type:"flip", cat:"Terrain", front:"Short sloping high ground jutting out from a ridge.", back:"SPUR (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-cliff", type:"flip", cat:"Terrain", front:"Vertical or near-vertical drop.", back:"CLIFF (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-cut", type:"flip", cat:"Terrain", front:"Man-made cut through high ground, e.g. for a road or rail line.", back:"CUT (supplementary)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-fill", type:"flip", cat:"Terrain", front:"Man-made fill raising a low area, e.g. a road bed.", back:"FILL (supplementary)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-counts", type:"mc", cat:"Terrain",
    q:"Terrain features: how many major, minor and supplementary?",
    choices:["5 / 3 / 2","4 / 4 / 2","3 / 5 / 2","5 / 2 / 3"],
    answer:0, explain:"Major: hill, saddle, valley, ridge, depression. Minor: draw, spur, cliff. Supplementary: cut, fill.",
    source:TC, verified:"https://brainscape.com/flashcards/land-nav-11330285/packs/20039434" },

  // ---------------- Map ----------------
  { id:"ln-colors", type:"flip", cat:"Map",
    front:"Military map colors",
    back:"Black: man-made features and labels. Blue: water. Green: vegetation. Brown: relief and contours. Red-brown: combined cultural and relief on red-light-readable maps. Red: populated areas, main roads, boundaries (older maps).",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/FMTBE/Student%20Materials/FMSO%20Manual/212.pdf" },
  { id:"ln-color-mc", type:"mc", cat:"Map",
    q:"On a military topo map, green shows…",
    choices:["Water","Vegetation","Man-made features","Relief"],
    answer:1, explain:"Green = vegetation (woods, orchards). Blue = water, brown = relief, black = man-made.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/FMTBE/Student%20Materials/FMSO%20Manual/212.pdf" },
  // ---------------- batch 3 ----------------
  { id:"ln-intersection", type:"flip", cat:"Compass & Declination",
    front:"Intersection",
    back:"Locating an UNKNOWN distant point from two or three KNOWN positions: shoot an azimuth from each known point to the target and plot them. The target is where the lines cross.",
    note:"You occupy known points and sight to the unknown one.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Position_resection_and_intersection" },
  { id:"ln-resection", type:"flip", cat:"Compass & Declination",
    front:"Resection",
    back:"Locating YOUR OWN position: shoot azimuths to two (three is better) features you can identify on the map, convert them to back azimuths, and plot those lines from the features. You're where they cross.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Position_resection_and_intersection" },
  { id:"ln-mod-resection", type:"flip", cat:"Compass & Declination",
    front:"Modified resection",
    back:"When you're on a linear feature (road, stream, power line), one azimuth to a known feature is enough. Plot its back azimuth from the feature, and you're where that line crosses your linear feature.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Position_resection_and_intersection" },
  { id:"ln-intersect-mc", type:"mc", cat:"Compass & Declination",
    q:"You're lost but can see two mapped hilltops. Which technique finds your position?",
    choices:["Intersection","Resection","Deliberate offset","Back azimuth only"],
    answer:1, explain:"Resection finds your own position from known features. Intersection finds a distant unknown from your known positions.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Position_resection_and_intersection" },
  { id:"ln-offset", type:"flip", cat:"Compass & Declination",
    front:"Deliberate offset (aiming off)",
    back:"When the objective sits on a linear feature (road, stream, trail), aim a known number of degrees to one side. When you hit the feature, you know which way to turn.",
    note:"Each degree of offset moves you about 17.5 m sideways per 1,000 m traveled (tan 1° × 1,000 m).",
    why:"Removes the 'left or right?' guess when you hit a road or stream.",
    source:TC, verified:"https://cacadets.org/sites/default/files/DraftCurriculum/1MilSubjects/MapsAndNav/1%20TEXT%20B_Navigation%20Tools%20and%20Activities.pdf" },
  { id:"ln-offset-calc", type:"mc", cat:"Compass & Declination",
    q:"You aim off 10° on a 2 km leg. Roughly how far to the side of the objective do you hit the road?",
    choices:["35 m","175 m","350 m","1,000 m"],
    answer:2, explain:"About 17.5 m per degree per km: 17.5 × 10 × 2 ≈ 350 m. You know which way to turn and roughly how far.",
    source:TC, verified:"https://cacadets.org/sites/default/files/DraftCurriculum/1MilSubjects/MapsAndNav/1%20TEXT%20B_Navigation%20Tools%20and%20Activities.pdf" },
  { id:"ln-bezel", type:"flip", cat:"Compass & Declination",
    front:"Lensatic compass bezel ring",
    back:"120 clicks for a full turn. Each click = 3°. To preset an azimuth for night work, divide it by 3 to get the number of clicks.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-bezel-calc", type:"mc", cat:"Compass & Declination",
    q:"How many bezel clicks to preset 135°?",
    choices:["27","45","135","15"],
    answer:1, explain:"135 ÷ 3 = 45 clicks.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-datum", type:"flip", cat:"Map",
    front:"GPS datum vs. map datum",
    back:"The datum set in your GPS must match the datum printed in the map's margin. WGS 84 vs. NAD 27 can differ by up to about 200 m. WGS 84 vs. NAD 83 is usually only a meter or two in the continental U.S.",
    note:"Older USGS quads are often NAD 27. Check the margin before passing a grid from a GPS.",
    why:"A correct grid on the wrong datum still sends the other unit to the wrong spot.",
    source:"Datum guidance: USGS topographic map practice; maptools.com datum tutorial", verified:"https://maptools.com/tutorials/map_datum" },
  { id:"ln-datum-sc", type:"scenario", cat:"Map",
    setup:"Your GPS is set to WGS 84. The paper map you're plotting on says NAD 27 in the margin. Your plotted position puts you in a pond you're not standing in.",
    q:"Most likely cause?",
    choices:["A bad compass","Datum mismatch: set the GPS to the map's datum (or convert)","Declination","Pace count"],
    answer:1, explain:"WGS 84 vs. NAD 27 can shift positions by up to about 200 m.",
    source:"Datum guidance: USGS topographic map practice; maptools.com datum tutorial", verified:"https://maptools.com/tutorials/map_datum" },
  { id:"ln-contours", type:"flip", cat:"Terrain",
    front:"Three kinds of contour line",
    back:"Index: heavier line labeled with elevation, usually every fifth line. Intermediate: thinner, unlabeled lines between index lines. Supplementary: dashed lines at half the contour interval, used where terrain is flat.",
    source:TC, verified:"https://alanwood.co.uk/news/understanding-contour-lines-on-topographic-maps" },
  { id:"ln-ci", type:"flip", cat:"Terrain",
    front:"Contour interval",
    back:"The fixed vertical distance between adjacent contour lines, stated in the map margin.",
    source:TC, verified:"https://alanwood.co.uk/news/understanding-contour-lines-on-topographic-maps" },
  { id:"ln-slope-mc", type:"mc", cat:"Terrain",
    q:"Contour lines bunched tightly together mean…",
    choices:["Gentle slope","Steep slope","A depression","A road cut"],
    answer:1, explain:"Close spacing = steep. Wide spacing = gentle.",
    source:TC, verified:"https://alanwood.co.uk/news/understanding-contour-lines-on-topographic-maps" },
  { id:"ln-scale-50k", type:"mc", cat:"Map",
    q:"On a 1:50,000 map, 1 cm equals…",
    choices:["50 m","500 m","5 km","50 km"],
    answer:1, explain:"50,000 cm = 500 m. So 2 cm = 1 km.",
    source:"Representative-fraction map scale (arithmetic)", verified:"https://digfir-published.macmillanusa.com/shellito2e/shellito2e_ch7_2.html" },
  { id:"ln-scale-24k", type:"mc", cat:"Map",
    q:"On a 1:24,000 map, 1 inch equals…",
    choices:["240 ft","1,000 ft","2,000 ft","1 mile"],
    answer:2, explain:"24,000 inches = 2,000 feet.",
    source:"Representative-fraction map scale (arithmetic)", verified:"https://digfir-published.macmillanusa.com/shellito2e/shellito2e_ch7_2.html" },
  ],
};
