// LAND NAV — MGRS/UTM, compass, declination, pace count, terrain. Source: TC 3-25.26 (U.S. Army,
// Map Reading and Land Navigation) unless a card says otherwise. Arithmetic cards are self-checking.
// No real grids, place names or local declination values (OPSEC): every example is generic.
const TC = "TC 3-25.26, Map Reading and Land Navigation (U.S. Army)";
export default {
  meta: { id:"landnav", name:"Land Nav", short:"NAV", color:"#A3B86C", order:10,
    blurb:"MGRS, compass work, declination, pace count and terrain features.",
    source: TC,
    subModes:["browse"] },
  categories: {
    "MGRS & UTM": { why:"A clean grid is how you pass a location for a pickup, a medevac or a sign-cutting handoff." },
    "Compass & Declination": { why:"A wrong conversion puts you a few hundred meters off per kilometer walked." },
    "Pace & Distance": { why:"When GPS fails in deep woods or cold, pace count is how you know how far you've gone." },
    "Terrain": { why:"Matching contour shapes to the ground is how you confirm where you are." },
    "Map": { why:"Reading the map's colors and margin quickly saves time on the ground." },
  },
  cards: [
  // ---------------- MGRS & UTM ----------------
  { id:"ln-mgrs-order", type:"order", cat:"MGRS & UTM",
    q:"Put the parts of an MGRS coordinate in order.",
    steps:["Grid zone designation (zone number + latitude band letter)","100,000-meter square identification (two letters)","Easting digits","Northing digits"],
    explain:"Zone → 100 km square → easting → northing. Format: 4Q FJ 1234 5678.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Military_Grid_Reference_System" },
  { id:"ln-right-up", type:"mc", cat:"MGRS & UTM",
    q:"How are grid coordinates read?",
    choices:["Up, then right","Right, then up","Clockwise from north","Either way if you say which"],
    answer:1, explain:"Right then up: easting first, then northing.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-precision", type:"flip", cat:"MGRS & UTM",
    front:"Grid precision: 4, 6, 8 and 10 digits",
    back:"4-digit = 1,000 m. 6-digit = 100 m. 8-digit = 10 m. 10-digit = 1 m.",
    note:"Each extra pair of digits divides the square by 10.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Military_Grid_Reference_System" },
  { id:"ln-8digit", type:"mc", cat:"MGRS & UTM",
    q:"An 8-digit grid locates a point to within…",
    choices:["1 m","10 m","100 m","1,000 m"],
    answer:1, explain:"8-digit = 10 m square. A 6-digit grid is only 100 m. Give 8 for a pickup or a medevac.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Military_Grid_Reference_System" },
  { id:"ln-utm-zones", type:"flip", cat:"MGRS & UTM",
    front:"UTM zones: how many, and how wide?",
    back:"60 zones, each 6° of longitude wide, numbered 1–60 eastward starting at 180°.",
    source:"UTM / MGRS specification", verified:"https://bluemarblegeo.com/knowledgebase/calculator-2020sp2/Military_Grid_Reference_System_(MGRS).htm" },
  { id:"ln-bands", type:"flip", cat:"MGRS & UTM",
    front:"MGRS latitude bands",
    back:"8° tall, lettered C (80° S) through X (north), skipping I and O.",
    note:"I and O are skipped so they can't be confused with 1 and 0.",
    source:"UTM / MGRS specification", verified:"https://bluemarblegeo.com/knowledgebase/calculator-2020sp2/Military_Grid_Reference_System_(MGRS).htm" },
  { id:"ln-mgrs-truncate", type:"scenario", cat:"MGRS & UTM",
    setup:"You have the 10-digit grid 12345 67890 and the receiving unit wants an 8-digit grid.",
    q:"Which is correct?",
    choices:["1234 6789","2345 7890","1234 5678","12345678"],
    answer:0, explain:"Drop the last digit of the easting and of the northing separately: 1234 / 6789. Never split one long string in half.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Military_Grid_Reference_System" },

  // ---------------- Compass & Declination ----------------
  { id:"ln-backaz", type:"flip", cat:"Compass & Declination",
    front:"Back azimuth rule",
    back:"Azimuth less than 180°: add 180. Azimuth 180° or more: subtract 180.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-backaz-calc", type:"mc", cat:"Compass & Declination",
    q:"Back azimuth of 250°?",
    choices:["70°","430°","110°","160°"],
    answer:0, explain:"250 is 180 or more, so subtract 180: 70°.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-backaz-calc2", type:"mc", cat:"Compass & Declination",
    q:"Back azimuth of 035°?",
    choices:["145°","215°","325°","395°"],
    answer:1, explain:"35 is less than 180, so add 180: 215°.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-gm-diagram", type:"flip", cat:"Compass & Declination",
    front:"Where do you get the G-M angle and the conversion direction?",
    back:"From the declination diagram in the map margin. It gives the grid-magnetic (G-M) angle and a note telling you whether to add or subtract for that sheet.",
    note:"Declination drifts over the years. Use the diagram on the map you're carrying.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-west", type:"flip", cat:"Compass & Declination",
    front:"WESTERLY G-M angle: converting",
    back:"Grid → magnetic: ADD the G-M angle. Magnetic → grid: SUBTRACT it.",
    note:"Magnetic north lies west of grid north, so magnetic azimuths read larger.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-east", type:"flip", cat:"Compass & Declination",
    front:"EASTERLY G-M angle: converting",
    back:"Magnetic → grid: ADD the G-M angle. Grid → magnetic: SUBTRACT it.",
    note:"The reverse of westerly. LARS (Left Add, Right Subtract) works off the diagram's arrows.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-conv-w", type:"scenario", cat:"Compass & Declination",
    setup:"You plot a grid azimuth of 090° on the map. The declination diagram shows a 10° westerly G-M angle.",
    q:"What magnetic azimuth do you set on the compass?",
    choices:["080°","090°","100°","270°"],
    answer:2, explain:"Westerly, grid → magnetic: add. 090 + 10 = 100°.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-conv-w2", type:"scenario", cat:"Compass & Declination",
    setup:"You shoot a magnetic azimuth of 200° to a landmark. G-M angle is 10° westerly.",
    q:"What grid azimuth do you plot?",
    choices:["190°","200°","210°","020°"],
    answer:0, explain:"Westerly, magnetic → grid: subtract. 200 − 10 = 190°.",
    source:TC, verified:"https://www.honestmos.com/field-manual/land-navigation" },
  { id:"ln-interference", type:"order", cat:"Compass & Declination",
    q:"Order these by safe compass distance, largest first.",
    steps:["High-tension power lines","Field gun, truck or tank","Telephone or barbed wire"],
    explain:"Power lines 55 m, field gun/truck/tank 18 m, telephone or barbed wire 10 m. Step away from the vehicle before you shoot an azimuth.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },
  { id:"ln-vehicle", type:"mc", cat:"Compass & Declination",
    q:"Minimum distance from a truck to get a trustworthy compass reading?",
    choices:["2 m","10 m","18 m","55 m"],
    answer:2, explain:"About 18 m for a truck, field gun or tank. Power lines need 55 m.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/TBS/B170249Lensatic%20Compass.pdf" },

  // ---------------- Pace & Distance ----------------
  { id:"ln-pace-calc", type:"mc", cat:"Pace & Distance",
    q:"Your pace count is 120 per 100 m. How many paces for 450 m?",
    choices:["375","450","540","570"],
    answer:2, explain:"4.5 × 120 = 540.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-dist", type:"mc", cat:"Pace & Distance",
    q:"Pace count 64 per 100 m. You've counted 256. Distance covered?",
    choices:["256 m","400 m","164 m","320 m"],
    answer:1, explain:"256 ÷ 64 = 4 hundreds = 400 m.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-factors", type:"flip", cat:"Pace & Distance",
    front:"Five conditions that change your pace",
    back:"Slopes, winds, surfaces, elements, visibility.",
    note:"Uphill shortens the pace and downhill lengthens it. A headwind shortens it and a tailwind lengthens it. Sand, mud and snow shorten it. Falling snow, rain and ice shorten it. Poor visibility shortens it.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },
  { id:"ln-pace-snow", type:"scenario", cat:"Pace & Distance",
    setup:"Deep snow, going uphill, in a light snowfall. Your normal count is 120 per 100 m.",
    q:"What happens to your count per 100 m?",
    choices:["Goes down","Stays the same","Goes up: pace is shorter, so more paces per 100 m","Can't be predicted"],
    answer:2, explain:"Upslope, snow surface and falling snow all shorten the pace. Expect well over 120.",
    source:TC, verified:"https://en.wikipedia.org/wiki/Land_navigation" },

  // ---------------- Terrain ----------------
  { id:"ln-t-hill", type:"flip", cat:"Terrain", front:"From the top, ground slopes down in every direction.", back:"HILL (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-saddle", type:"flip", cat:"Terrain", front:"Dip between two hills: up on two sides, down on two sides.", back:"SADDLE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-valley", type:"flip", cat:"Terrain", front:"Low ground between higher areas, often with a stream.", back:"VALLEY (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-ridge", type:"flip", cat:"Terrain", front:"A sloping line of high ground.", back:"RIDGE (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-depression", type:"flip", cat:"Terrain", front:"Low point or sinkhole, surrounded by higher ground.", back:"DEPRESSION (major)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-draw", type:"flip", cat:"Terrain", front:"A small valley, sometimes called a re-entrant.", back:"DRAW (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-spur", type:"flip", cat:"Terrain", front:"Short sloping high ground jutting out from a ridge.", back:"SPUR (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-cliff", type:"flip", cat:"Terrain", front:"Vertical or near-vertical drop.", back:"CLIFF (minor)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-cut", type:"flip", cat:"Terrain", front:"Man-made cut through high ground, e.g. for a road or rail line.", back:"CUT (supplementary)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-fill", type:"flip", cat:"Terrain", front:"Man-made fill raising a low area, e.g. a road bed.", back:"FILL (supplementary)", source:TC, verified:"https://www.land-navigation.com/terrain-features.html" },
  { id:"ln-t-counts", type:"mc", cat:"Terrain",
    q:"Terrain features: how many major, minor and supplementary?",
    choices:["5 / 3 / 2","4 / 4 / 2","3 / 5 / 2","5 / 2 / 3"],
    answer:0, explain:"Major: hill, saddle, valley, ridge, depression. Minor: draw, spur, cliff. Supplementary: cut, fill.",
    source:TC, verified:"https://brainscape.com/flashcards/land-nav-11330285/packs/20039434" },

  // ---------------- Map ----------------
  { id:"ln-colors", type:"flip", cat:"Map",
    front:"Military map colors",
    back:"Black: man-made features and labels. Blue: water. Green: vegetation. Brown: relief and contours. Red-brown: combined cultural and relief on red-light-readable maps. Red: populated areas, main roads, boundaries (older maps).",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/FMTBE/Student%20Materials/FMSO%20Manual/212.pdf" },
  { id:"ln-color-mc", type:"mc", cat:"Map",
    q:"On a military topo map, green shows…",
    choices:["Water","Vegetation","Man-made features","Relief"],
    answer:1, explain:"Green = vegetation (woods, orchards). Blue = water, brown = relief, black = man-made.",
    source:TC, verified:"https://www.trngcmd.marines.mil/Portals/207/Docs/FMTBE/Student%20Materials/FMSO%20Manual/212.pdf" },
  ],
};
