// RADIO — phonetic alphabet, number pronunciation, prowords, generic procedure only.
// BP 10-codes and jargon come from a public list (HonorFirst.com), added at the user's direction; flagged as sector-variable.
export default {
  meta: { id:"radio", name:"Radio", short:"RAD", color:"#8DB37A", order:11,
    blurb:"ICAO alphabet, number pronunciation, prowords, and BP 10-codes and jargon.",
    subModes:["browse"] },
  categories: {
    "Phonetic Alphabet": { why:"Plates, names and grid letters have to get through noise and bad signal on the first try." },
    "Numbers": { why:"Clipped numbers like TREE, FIFE and NIN-ER keep 3/5 and 9/5 apart on a weak signal." },
    "Prowords": { why:"Prowords say in one word what you need from the other station." },
    "Procedure": { why:"Clear, standard traffic keeps the channel open for whoever needs it next." },
    "BP 10-Codes": { why:"Know the codes you'll hear on BP traffic. On multi-agency incidents, use plain language (NIMS).", source:"HonorFirst.com, \"Border Patrol 10 Codes & Jargon\" (updated Mar. 2025)", flag:"Codes vary by sector and change over time. Confirm against your sector's current list." },
    "BP Jargon": { why:"The shorthand you'll hear in the field and in reports.", source:"HonorFirst.com, \"Border Patrol 10 Codes & Jargon\" (updated Mar. 2025)", flag:"Codes vary by sector and change over time. Confirm against your sector's current list." },
  },
  cards: [
  { id:"rd-l-a", type:"flip", cat:"Phonetic Alphabet", front:"A", back:"ALFA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-b", type:"flip", cat:"Phonetic Alphabet", front:"B", back:"BRAVO", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-c", type:"flip", cat:"Phonetic Alphabet", front:"C", back:"CHARLIE", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-d", type:"flip", cat:"Phonetic Alphabet", front:"D", back:"DELTA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-e", type:"flip", cat:"Phonetic Alphabet", front:"E", back:"ECHO", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-f", type:"flip", cat:"Phonetic Alphabet", front:"F", back:"FOXTROT", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-g", type:"flip", cat:"Phonetic Alphabet", front:"G", back:"GOLF", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-h", type:"flip", cat:"Phonetic Alphabet", front:"H", back:"HOTEL", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-i", type:"flip", cat:"Phonetic Alphabet", front:"I", back:"INDIA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-j", type:"flip", cat:"Phonetic Alphabet", front:"J", back:"JULIETT", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-k", type:"flip", cat:"Phonetic Alphabet", front:"K", back:"KILO", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-l", type:"flip", cat:"Phonetic Alphabet", front:"L", back:"LIMA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-m", type:"flip", cat:"Phonetic Alphabet", front:"M", back:"MIKE", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-n", type:"flip", cat:"Phonetic Alphabet", front:"N", back:"NOVEMBER", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-o", type:"flip", cat:"Phonetic Alphabet", front:"O", back:"OSCAR", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-p", type:"flip", cat:"Phonetic Alphabet", front:"P", back:"PAPA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-q", type:"flip", cat:"Phonetic Alphabet", front:"Q", back:"QUEBEC", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-r", type:"flip", cat:"Phonetic Alphabet", front:"R", back:"ROMEO", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-s", type:"flip", cat:"Phonetic Alphabet", front:"S", back:"SIERRA", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-t", type:"flip", cat:"Phonetic Alphabet", front:"T", back:"TANGO", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-u", type:"flip", cat:"Phonetic Alphabet", front:"U", back:"UNIFORM", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-v", type:"flip", cat:"Phonetic Alphabet", front:"V", back:"VICTOR", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-w", type:"flip", cat:"Phonetic Alphabet", front:"W", back:"WHISKEY", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-x", type:"flip", cat:"Phonetic Alphabet", front:"X", back:"X-RAY", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-y", type:"flip", cat:"Phonetic Alphabet", front:"Y", back:"YANKEE", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-z", type:"flip", cat:"Phonetic Alphabet", front:"Z", back:"ZULU", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-spelling", type:"mc", cat:"Phonetic Alphabet", q:"Official ICAO spelling for A and J?", choices:["Alpha / Juliet","Alfa / Juliett","Alfa / Juliet","Alpha / Juliett"], answer:1, explain:"Alfa with an F and Juliett with a double T, so non-English speakers pronounce them correctly.", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-l-plate", type:"order", cat:"Phonetic Alphabet", q:"Read plate \"K Z R\" over the air, in order.", steps:["KILO","ZULU","ROMEO"], explain:"Kilo, Zulu, Romeo. Say I SPELL first if it isn't clear you're spelling.", source:"ICAO spelling alphabet (ICAO Annex 10)", verified:"https://skybrary.aero/articles/icao-phonetic-alphabet" },
  { id:"rd-n-0", type:"flip", cat:"Numbers", front:"0", back:"ZE-RO", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-1", type:"flip", cat:"Numbers", front:"1", back:"WUN", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-2", type:"flip", cat:"Numbers", front:"2", back:"TOO", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-3", type:"flip", cat:"Numbers", front:"3", back:"TREE", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-4", type:"flip", cat:"Numbers", front:"4", back:"FOW-ER", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-5", type:"flip", cat:"Numbers", front:"5", back:"FIFE", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-6", type:"flip", cat:"Numbers", front:"6", back:"SIX", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-7", type:"flip", cat:"Numbers", front:"7", back:"SEV-EN", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-8", type:"flip", cat:"Numbers", front:"8", back:"AIT", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-9", type:"flip", cat:"Numbers", front:"9", back:"NIN-ER", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-n-mc", type:"mc", cat:"Numbers", q:"Which number is spoken \"FIFE\"?", choices:["4","5","9","3"], answer:1, explain:"FIFE = 5, FOW-ER = 4, NIN-ER = 9, TREE = 3.", source:"FAA Order JO 7110.10, Ch. 2 Sec. 3 (ICAO number pronunciation)", verified:"https://www.faa.gov/Air_traffic/Publications/atpubs/fs_html/chap2_section_3.html" },
  { id:"rd-p-roger", type:"flip", cat:"Prowords", front:"ROGER", back:"I have received your last transmission satisfactorily.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-wilco", type:"flip", cat:"Prowords", front:"WILCO", back:"I understand and will comply. Used on receipt of an order.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-say-again", type:"flip", cat:"Prowords", front:"SAY AGAIN", back:"I have not understood your message — repeat it. Often with ALL AFTER or ALL BEFORE.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-over", type:"flip", cat:"Prowords", front:"OVER", back:"End of my transmission; a response is necessary. Go ahead, transmit.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-out", type:"flip", cat:"Prowords", front:"OUT", back:"End of my transmission; no answer is required or expected.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-i-spell", type:"flip", cat:"Prowords", front:"I SPELL", back:"I will now spell the next word letter by letter, using the phonetic alphabet.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-correction", type:"flip", cat:"Prowords", front:"CORRECTION", back:"Disregard what I just sent; the correct version follows.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-break", type:"flip", cat:"Prowords", front:"BREAK", back:"Separates parts of a transmission.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-wait", type:"flip", cat:"Prowords", front:"WAIT", back:"Pause — wait for further transmission.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-p-overout", type:"mc", cat:"Prowords", q:"Why is \"OVER AND OUT\" incorrect?", choices:["It's too long","OVER asks for a reply and OUT says none is expected — they contradict","Only supervisors may say OUT","It's a 10-code"], answer:1, explain:"OVER and OUT are mutually exclusive. End with one or the other.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-sc-wilco", type:"scenario", cat:"Prowords", setup:"Dispatch tells you to hold your position and wait for backup. You understand and will do it.", q:"Best one-word reply?", choices:["ROGER WILCO","WILCO","OVER","COPY THAT, WILL DO"], answer:1, explain:"WILCO already means received, understood and will comply. ROGER WILCO is redundant.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-sc-sayagain", type:"scenario", cat:"Prowords", setup:"You copied the first half of a plate but lost the rest in static.", q:"What do you send?", choices:["REPEAT","SAY AGAIN ALL AFTER (last good word)","WHAT?","CORRECTION"], answer:1, explain:"SAY AGAIN with ALL AFTER or ALL BEFORE targets only the missed part.", source:"ACP 125, Communications Instructions — Radiotelephone Procedures (prowords)", verified:"https://en.wikipedia.org/wiki/Procedure_word" },
  { id:"rd-pr-plain", type:"mc", cat:"Procedure", q:"Under NIMS, what style of radio language is required when multiple agencies are working an incident?", choices:["Agency 10-codes","Plain language (common terminology)","Any code both units know","Phonetic alphabet only"], answer:1, explain:"NIMS/ICS requires common terminology: plain language that limits codes, abbreviations and jargon so mutual-aid responders understand each other.", source:"FEMA, NIMS Plain Language Guidance; IS-315 (ICS common terminology)", verified:"https://emilms.fema.gov/is_0315a/groups/143.html" },
  { id:"rd-pr-why", type:"flip", cat:"Procedure", front:"Why did NIMS move away from 10-codes?", back:"Codes vary between agencies. Plain language lets responders from different agencies and disciplines understand each other, a problem highlighted in the September 11, 2001 response.", source:"FEMA, NIMS Plain Language Guidance", verified:"https://www.alicetraining.com/wp-content/uploads/2016/03/FEMA-Plain-Language-Guide.pdf" },
  // ---------- BP 10-codes (public list; user-approved for this deck) ----------
  { id:"rd-10-1", type:"flip", cat:"BP 10-Codes", front:"10-1", back:"Receiving Poorly", opsecReviewed:true },
  { id:"rd-10-2", type:"flip", cat:"BP 10-Codes", front:"10-2", back:"Receiving Well", opsecReviewed:true },
  { id:"rd-10-3", type:"flip", cat:"BP 10-Codes", front:"10-3", back:"Disregard", opsecReviewed:true },
  { id:"rd-10-4", type:"flip", cat:"BP 10-Codes", front:"10-4", back:"Acknowledgement", opsecReviewed:true },
  { id:"rd-10-5", type:"flip", cat:"BP 10-Codes", front:"10-5", back:"Be on the Lookout", opsecReviewed:true },
  { id:"rd-10-6", type:"flip", cat:"BP 10-Codes", front:"10-6", back:"Temporarily Busy", opsecReviewed:true },
  { id:"rd-10-7", type:"flip", cat:"BP 10-Codes", front:"10-7", back:"Out of Service \u2014 Unavailable", opsecReviewed:true },
  { id:"rd-10-8", type:"flip", cat:"BP 10-Codes", front:"10-8", back:"In Service \u2014 Available", opsecReviewed:true },
  { id:"rd-10-9", type:"flip", cat:"BP 10-Codes", front:"10-9", back:"Repeat Last Transmission", opsecReviewed:true },
  { id:"rd-10-10", type:"flip", cat:"BP 10-Codes", front:"10-10", back:"All Available Agents Furnish Emergency Assistance", opsecReviewed:true },
  { id:"rd-10-11", type:"flip", cat:"BP 10-Codes", front:"10-11", back:"Investigate Subject", opsecReviewed:true },
  { id:"rd-10-12", type:"flip", cat:"BP 10-Codes", front:"10-12", back:"Visitors Present", opsecReviewed:true },
  { id:"rd-10-13", type:"flip", cat:"BP 10-Codes", front:"10-13", back:"En Route", opsecReviewed:true },
  { id:"rd-10-14", type:"flip", cat:"BP 10-Codes", front:"10-14", back:"Establish Traffic at Checkpoint", opsecReviewed:true },
  { id:"rd-10-15", type:"flip", cat:"BP 10-Codes", front:"10-15", back:"Aliens in Custody", opsecReviewed:true },
  { id:"rd-10-16", type:"flip", cat:"BP 10-Codes", front:"10-16", back:"Pick Up Aliens in Custody", opsecReviewed:true },
  { id:"rd-10-17", type:"flip", cat:"BP 10-Codes", front:"10-17", back:"Inspection Party", opsecReviewed:true },
  { id:"rd-10-18", type:"flip", cat:"BP 10-Codes", front:"10-18", back:"Any Traffic \u2014 Security Check", opsecReviewed:true },
  { id:"rd-10-19", type:"flip", cat:"BP 10-Codes", front:"10-19", back:"No Traffic, Security Check Reply", opsecReviewed:true },
  { id:"rd-10-20", type:"flip", cat:"BP 10-Codes", front:"10-20", back:"Location", opsecReviewed:true },
  { id:"rd-10-21", type:"flip", cat:"BP 10-Codes", front:"10-21", back:"Telephone Call", opsecReviewed:true },
  { id:"rd-10-22", type:"flip", cat:"BP 10-Codes", front:"10-22", back:"Advise Officers to Report", opsecReviewed:true },
  { id:"rd-10-23", type:"flip", cat:"BP 10-Codes", front:"10-23", back:"Restrict Normal Communications", opsecReviewed:true },
  { id:"rd-10-24", type:"flip", cat:"BP 10-Codes", front:"10-24", back:"Normal Communications", opsecReviewed:true },
  { id:"rd-10-25", type:"flip", cat:"BP 10-Codes", front:"10-25", back:"Immediate Assistance Required", opsecReviewed:true },
  { id:"rd-10-26", type:"flip", cat:"BP 10-Codes", front:"10-26", back:"Single Agent Vehicle Stop", opsecReviewed:true },
  { id:"rd-10-27", type:"flip", cat:"BP 10-Codes", front:"10-27", back:"Information from Civilian", opsecReviewed:true },
  { id:"rd-10-28", type:"flip", cat:"BP 10-Codes", front:"10-28", back:"Vehicle Registration Check", opsecReviewed:true },
  { id:"rd-10-29", type:"flip", cat:"BP 10-Codes", front:"10-29", back:"Stolen/Wanted Vehicle Check", opsecReviewed:true },
  { id:"rd-10-30", type:"flip", cat:"BP 10-Codes", front:"10-30", back:"Person in Custody Speaks English", opsecReviewed:true },
  { id:"rd-10-31", type:"flip", cat:"BP 10-Codes", front:"10-31", back:"Engaging in Pursuit", opsecReviewed:true },
  { id:"rd-10-32", type:"flip", cat:"BP 10-Codes", front:"10-32", back:"More Than One Agent Vehicle Stop", opsecReviewed:true },
  { id:"rd-10-33", type:"flip", cat:"BP 10-Codes", front:"10-33", back:"Dangerous Subject", opsecReviewed:true },
  { id:"rd-10-34", type:"flip", cat:"BP 10-Codes", front:"10-34", back:"I-213/Immigration Check", opsecReviewed:true },
  { id:"rd-10-35", type:"flip", cat:"BP 10-Codes", front:"10-35", back:"False Claim Check", opsecReviewed:true },
  { id:"rd-10-36", type:"flip", cat:"BP 10-Codes", front:"10-36", back:"Smuggler Check", opsecReviewed:true },
  { id:"rd-10-37", type:"flip", cat:"BP 10-Codes", front:"10-37", back:"Observing Traffic at...", opsecReviewed:true },
  { id:"rd-10-38", type:"flip", cat:"BP 10-Codes", front:"10-38", back:"Meet at...", opsecReviewed:true },
  { id:"rd-10-39", type:"flip", cat:"BP 10-Codes", front:"10-39", back:"Record Check is Positive", opsecReviewed:true },
  { id:"rd-10-40", type:"flip", cat:"BP 10-Codes", front:"10-40", back:"No Record Found on Subject", opsecReviewed:true },
  { id:"rd-10-41", type:"flip", cat:"BP 10-Codes", front:"10-41", back:"Unit on Duty \u2014 Able to Talk", opsecReviewed:true },
  { id:"rd-10-42", type:"flip", cat:"BP 10-Codes", front:"10-42", back:"Unit Off Duty \u2014 Not Able to Talk", opsecReviewed:true },
  { id:"rd-10-43", type:"flip", cat:"BP 10-Codes", front:"10-43", back:"Switch to Channel", opsecReviewed:true },
  { id:"rd-10-44", type:"flip", cat:"BP 10-Codes", front:"10-44", back:"Meet at...", opsecReviewed:true },
  { id:"rd-10-45", type:"flip", cat:"BP 10-Codes", front:"10-45", back:"Apprehended Illegal Aliens", opsecReviewed:true },
  { id:"rd-10-46", type:"flip", cat:"BP 10-Codes", front:"10-46", back:"Apprehended Narcotics", opsecReviewed:true },
  { id:"rd-10-48", type:"flip", cat:"BP 10-Codes", front:"10-48", back:"BP Involved in an Accident", opsecReviewed:true },
  { id:"rd-10-49", type:"flip", cat:"BP 10-Codes", front:"10-49", back:"Out of Service at Residence", opsecReviewed:true },
  { id:"rd-10-50", type:"flip", cat:"BP 10-Codes", front:"10-50", back:"Immigration Check", opsecReviewed:true },
  { id:"rd-10-51", type:"flip", cat:"BP 10-Codes", front:"10-51", back:"Wants/Warrants on a Person", opsecReviewed:true },
  { id:"rd-10-52", type:"flip", cat:"BP 10-Codes", front:"10-52", back:"Check Criminal History", opsecReviewed:true },
  { id:"rd-10-53", type:"flip", cat:"BP 10-Codes", front:"10-53", back:"Firearms Check", opsecReviewed:true },
  { id:"rd-10-54", type:"flip", cat:"BP 10-Codes", front:"10-54", back:"Vital Statistics Check", opsecReviewed:true },
  { id:"rd-10-55", type:"flip", cat:"BP 10-Codes", front:"10-55", back:"Controlled Load", opsecReviewed:true },
  { id:"rd-10-57", type:"flip", cat:"BP 10-Codes", front:"10-57", back:"Driver's License Check", opsecReviewed:true },
  { id:"rd-10-58", type:"flip", cat:"BP 10-Codes", front:"10-58", back:"Cross Index Check", opsecReviewed:true },
  { id:"rd-10-59", type:"flip", cat:"BP 10-Codes", front:"10-59", back:"Maintenance (Sensor or Other)", opsecReviewed:true },
  { id:"rd-10-60", type:"flip", cat:"BP 10-Codes", front:"10-60", back:"Sensor Hit", opsecReviewed:true },
  { id:"rd-10-72", type:"flip", cat:"BP 10-Codes", front:"10-72", back:"TECS Lane Check", opsecReviewed:true },
  { id:"rd-10-79", type:"flip", cat:"BP 10-Codes", front:"10-79", back:"No Unit Available", opsecReviewed:true },
  { id:"rd-10-81", type:"flip", cat:"BP 10-Codes", front:"10-81", back:"Assigned Unit", opsecReviewed:true },
  { id:"rd-10-82", type:"flip", cat:"BP 10-Codes", front:"10-82", back:"Assigned Unit Arrived Time", opsecReviewed:true },
  { id:"rd-10-83", type:"flip", cat:"BP 10-Codes", front:"10-83", back:"Completes Unit Assignment", opsecReviewed:true },
  { id:"rd-10-84", type:"flip", cat:"BP 10-Codes", front:"10-84", back:"Remove Unit from Assignment", opsecReviewed:true },
  { id:"rd-10-85", type:"flip", cat:"BP 10-Codes", front:"10-85", back:"Create Incident Ticket", opsecReviewed:true },
  { id:"rd-10-86", type:"flip", cat:"BP 10-Codes", front:"10-86", back:"Vehicle Change", opsecReviewed:true },
  { id:"rd-10-87", type:"flip", cat:"BP 10-Codes", front:"10-87", back:"Change Work Area", opsecReviewed:true },
  { id:"rd-10-88", type:"flip", cat:"BP 10-Codes", front:"10-88", back:"Operated in Coded Mode", opsecReviewed:true },
  { id:"rd-10-89", type:"flip", cat:"BP 10-Codes", front:"10-89", back:"Operated in Clear Mode", opsecReviewed:true },
  { id:"rd-10-91", type:"flip", cat:"BP 10-Codes", front:"10-91", back:"Out of Radio Contact \u2014 Still in Service", opsecReviewed:true },
  { id:"rd-10-92", type:"flip", cat:"BP 10-Codes", front:"10-92", back:"Back in Radio Contact", opsecReviewed:true },
  { id:"rd-10-95", type:"flip", cat:"BP 10-Codes", front:"10-95", back:"Log Information", opsecReviewed:true },
  { id:"rd-10-96", type:"flip", cat:"BP 10-Codes", front:"10-96", back:"Escorting Female", opsecReviewed:true },
  { id:"rd-10-97", type:"flip", cat:"BP 10-Codes", front:"10-97", back:"Begin Transport of Juvenile/Female", opsecReviewed:true },
  { id:"rd-10-98", type:"flip", cat:"BP 10-Codes", front:"10-98", back:"End Transport of Juvenile/Female", opsecReviewed:true },
  { id:"rd-10-99", type:"flip", cat:"BP 10-Codes", front:"10-99", back:"Officer Down \u2014 All Agents Respond", opsecReviewed:true },
  { id:"rd-10-100", type:"flip", cat:"BP 10-Codes", front:"10-100", back:"Place BP Emergency Plan Into Effect", opsecReviewed:true },
  { id:"rd-10-101", type:"flip", cat:"BP 10-Codes", front:"10-101", back:"Bomb Threat", opsecReviewed:true },
  { id:"rd-10-mc1", type:"mc", cat:"BP 10-Codes", q:"10-20 means…", choices:["Location","En route","Repeat last transmission","Out of service"], answer:0, explain:"10-20 = location. 10-13 = en route, 10-9 = repeat, 10-7 = out of service.", opsecReviewed:true },
  { id:"rd-10-mc2", type:"mc", cat:"BP 10-Codes", q:"Which code is 'Immediate Assistance Required'?", choices:["10-10","10-25","10-33","10-99"], answer:1, explain:"10-25 = immediate assistance. 10-10 = all available agents furnish emergency assistance. 10-33 = dangerous subject. 10-99 = officer down, all agents respond.", opsecReviewed:true },
  { id:"rd-10-mc3", type:"mc", cat:"BP 10-Codes", q:"10-15 means…", choices:["Aliens in custody","Pick up aliens in custody","Apprehended narcotics","Person in custody speaks English"], answer:0, explain:"10-15 = in custody. 10-16 = pick up those in custody. 10-46 = narcotics. 10-30 = speaks English.", opsecReviewed:true },
  { id:"rd-10-mc4", type:"mc", cat:"BP 10-Codes", q:"Single-agent vehicle stop vs. more than one agent:", choices:["10-26 / 10-32","10-32 / 10-26","10-28 / 10-29","10-11 / 10-33"], answer:0, explain:"10-26 = single-agent stop. 10-32 = more than one agent. 10-28 = registration check, 10-29 = stolen/wanted vehicle check.", opsecReviewed:true },
  { id:"rd-10-mc5", type:"mc", cat:"BP 10-Codes", q:"A record check comes back positive. Which code?", choices:["10-39","10-40","10-51","10-52"], answer:0, explain:"10-39 = record check positive. 10-40 = no record found. 10-51 = wants/warrants check, 10-52 = criminal history check.", opsecReviewed:true },
  { id:"rd-10-mc6", type:"mc", cat:"BP 10-Codes", q:"10-99 means…", choices:["Bomb threat","Officer down — all agents respond","Place BP emergency plan into effect","BP involved in an accident"], answer:1, explain:"10-99 = officer down. 10-101 = bomb threat. 10-100 = emergency plan. 10-48 = BP accident.", opsecReviewed:true },
  // ---------- BP jargon (same public source) ----------
  { id:"rd-j-1", type:"flip", cat:"BP Jargon", front:"\u201c46\u201d", back:"Drugs, usually marijuana", opsecReviewed:true },
  { id:"rd-j-2", type:"flip", cat:"BP Jargon", front:"\u201c45\u201d", back:"Illegal aliens", opsecReviewed:true },
  { id:"rd-j-3", type:"flip", cat:"BP Jargon", front:"IAs", back:"Illegal aliens", opsecReviewed:true },
  { id:"rd-j-4", type:"flip", cat:"BP Jargon", front:"UDAs", back:"Illegal aliens", opsecReviewed:true },
  { id:"rd-j-5", type:"flip", cat:"BP Jargon", front:"UACs", back:"Unaccompanied children", opsecReviewed:true },
  { id:"rd-j-6", type:"flip", cat:"BP Jargon", front:"\u201cBodies\u201d", back:"Illegal aliens", note:"If deceased, \u201c10-7\u201d is used.", opsecReviewed:true },
  { id:"rd-j-7", type:"flip", cat:"BP Jargon", front:"\u201cPackers\u201d / \u201cMules\u201d", back:"Drug smugglers", opsecReviewed:true },
  { id:"rd-j-8", type:"flip", cat:"BP Jargon", front:"\u201cBailout\u201d", back:"People who abscond from a traffic stop", opsecReviewed:true },
  { id:"rd-j-9", type:"flip", cat:"BP Jargon", front:"\u201cGot-aways\u201d", back:"Exactly what it sounds like: people who evaded apprehension", opsecReviewed:true },
  { id:"rd-j-10", type:"flip", cat:"BP Jargon", front:"TBS", back:"Turned back south", opsecReviewed:true },
  { id:"rd-j-11", type:"flip", cat:"BP Jargon", front:"POE", back:"Port of entry", opsecReviewed:true },
  { id:"rd-j-12", type:"flip", cat:"BP Jargon", front:"\u201cThe Line\u201d", back:"The international boundary", note:"The source defines it as the U.S./Mexico boundary.", opsecReviewed:true },
  { id:"rd-j-13", type:"flip", cat:"BP Jargon", front:"\u201cOmaha\u201d / \u201cLiberty\u201d / \u201cFalcon\u201d", back:"Helicopters and fixed-wing aircraft", opsecReviewed:true },
  { id:"rd-j-14", type:"flip", cat:"BP Jargon", front:"\u201cPushing\u201d", back:"Tracking and literally \u201cpushing\u201d behind a group", opsecReviewed:true },
  { id:"rd-j-15", type:"flip", cat:"BP Jargon", front:"USC", back:"U.S. citizen", opsecReviewed:true },
  { id:"rd-j-16", type:"flip", cat:"BP Jargon", front:"BOLO", back:"Be on the lookout", opsecReviewed:true },
  { id:"rd-j-17", type:"flip", cat:"BP Jargon", front:"FTY", back:"Failure to yield", opsecReviewed:true },
  ],
};
