// SPANISH — flashcard deck. Migrated verbatim from Patrol Español v1.
// IDs: es-v* = vocabulary, es-p* = field phrases (v1 ids prefixed with "es-"; never reuse).
// Card-level "why"/"source" override the category defaults below.
export default {
  meta: { id:"spanish", name:"Spanish", short:"ES", color:"#C9A227", lang:"es-MX", order:1,
    blurb:"Field phrases and vocabulary, spaced repetition.",
    source:"Patrol Español v1 · adapted from Friar & Kelly, Practical Spanish Grammar for Border Patrol Officers (INS, 1943), modernized",
    subModes:["browse","grammar","verbs"] },
  categories: {
    // vocabulary
    "People":                  { group:"Vocabulary", why:"Sorting out who is who — driver, guide, family — drives every follow-up question." },
    "Terrain & Places":        { group:"Vocabulary", why:"Lets you follow where someone crossed, walked, and was headed." },
    "Documents":               { group:"Vocabulary", why:"The words at the core of every status interview." },
    "Objects & Gear":          { group:"Vocabulary", why:"Officer safety and evidence: name what you see and what they carry." },
    "Body & Medical":          { group:"Vocabulary", why:"You can't render aid until you understand the complaint." },
    "Weather & Time":          { group:"Vocabulary", why:"Cold exposure and timeline questions: when, how long, how cold." },
    "Action Verbs":            { group:"Vocabulary", why:"Verbs carry the story — crossed, walked, paid, hid." },
    "Direction & Description": { group:"Vocabulary", why:"Positions and directions, for giving commands and locating others." },
    // phrases
    "Commands & Control":      { group:"Phrases", why:"Clear commands in the subject's language cut confusion and the need for force." },
    "Identity & Citizenship":  { group:"Phrases", why:"Alienage and status questions are the legal core of the encounter." },
    "Crossing & Travel":       { group:"Phrases", why:"Pins down time, place and manner of entry — and whether others are still out there." },
    "Safety & Medical":        { group:"Phrases", why:"Catch injuries, cold exposure and weapons early." },
    "Processing & Transport":  { group:"Phrases", why:"Explaining each step gets compliance and protects the subject's rights." },
    "Everyday & Idioms":       { group:"Phrases", why:"Rapport and comprehension — the glue between the scripted questions." },
  },
  cards: [
  // ---------- vocabulary ----------
  {id:"es-v1", type:"flip", cat:"People", front:"el hombre", back:"the man"},
  {id:"es-v2", type:"flip", cat:"People", front:"la mujer", back:"the woman"},
  {id:"es-v3", type:"flip", cat:"People", front:"el niño / la niña", back:"the boy / the girl (child)"},
  {id:"es-v4", type:"flip", cat:"People", front:"el muchacho", back:"the boy, young man"},
  {id:"es-v5", type:"flip", cat:"People", front:"la familia", back:"the family"},
  {id:"es-v6", type:"flip", cat:"People", front:"el esposo / la esposa", back:"the husband / the wife"},
  {id:"es-v7", type:"flip", cat:"People", front:"el hijo / la hija", back:"the son / the daughter"},
  {id:"es-v8", type:"flip", cat:"People", front:"la madre / el padre", back:"the mother / the father"},
  {id:"es-v9", type:"flip", cat:"People", front:"el hermano / la hermana", back:"the brother / the sister"},
  {id:"es-v10", type:"flip", cat:"People", front:"la gente", back:"the people (singular in Spanish)"},
  {id:"es-v11", type:"flip", cat:"People", front:"el ciudadano", back:"the citizen"},
  {id:"es-v12", type:"flip", cat:"People", front:"el extranjero", back:"the foreigner, alien"},
  {id:"es-v13", type:"flip", cat:"People", front:"el guía", back:"the guide (smuggler: 'coyote' / 'pollero')"},
  {id:"es-v14", type:"flip", cat:"People", front:"el testigo", back:"the witness"},
  {id:"es-v15", type:"flip", cat:"People", front:"el conductor", back:"the driver"},
  {id:"es-v16", type:"flip", cat:"People", front:"el pasajero", back:"the passenger"},
  {id:"es-v17", type:"flip", cat:"People", front:"el agente", back:"the agent, officer"},
  {id:"es-v20", type:"flip", cat:"Terrain & Places", front:"la frontera", back:"the border"},
  {id:"es-v21", type:"flip", cat:"Terrain & Places", front:"la línea", back:"the line (slang: the border)"},
  {id:"es-v22", type:"flip", cat:"Terrain & Places", front:"el río", back:"the river"},
  {id:"es-v23", type:"flip", cat:"Terrain & Places", front:"la montaña", back:"the mountain"},
  {id:"es-v24", type:"flip", cat:"Terrain & Places", front:"el bosque", back:"the woods, forest"},
  {id:"es-v25", type:"flip", cat:"Terrain & Places", front:"el campo", back:"the field, countryside"},
  {id:"es-v26", type:"flip", cat:"Terrain & Places", front:"el camino", back:"the road, way"},
  {id:"es-v27", type:"flip", cat:"Terrain & Places", front:"la carretera", back:"the highway"},
  {id:"es-v28", type:"flip", cat:"Terrain & Places", front:"el puente", back:"the bridge"},
  {id:"es-v29", type:"flip", cat:"Terrain & Places", front:"el lago", back:"the lake"},
  {id:"es-v30", type:"flip", cat:"Terrain & Places", front:"la loma", back:"the hill"},
  {id:"es-v31", type:"flip", cat:"Terrain & Places", front:"el sendero", back:"the trail, path"},
  {id:"es-v32", type:"flip", cat:"Terrain & Places", front:"la huella", back:"the footprint, track (also: fingerprint)"},
  {id:"es-v33", type:"flip", cat:"Terrain & Places", front:"el rancho / la granja", back:"the ranch / the farm"},
  {id:"es-v34", type:"flip", cat:"Terrain & Places", front:"el pueblo", back:"the town, village"},
  {id:"es-v35", type:"flip", cat:"Terrain & Places", front:"la estación", back:"the station"},
  {id:"es-v36", type:"flip", cat:"Terrain & Places", front:"la garita", back:"the port of entry, checkpoint booth"},
  {id:"es-v37", type:"flip", cat:"Terrain & Places", front:"el norte / el sur", back:"the north / the south"},
  {id:"es-v38", type:"flip", cat:"Terrain & Places", front:"el este / el oeste", back:"the east / the west"},
  {id:"es-v39", type:"flip", cat:"Terrain & Places", front:"la cerca", back:"the fence"},
  {id:"es-v40", type:"flip", cat:"Documents", front:"el pasaporte", back:"the passport"},
  {id:"es-v41", type:"flip", cat:"Documents", front:"la visa", back:"the visa"},
  {id:"es-v42", type:"flip", cat:"Documents", front:"los papeles", back:"the papers (documents)"},
  {id:"es-v43", type:"flip", cat:"Documents", front:"la tarjeta", back:"the card"},
  {id:"es-v44", type:"flip", cat:"Documents", front:"la mica", back:"slang: green card / resident card"},
  {id:"es-v45", type:"flip", cat:"Documents", front:"la licencia", back:"the license"},
  {id:"es-v46", type:"flip", cat:"Documents", front:"el permiso", back:"the permit, permission"},
  {id:"es-v47", type:"flip", cat:"Documents", front:"la cita", back:"the appointment"},
  {id:"es-v48", type:"flip", cat:"Documents", front:"la firma", back:"the signature"},
  {id:"es-v49", type:"flip", cat:"Documents", front:"el nombre", back:"the name (first name)"},
  {id:"es-v50", type:"flip", cat:"Documents", front:"el apellido", back:"the last name, surname"},
  {id:"es-v51", type:"flip", cat:"Documents", front:"la fecha de nacimiento", back:"the date of birth"},
  {id:"es-v52", type:"flip", cat:"Documents", front:"la nacionalidad", back:"the nationality"},
  {id:"es-v60", type:"flip", cat:"Objects & Gear", front:"la mochila", back:"the backpack"},
  {id:"es-v61", type:"flip", cat:"Objects & Gear", front:"el teléfono (celular)", back:"the (cell) phone"},
  {id:"es-v62", type:"flip", cat:"Objects & Gear", front:"el dinero", back:"the money"},
  {id:"es-v63", type:"flip", cat:"Objects & Gear", front:"el arma", back:"the weapon (fem. noun, uses 'el')"},
  {id:"es-v64", type:"flip", cat:"Objects & Gear", front:"la pistola", back:"the pistol"},
  {id:"es-v65", type:"flip", cat:"Objects & Gear", front:"el cuchillo", back:"the knife"},
  {id:"es-v66", type:"flip", cat:"Objects & Gear", front:"las drogas", back:"the drugs"},
  {id:"es-v67", type:"flip", cat:"Objects & Gear", front:"la bolsa", back:"the bag, purse"},
  {id:"es-v68", type:"flip", cat:"Objects & Gear", front:"el bolsillo", back:"the pocket"},
  {id:"es-v69", type:"flip", cat:"Objects & Gear", front:"la ropa", back:"the clothes"},
  {id:"es-v70", type:"flip", cat:"Objects & Gear", front:"los zapatos / las botas", back:"the shoes / the boots"},
  {id:"es-v71", type:"flip", cat:"Objects & Gear", front:"la chamarra", back:"the jacket (Mex.; also 'la chaqueta')"},
  {id:"es-v72", type:"flip", cat:"Objects & Gear", front:"la gorra", back:"the cap"},
  {id:"es-v73", type:"flip", cat:"Objects & Gear", front:"la linterna", back:"the flashlight"},
  {id:"es-v74", type:"flip", cat:"Objects & Gear", front:"las esposas", back:"the handcuffs (also: wives!)"},
  {id:"es-v75", type:"flip", cat:"Objects & Gear", front:"la cuerda", back:"the rope, cord"},
  {id:"es-v76", type:"flip", cat:"Objects & Gear", front:"la llave", back:"the key"},
  {id:"es-v77", type:"flip", cat:"Objects & Gear", front:"el carro", back:"the car"},
  {id:"es-v78", type:"flip", cat:"Objects & Gear", front:"la camioneta", back:"the van, pickup (Mex. slang: 'la troca')"},
  {id:"es-v79", type:"flip", cat:"Objects & Gear", front:"el autobús", back:"the bus"},
  {id:"es-v80", type:"flip", cat:"Body & Medical", front:"la cabeza", back:"the head"},
  {id:"es-v81", type:"flip", cat:"Body & Medical", front:"la mano", back:"the hand (fem. despite -o)"},
  {id:"es-v82", type:"flip", cat:"Body & Medical", front:"el pie", back:"the foot"},
  {id:"es-v83", type:"flip", cat:"Body & Medical", front:"la pierna", back:"the leg"},
  {id:"es-v84", type:"flip", cat:"Body & Medical", front:"el brazo", back:"the arm"},
  {id:"es-v85", type:"flip", cat:"Body & Medical", front:"la espalda", back:"the back"},
  {id:"es-v86", type:"flip", cat:"Body & Medical", front:"la sangre", back:"the blood"},
  {id:"es-v87", type:"flip", cat:"Body & Medical", front:"herido / herida", back:"injured, wounded"},
  {id:"es-v88", type:"flip", cat:"Body & Medical", front:"enfermo / enferma", back:"sick, ill"},
  {id:"es-v89", type:"flip", cat:"Body & Medical", front:"el dolor", back:"the pain, ache"},
  {id:"es-v90", type:"flip", cat:"Body & Medical", front:"la ampolla", back:"the blister"},
  {id:"es-v91", type:"flip", cat:"Body & Medical", front:"deshidratado", back:"dehydrated"},
  {id:"es-v92", type:"flip", cat:"Body & Medical", front:"el médico", back:"the doctor"},
  {id:"es-v93", type:"flip", cat:"Body & Medical", front:"la ambulancia", back:"the ambulance"},
  {id:"es-v94", type:"flip", cat:"Body & Medical", front:"la medicina", back:"the medicine"},
  {id:"es-v95", type:"flip", cat:"Body & Medical", front:"embarazada", back:"pregnant"},
  {id:"es-v96", type:"flip", cat:"Body & Medical", front:"el agua", back:"the water (fem. noun, uses 'el')"},
  {id:"es-v100", type:"flip", cat:"Weather & Time", front:"la nieve", back:"the snow"},
  {id:"es-v101", type:"flip", cat:"Weather & Time", front:"el hielo", back:"the ice"},
  {id:"es-v102", type:"flip", cat:"Weather & Time", front:"el frío", back:"the cold"},
  {id:"es-v103", type:"flip", cat:"Weather & Time", front:"el calor", back:"the heat"},
  {id:"es-v104", type:"flip", cat:"Weather & Time", front:"la lluvia", back:"the rain"},
  {id:"es-v105", type:"flip", cat:"Weather & Time", front:"la tormenta", back:"the storm"},
  {id:"es-v106", type:"flip", cat:"Weather & Time", front:"la neblina", back:"the fog"},
  {id:"es-v107", type:"flip", cat:"Weather & Time", front:"la noche", back:"the night"},
  {id:"es-v108", type:"flip", cat:"Weather & Time", front:"el amanecer", back:"the dawn"},
  {id:"es-v109", type:"flip", cat:"Weather & Time", front:"oscuro", back:"dark"},
  {id:"es-v110", type:"flip", cat:"Weather & Time", front:"mojado", back:"wet"},
  {id:"es-v111", type:"flip", cat:"Weather & Time", front:"hoy / ayer / mañana", back:"today / yesterday / tomorrow"},
  {id:"es-v112", type:"flip", cat:"Weather & Time", front:"ahora / ahorita", back:"now / right now (Mex.)"},
  {id:"es-v113", type:"flip", cat:"Weather & Time", front:"la semana / el mes / el año", back:"the week / the month / the year"},
  {id:"es-v120", type:"flip", cat:"Action Verbs", front:"cruzar", back:"to cross"},
  {id:"es-v121", type:"flip", cat:"Action Verbs", front:"correr", back:"to run"},
  {id:"es-v122", type:"flip", cat:"Action Verbs", front:"caminar", back:"to walk"},
  {id:"es-v123", type:"flip", cat:"Action Verbs", front:"parar(se)", back:"to stop (pararse: to stand up / halt)"},
  {id:"es-v124", type:"flip", cat:"Action Verbs", front:"esperar", back:"to wait; to hope"},
  {id:"es-v125", type:"flip", cat:"Action Verbs", front:"hablar", back:"to speak, talk"},
  {id:"es-v126", type:"flip", cat:"Action Verbs", front:"entender", back:"to understand"},
  {id:"es-v127", type:"flip", cat:"Action Verbs", front:"ayudar", back:"to help"},
  {id:"es-v128", type:"flip", cat:"Action Verbs", front:"buscar", back:"to look for, search"},
  {id:"es-v129", type:"flip", cat:"Action Verbs", front:"encontrar", back:"to find"},
  {id:"es-v130", type:"flip", cat:"Action Verbs", front:"llevar", back:"to carry, take (away)"},
  {id:"es-v131", type:"flip", cat:"Action Verbs", front:"traer", back:"to bring"},
  {id:"es-v132", type:"flip", cat:"Action Verbs", front:"mostrar", back:"to show"},
  {id:"es-v133", type:"flip", cat:"Action Verbs", front:"firmar", back:"to sign"},
  {id:"es-v134", type:"flip", cat:"Action Verbs", front:"mentir", back:"to lie (tell a lie)"},
  {id:"es-v135", type:"flip", cat:"Action Verbs", front:"esconder(se)", back:"to hide (esconderse: hide oneself)"},
  {id:"es-v136", type:"flip", cat:"Action Verbs", front:"escapar", back:"to escape"},
  {id:"es-v137", type:"flip", cat:"Action Verbs", front:"pagar", back:"to pay"},
  {id:"es-v138", type:"flip", cat:"Action Verbs", front:"trabajar", back:"to work"},
  {id:"es-v139", type:"flip", cat:"Action Verbs", front:"regresar", back:"to return, go back"},
  {id:"es-v140", type:"flip", cat:"Action Verbs", front:"entrar / salir", back:"to enter / to leave, exit"},
  {id:"es-v141", type:"flip", cat:"Action Verbs", front:"subir / bajar", back:"to go up, get in / to go down, get out"},
  {id:"es-v142", type:"flip", cat:"Action Verbs", front:"sentarse / levantarse", back:"to sit down / to stand up, get up"},
  {id:"es-v143", type:"flip", cat:"Action Verbs", front:"dormir", back:"to sleep"},
  {id:"es-v144", type:"flip", cat:"Action Verbs", front:"comer / beber", back:"to eat / to drink"},
  {id:"es-v145", type:"flip", cat:"Action Verbs", front:"manejar", back:"to drive (Mex.; also 'conducir')"},
  {id:"es-v150", type:"flip", cat:"Direction & Description", front:"rápido / despacio", back:"fast / slowly"},
  {id:"es-v151", type:"flip", cat:"Direction & Description", front:"cerca / lejos", back:"near / far"},
  {id:"es-v152", type:"flip", cat:"Direction & Description", front:"aquí / acá", back:"here (acá: over here, motion)"},
  {id:"es-v153", type:"flip", cat:"Direction & Description", front:"allí / allá", back:"there / over there (farther)"},
  {id:"es-v154", type:"flip", cat:"Direction & Description", front:"arriba / abajo", back:"up, above / down, below"},
  {id:"es-v155", type:"flip", cat:"Direction & Description", front:"adelante / atrás", back:"forward, ahead / back, behind"},
  {id:"es-v156", type:"flip", cat:"Direction & Description", front:"adentro / afuera", back:"inside / outside"},
  {id:"es-v157", type:"flip", cat:"Direction & Description", front:"a la derecha / a la izquierda", back:"to the right / to the left"},
  {id:"es-v158", type:"flip", cat:"Direction & Description", front:"juntos / solo", back:"together / alone"},
  {id:"es-v159", type:"flip", cat:"Direction & Description", front:"peligroso / seguro", back:"dangerous / safe"},
  {id:"es-v160", type:"flip", cat:"Direction & Description", front:"la verdad / la mentira", back:"the truth / the lie"},
  {id:"es-v161", type:"flip", cat:"Direction & Description", front:"todo / nada", back:"everything / nothing"},
  {id:"es-v162", type:"flip", cat:"Direction & Description", front:"alguien / nadie", back:"someone / no one"},
  {id:"es-v163", type:"flip", cat:"Direction & Description", front:"más / menos", back:"more / less"},
  {id:"es-v164", type:"flip", cat:"Direction & Description", front:"otro / otra", back:"another, other"},
  // ---------- field phrases ----------
  {id:"es-p1", type:"flip", cat:"Commands & Control", front:"¡Alto! Patrulla Fronteriza.", back:"Stop! Border Patrol.", note:"'Alto' is the universal halt command — sharper than 'pare'."},
  {id:"es-p2", type:"flip", cat:"Commands & Control", front:"No se mueva.", back:"Don't move.", note:"Negative command: no + subjunctive form. Pronoun 'se' goes BEFORE the verb in negatives."},
  {id:"es-p3", type:"flip", cat:"Commands & Control", front:"No corra.", back:"Don't run."},
  {id:"es-p4", type:"flip", cat:"Commands & Control", front:"Párese allí.", back:"Stand over there. / Stop there.", note:"From pararse. Pronoun attaches to the END of affirmative commands."},
  {id:"es-p5", type:"flip", cat:"Commands & Control", front:"Venga acá.", back:"Come here.", note:"Irregular command of venir. 'Acá' implies motion toward you."},
  {id:"es-p6", type:"flip", cat:"Commands & Control", front:"Muéstreme las manos.", back:"Show me your hands.", note:"Spanish uses 'las manos' (the hands), not 'sus manos' — body parts take the article."},
  {id:"es-p7", type:"flip", cat:"Commands & Control", front:"Ponga las manos en la cabeza.", back:"Put your hands on your head."},
  {id:"es-p8", type:"flip", cat:"Commands & Control", front:"Levante las manos.", back:"Raise your hands."},
  {id:"es-p9", type:"flip", cat:"Commands & Control", front:"Siéntese.", back:"Sit down."},
  {id:"es-p10", type:"flip", cat:"Commands & Control", front:"Levántese.", back:"Stand up. / Get up."},
  {id:"es-p11", type:"flip", cat:"Commands & Control", front:"Póngase de rodillas.", back:"Get on your knees."},
  {id:"es-p12", type:"flip", cat:"Commands & Control", front:"Cálmese.", back:"Calm down."},
  {id:"es-p13", type:"flip", cat:"Commands & Control", front:"Silencio, por favor.", back:"Quiet, please."},
  {id:"es-p14", type:"flip", cat:"Commands & Control", front:"Camine despacio hacia mí.", back:"Walk slowly toward me."},
  {id:"es-p15", type:"flip", cat:"Commands & Control", front:"Suelte la mochila.", back:"Drop the backpack.", note:"From soltar (o→ue): suelte."},
  {id:"es-p16", type:"flip", cat:"Commands & Control", front:"No toque nada.", back:"Don't touch anything.", note:"Double negative is correct Spanish: no + nada."},
  {id:"es-p17", type:"flip", cat:"Commands & Control", front:"Espere aquí.", back:"Wait here."},
  {id:"es-p18", type:"flip", cat:"Commands & Control", front:"Dese la vuelta.", back:"Turn around."},
  {id:"es-p20", type:"flip", cat:"Identity & Citizenship", front:"¿De qué país es usted ciudadano?", back:"Of what country are you a citizen?", note:"The classic field question — uses SER for citizenship/origin."},
  {id:"es-p21", type:"flip", cat:"Identity & Citizenship", front:"¿Cuál es su nacionalidad?", back:"What is your nationality?", note:"'¿Cuál?' (not '¿Qué?') before 'es' when selecting from possibilities."},
  {id:"es-p22", type:"flip", cat:"Identity & Citizenship", front:"¿Dónde nació usted?", back:"Where were you born?", note:"Preterite of nacer."},
  {id:"es-p23", type:"flip", cat:"Identity & Citizenship", front:"¿Cómo se llama usted?", back:"What is your name?", note:"Literally 'How do you call yourself?' — reflexive llamarse."},
  {id:"es-p24", type:"flip", cat:"Identity & Citizenship", front:"¿Cuál es su nombre completo?", back:"What is your full name?"},
  {id:"es-p25", type:"flip", cat:"Identity & Citizenship", front:"¿Cuál es su apellido?", back:"What is your last name?"},
  {id:"es-p26", type:"flip", cat:"Identity & Citizenship", front:"¿Cuántos años tiene usted?", back:"How old are you?", note:"Age uses TENER: literally 'How many years do you have?'"},
  {id:"es-p27", type:"flip", cat:"Identity & Citizenship", front:"¿Cuál es su fecha de nacimiento?", back:"What is your date of birth?"},
  {id:"es-p28", type:"flip", cat:"Identity & Citizenship", front:"¿Tiene documentos para estar legalmente en los Estados Unidos?", back:"Do you have documents to be in the United States legally?"},
  {id:"es-p29", type:"flip", cat:"Identity & Citizenship", front:"¿Tiene pasaporte o visa?", back:"Do you have a passport or visa?", note:"Spanish drops 'a/an' after tener in questions like this."},
  {id:"es-p30", type:"flip", cat:"Identity & Citizenship", front:"¿Tiene identificación?", back:"Do you have identification?"},
  {id:"es-p31", type:"flip", cat:"Identity & Citizenship", front:"¿En qué trabaja usted?", back:"What do you do for work?", note:"The 1943 book's '¿En qué se ocupa Vd.?' — this is the modern version."},
  {id:"es-p32", type:"flip", cat:"Identity & Citizenship", front:"¿Dónde vive usted?", back:"Where do you live?"},
  {id:"es-p33", type:"flip", cat:"Identity & Citizenship", front:"¿Está usted casado?", back:"Are you married?", note:"ESTAR with marital status is standard in Mexico."},
  {id:"es-p34", type:"flip", cat:"Identity & Citizenship", front:"¿Habla usted inglés?", back:"Do you speak English?"},
  {id:"es-p35", type:"flip", cat:"Identity & Citizenship", front:"Hable más despacio, por favor.", back:"Speak more slowly, please."},
  {id:"es-p36", type:"flip", cat:"Identity & Citizenship", front:"Repita, por favor.", back:"Repeat, please."},
  {id:"es-p37", type:"flip", cat:"Identity & Citizenship", front:"No entiendo.", back:"I don't understand."},
  {id:"es-p38", type:"flip", cat:"Identity & Citizenship", front:"¿Me entiende?", back:"Do you understand me?"},
  {id:"es-p40", type:"flip", cat:"Crossing & Travel", front:"¿Cómo entró usted a los Estados Unidos?", back:"How did you enter the United States?", note:"Preterite of entrar."},
  {id:"es-p41", type:"flip", cat:"Crossing & Travel", front:"¿Cuándo cruzó la frontera?", back:"When did you cross the border?"},
  {id:"es-p42", type:"flip", cat:"Crossing & Travel", front:"¿Dónde cruzó?", back:"Where did you cross?"},
  {id:"es-p43", type:"flip", cat:"Crossing & Travel", front:"¿Cruzó por el bosque?", back:"Did you cross through the woods?", note:"POR = through/along. Northern-border phrasing."},
  {id:"es-p44", type:"flip", cat:"Crossing & Travel", front:"¿Quién lo ayudó a cruzar?", back:"Who helped you cross?", note:"'lo' = you (direct object, formal masc.). Use 'la' for a woman."},
  {id:"es-p45", type:"flip", cat:"Crossing & Travel", front:"¿Cuánto pagó?", back:"How much did you pay?"},
  {id:"es-p46", type:"flip", cat:"Crossing & Travel", front:"¿Con quién viaja usted?", back:"Who are you traveling with?", note:"Preposition must come first: CON quién, never 'quién... con'."},
  {id:"es-p47", type:"flip", cat:"Crossing & Travel", front:"¿Adónde va?", back:"Where are you going?", note:"'¿Adónde?' for motion, '¿Dónde?' for location."},
  {id:"es-p48", type:"flip", cat:"Crossing & Travel", front:"¿De dónde viene?", back:"Where are you coming from?"},
  {id:"es-p49", type:"flip", cat:"Crossing & Travel", front:"¿Quién lo va a recoger?", back:"Who is going to pick you up?"},
  {id:"es-p50", type:"flip", cat:"Crossing & Travel", front:"¿Hay más personas con usted?", back:"Are there more people with you?", note:"HAY = there is / there are. One word, huge mileage."},
  {id:"es-p51", type:"flip", cat:"Crossing & Travel", front:"¿Cuántas personas hay?", back:"How many people are there?", note:"Cuántas agrees with personas (fem. pl.)."},
  {id:"es-p52", type:"flip", cat:"Crossing & Travel", front:"¿Hay niños en el grupo?", back:"Are there children in the group?"},
  {id:"es-p53", type:"flip", cat:"Crossing & Travel", front:"¿Dónde están los demás?", back:"Where are the others?", note:"ESTAR for location, always."},
  {id:"es-p54", type:"flip", cat:"Crossing & Travel", front:"¿Cuánto tiempo caminó?", back:"How long did you walk?"},
  {id:"es-p55", type:"flip", cat:"Crossing & Travel", front:"¿Cuánto tiempo hace que está aquí?", back:"How long have you been here?", note:"HACER time idiom: hace + time + que + present tense."},
  {id:"es-p60", type:"flip", cat:"Safety & Medical", front:"¿Está usted herido?", back:"Are you hurt?", note:"ESTAR for conditions. Use 'herida' for a woman."},
  {id:"es-p61", type:"flip", cat:"Safety & Medical", front:"¿Está usted bien?", back:"Are you okay?"},
  {id:"es-p62", type:"flip", cat:"Safety & Medical", front:"¿Necesita agua?", back:"Do you need water?"},
  {id:"es-p63", type:"flip", cat:"Safety & Medical", front:"¿Necesita un médico?", back:"Do you need a doctor?"},
  {id:"es-p64", type:"flip", cat:"Safety & Medical", front:"¿Tiene frío?", back:"Are you cold?", note:"TENER idiom: literally 'Do you have cold?' Critical question in a Vermont winter."},
  {id:"es-p65", type:"flip", cat:"Safety & Medical", front:"¿Puede caminar?", back:"Can you walk?"},
  {id:"es-p66", type:"flip", cat:"Safety & Medical", front:"¿Dónde le duele?", back:"Where does it hurt?", note:"Doler works like gustar: 'Me duele la cabeza' = my head hurts."},
  {id:"es-p67", type:"flip", cat:"Safety & Medical", front:"¿Tiene alguna enfermedad?", back:"Do you have any illness?"},
  {id:"es-p68", type:"flip", cat:"Safety & Medical", front:"¿Toma alguna medicina?", back:"Do you take any medicine?"},
  {id:"es-p69", type:"flip", cat:"Safety & Medical", front:"¿Está embarazada?", back:"Are you pregnant?"},
  {id:"es-p70", type:"flip", cat:"Safety & Medical", front:"Voy a ayudarle.", back:"I am going to help you.", note:"IR A + infinitive = going to. Your easiest future tense."},
  {id:"es-p71", type:"flip", cat:"Safety & Medical", front:"La ayuda viene en camino.", back:"Help is on the way."},
  {id:"es-p72", type:"flip", cat:"Safety & Medical", front:"¿Tiene armas?", back:"Do you have weapons?"},
  {id:"es-p73", type:"flip", cat:"Safety & Medical", front:"¿Tiene algo en los bolsillos que me pueda lastimar?", back:"Do you have anything in your pockets that could hurt me?", note:"The standard pat-down question. 'Pueda' is subjunctive after an uncertain 'algo... que'."},
  {id:"es-p74", type:"flip", cat:"Safety & Medical", front:"Todo va a estar bien.", back:"Everything is going to be okay."},
  {id:"es-p75", type:"flip", cat:"Safety & Medical", front:"Respire despacio.", back:"Breathe slowly."},
  {id:"es-p80", type:"flip", cat:"Processing & Transport", front:"Usted está detenido.", back:"You are detained / under arrest.", note:"ESTAR + past participle for a resulting state. 'Detenida' for a woman."},
  {id:"es-p81", type:"flip", cat:"Processing & Transport", front:"Voy a esposarlo por su seguridad y la mía.", back:"I am going to handcuff you for your safety and mine.", note:"Pronoun 'lo' attaches to the infinitive. POR = for the sake of."},
  {id:"es-p82", type:"flip", cat:"Processing & Transport", front:"Voy a revisarlo.", back:"I am going to search you."},
  {id:"es-p83", type:"flip", cat:"Processing & Transport", front:"Vacíe sus bolsillos.", back:"Empty your pockets."},
  {id:"es-p84", type:"flip", cat:"Processing & Transport", front:"Suba a la camioneta.", back:"Get in the van/truck.", note:"Subir = go up / get in. Irregular-yo verb: subo → suba."},
  {id:"es-p85", type:"flip", cat:"Processing & Transport", front:"Cuidado con la cabeza.", back:"Watch your head."},
  {id:"es-p86", type:"flip", cat:"Processing & Transport", front:"Vamos a la estación.", back:"We are going to the station."},
  {id:"es-p87", type:"flip", cat:"Processing & Transport", front:"Tiene derecho a hablar con su consulado.", back:"You have the right to speak with your consulate."},
  {id:"es-p88", type:"flip", cat:"Processing & Transport", front:"Firme aquí, por favor.", back:"Sign here, please."},
  {id:"es-p89", type:"flip", cat:"Processing & Transport", front:"Ponga su huella aquí.", back:"Put your fingerprint here.", note:"'Huella' = fingerprint AND footprint/track — same word you use cutting sign."},
  {id:"es-p90", type:"flip", cat:"Processing & Transport", front:"¿Entiende sus derechos?", back:"Do you understand your rights?"},
  {id:"es-p91", type:"flip", cat:"Processing & Transport", front:"Diga la verdad.", back:"Tell the truth.", note:"Irregular command of decir: diga."},
  {id:"es-p92", type:"flip", cat:"Processing & Transport", front:"Siga las instrucciones.", back:"Follow the instructions.", note:"From seguir (e→i): siga."},
  {id:"es-p93", type:"flip", cat:"Processing & Transport", front:"Espere su turno.", back:"Wait your turn."},
  {id:"es-p94", type:"flip", cat:"Processing & Transport", front:"Mentir es un delito.", back:"Lying is a crime.", note:"Infinitive used as a noun — Lesson XXVI of the old manual."},
  {id:"es-p100", type:"flip", cat:"Everyday & Idioms", front:"Tengo que verificar sus documentos.", back:"I have to verify your documents.", note:"TENER QUE + infinitive = to have to. The workhorse obligation idiom."},
  {id:"es-p101", type:"flip", cat:"Everyday & Idioms", front:"Hay que esperar.", back:"One must wait. / We have to wait.", note:"HAY QUE + infinitive = impersonal 'it is necessary to'."},
  {id:"es-p102", type:"flip", cat:"Everyday & Idioms", front:"Hace frío. / Hace calor.", back:"It's cold. / It's hot.", note:"Weather uses HACER, not ser/estar."},
  {id:"es-p103", type:"flip", cat:"Everyday & Idioms", front:"¿Qué hora es?", back:"What time is it?"},
  {id:"es-p104", type:"flip", cat:"Everyday & Idioms", front:"Hace dos días.", back:"Two days ago.", note:"HACE + time = ago. '¿Cuándo cruzó?' — 'Hace dos días.'"},
  {id:"es-p105", type:"flip", cat:"Everyday & Idioms", front:"Acaba de llegar.", back:"He/she just arrived.", note:"ACABAR DE + infinitive = to have just done something."},
  {id:"es-p106", type:"flip", cat:"Everyday & Idioms", front:"Otra vez. / De nuevo.", back:"Again."},
  {id:"es-p107", type:"flip", cat:"Everyday & Idioms", front:"Tenga cuidado.", back:"Be careful.", note:"TENER idiom in command form."},
  {id:"es-p108", type:"flip", cat:"Everyday & Idioms", front:"Con permiso. / Perdón.", back:"Excuse me. / Pardon.", note:"Con permiso to pass by; perdón after a bump or to get attention."},
  {id:"es-p109", type:"flip", cat:"Everyday & Idioms", front:"Buenos días. / Buenas tardes. / Buenas noches.", back:"Good morning. / Good afternoon. / Good evening."},
  {id:"es-p110", type:"flip", cat:"Everyday & Idioms", front:"Gracias. — De nada.", back:"Thank you. — You're welcome."},
  {id:"es-p111", type:"flip", cat:"Everyday & Idioms", front:"Ya voy.", back:"I'm coming (right now).", note:"Straight from the 1943 manual — still exactly how it's said."},
  {id:"es-p112", type:"flip", cat:"Everyday & Idioms", front:"Usted se equivoca.", back:"You are mistaken.", note:"Reflexive equivocarse — useful when a story doesn't add up."},
  {id:"es-p113", type:"flip", cat:"Everyday & Idioms", front:"Me parece que...", back:"It seems to me that..."},
  {id:"es-p114", type:"flip", cat:"Everyday & Idioms", front:"¿De veras? / ¿En serio?", back:"Really? / Seriously?"},
  {id:"es-p115", type:"flip", cat:"Everyday & Idioms", front:"Poco a poco.", back:"Little by little.", note:"Also the honest answer to '¿Habla español?' while you're learning."},
  ],
};
