// STATUTES & AUTHORITY — 8 U.S.C., 8 C.F.R., 19 U.S.C.
// Text checked against the URL in `verified` (see VERIFICATION.md). Quotes are verbatim; paraphrase is marked.
// Penalties are carded only where the statute's text was confirmed.
export default {
  meta: { id:"statutes", name:"Statutes & Authority", short:"USC", color:"#6FB3A8", order:4, requireVerified:true,
    blurb:"Where your authority comes from: 8 U.S.C. § 1357, 8 C.F.R. 287, and the crimes you charge.",
    subModes:["browse"] },
  categories: {
    "Powers — 8 USC 1357": { why:"Every warrantless action you take has to trace back to one of these powers." },
    "Regulations — 8 CFR 287": { why:"The regulations define the terms in § 1357 and set the standards you're held to." },
    "Offenses": { why:"Knowing the elements tells you what facts to document." },
    "Customs Authority": { why:"Customs authority sits alongside immigration authority at and near the border." },
    "Which Authority?": { why:"Naming the exact authority is how you articulate your legal basis." },
  },
  cards: [
  // ---------------- 8 USC 1357 ----------------
  { id:"st-1357-a1", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(a)(1) — interrogate", back:"Power without warrant \"to interrogate any alien or person believed to be an alien as to his right to be or to remain in the United States.\"",
    note:"The statute doesn't override the Fourth Amendment. Detaining someone to question them still needs reasonable suspicion (8 C.F.R. 287.8(b)).",
    why:"Your authority to ask about status.",
    source:"8 U.S.C. § 1357(a)(1)", verified:"https://www.law.cornell.edu/uscode/text/8/1357" },
  { id:"st-1357-a2", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(a)(2) — warrantless immigration arrest", back:"Power to arrest any alien who, in the officer's presence or view, is entering or attempting to enter in violation of immigration law, or to arrest any alien in the U.S. if the officer has reason to believe the alien is here in violation of such law AND is likely to escape before a warrant can be obtained.",
    note:"Two prongs for interior arrests: reason to believe the person is unlawfully present + likelihood of escape. Document both.",
    why:"The basis for most administrative immigration arrests in the field.",
    source:"8 U.S.C. § 1357(a)(2)", verified:"https://www.law.cornell.edu/uscode/text/8/1357" },
  { id:"st-1357-a3", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(a)(3) — conveyances and private lands", back:"Within a reasonable distance from any external boundary: board and search for aliens any vessel in U.S. territorial waters and any railway car, aircraft, conveyance or vehicle. Within 25 miles of the boundary: access to private lands, but not dwellings, to patrol the border and prevent illegal entry.",
    note:"'Reasonable distance' = 100 air miles under 8 C.F.R. 287.1(a)(2). The 25-mile private-lands access excludes dwellings.",
    flag:"The Fourth Amendment still applies: Almeida-Sanchez requires probable cause or consent for roving-patrol vehicle searches, and Brignoni-Ponce requires reasonable suspicion for roving stops.",
    why:"The geographic basis of Border Patrol authority, and its limits.",
    source:"8 U.S.C. § 1357(a)(3)", verified:"https://www.govinfo.gov/link/statute/66/26" },
  { id:"st-1357-a4", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(a)(4) — immigration felonies", back:"Power to arrest for felonies under laws regulating admission, exclusion, expulsion or removal of aliens, if the officer has reason to believe the person is guilty AND is likely to escape before a warrant can be obtained. The person must be taken without unnecessary delay before the nearest available officer empowered to commit persons charged with federal offenses.",
    why:"Covers felony arrests such as § 1326 reentry.",
    source:"8 U.S.C. § 1357(a)(4)", verified:"https://lawofselfdefense.com/statute/8-usc-1357-powers-of-immigration-officers-and-employees/" },
  { id:"st-1357-a5", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(a)(5) — general federal arrests", back:"(A) Any federal offense committed in the officer's presence. (B) Any federal felony, if there are reasonable grounds to believe the person committed or is committing it, the officer is performing immigration-enforcement duties at the time, and there is a likelihood of escape before a warrant can be obtained.",
    why:"Your authority for non-immigration federal crimes you come across, such as drugs or assault.",
    source:"8 U.S.C. § 1357(a)(5)", verified:"https://lawofselfdefense.com/statute/8-usc-1357-powers-of-immigration-officers-and-employees/" },
  { id:"st-1357-c", type:"flip", cat:"Powers — 8 USC 1357", binding:"statute",
    front:"8 U.S.C. § 1357(c) — search of persons seeking admission", back:"Power to search, without warrant, the person and personal effects of anyone seeking admission, when the officer has reasonable cause to suspect that grounds for denial of admission exist that the search would reveal.",
    why:"Statutory search authority for people seeking admission.",
    source:"8 U.S.C. § 1357(c)", verified:"https://www.law.cornell.edu/uscode/text/8/1357" },

  // ---------------- 8 CFR 287 ----------------
  { id:"st-2871-a2", type:"flip", cat:"Regulations — 8 CFR 287", binding:"regulation",
    front:"8 C.F.R. 287.1(a)(2) — 'reasonable distance'", back:"Within 100 air miles from any external boundary of the United States, or any shorter distance fixed by the chief patrol agent (CBP) or special agent in charge (ICE).",
    note:"287.1(b): fixing distances considers topography, transportation routes, population density, inconvenience to the public, conveyance types, and reliable information on illegal-entry movements. A longer distance needs a report to and approval by the CBP Commissioner.",
    why:"Defines the 'reasonable distance' in § 1357(a)(3).",
    source:"8 C.F.R. § 287.1(a)(2), (b)", verified:"https://www.law.cornell.edu/cfr/text/8/287.1" },
  { id:"st-2878-b", type:"flip", cat:"Regulations — 8 CFR 287", binding:"regulation",
    front:"8 C.F.R. 287.8(b) — interrogation and brief detention", back:"Any officer may ask anyone questions as long as the officer doesn't restrain the freedom of a person not under arrest to walk away. With reasonable suspicion, based on specific articulable facts, that the person is engaged in an offense against the U.S. or is an alien illegally in the U.S., the officer may briefly detain the person for questioning.",
    why:"Codifies the consensual / Terry line for immigration officers.",
    source:"8 C.F.R. § 287.8(b)", verified:"https://www.govinfo.gov/content/pkg/CFR-2024-title8-vol1/pdf/CFR-2024-title8-vol1-sec287-8.pdf" },
  { id:"st-2878-c2i", type:"flip", cat:"Regulations — 8 CFR 287", binding:"regulation",
    front:"8 C.F.R. 287.8(c)(2)(i) — basis for arrest", back:"An arrest shall be made only when the designated immigration officer has reason to believe the person has committed an offense against the United States or is an alien illegally in the United States.",
    why:"The regulatory arrest standard.",
    source:"8 C.F.R. § 287.8(c)(2)(i)", verified:"https://www.law.cornell.edu/cfr/text/8/287.8" },
  { id:"st-2878-c2iii", type:"order", cat:"Regulations — 8 CFR 287", binding:"regulation",
    q:"At the time of arrest, as soon as it is practical and safe, what does 287.8(c)(2)(iii) require — in order?",
    steps:["Identify yourself as an immigration officer authorized to execute an arrest","State that the person is under arrest","State the reason for the arrest"],
    explain:"Identify, then announce the arrest and its reason, as soon as practical and safe.",
    why:"Regulatory requirement on every arrest.",
    source:"8 C.F.R. § 287.8(c)(2)(iii)", verified:"https://www.law.cornell.edu/cfr/text/8/287.8" },
  { id:"st-2878-a-nondeadly", type:"flip", cat:"Regulations — 8 CFR 287", binding:"regulation",
    front:"8 C.F.R. 287.8(a) — non-deadly force", back:"Always use the minimum non-deadly force necessary to accomplish the mission. Escalate to a higher level only when warranted by the subject's actions, apparent intentions, and apparent capabilities.",
    why:"The regulatory force continuum. Pairs with Graham v. Connor.",
    source:"8 C.F.R. § 287.8(a)(1)", verified:"https://chanrobles.com/usa/uslaws/cfr/title08/8-1.0.1.2.57.0.1.8.php" },
  { id:"st-2878-a-deadly", type:"flip", cat:"Regulations — 8 CFR 287", binding:"regulation",
    front:"8 C.F.R. 287.8(a)(2) — deadly force", back:"Deadly force (force likely to cause death or serious physical injury) may be used only when the designated officer has reasonable grounds to believe it is necessary to protect the officer or others from the imminent danger of death or serious physical injury.",
    why:"The regulatory deadly-force standard.",
    source:"8 C.F.R. § 287.8(a)(2)", verified:"https://www.law.cornell.edu/cfr/text/8/287.8" },

  // ---------------- Offenses ----------------
  { id:"st-1325a", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1325(a) — improper entry", back:"An alien who (1) enters or attempts to enter at any time or place other than as designated by immigration officers, (2) eludes examination or inspection, or (3) attempts to enter or obtains entry by a willfully false or misleading representation or willful concealment of a material fact. First offense: fine and/or up to 6 months. Subsequent: fine and/or up to 2 years.",
    why:"The base illegal-entry charge.",
    source:"8 U.S.C. § 1325(a)", verified:"https://www.govinfo.gov/content/pkg/USCODE-2024-title8/html/USCODE-2024-title8-chap12-subchapII-partVIII-sec1325.htm" },
  { id:"st-1326a", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1326(a) — reentry after removal", back:"An alien who has been denied admission, excluded, deported or removed (or departed while such an order was outstanding) and then enters, attempts to enter, or is at any time found in the U.S., without the Attorney General's express consent to reapply. Fine and/or up to 2 years.",
    note:"'Found in' — the offense can be complete when you encounter the person, not only at the moment of crossing.",
    why:"The reentry felony. Prior removal is the key fact to confirm.",
    source:"8 U.S.C. § 1326(a)", verified:"https://www.law.cornell.edu/uscode/text/8/1326" },
  { id:"st-1326b", type:"mc", cat:"Offenses", binding:"statute",
    q:"Under § 1326(b), what is the maximum sentence for reentry after removal that followed an aggravated-felony conviction?",
    choices:["2 years","10 years","20 years","Life"],
    answer:2, explain:"(b)(2): aggravated felony = up to 20 years. (b)(1): three or more drug or person misdemeanors, or a non-aggravated felony = up to 10 years. Base (a) = 2 years.",
    why:"Criminal history drives the charge. Run it every time.",
    source:"8 U.S.C. § 1326(b)", verified:"https://www.law.cornell.edu/uscode/text/8/1326" },
  { id:"st-1324-i", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1324(a)(1)(A)(i) — bringing in", back:"Knowing that a person is an alien, bringing or attempting to bring the person to the U.S. in any manner at a place other than a designated port of entry or place designated by the Commissioner, regardless of whether the alien has prior official authorization.",
    why:"Smuggling at the line.",
    source:"8 U.S.C. § 1324(a)(1)(A)(i)", verified:"https://law.counselstack.com/usc/8/1324" },
  { id:"st-1324-ii", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1324(a)(1)(A)(ii) — transporting", back:"Knowing or in reckless disregard of the fact that an alien came to, entered or remains in the U.S. in violation of law, transporting or moving (or attempting to) the alien within the U.S., by means of transportation or otherwise, in furtherance of that violation.",
    note:"Elements to document: transport, the alien's unlawful status, the driver's knowledge or reckless disregard, and 'in furtherance'.",
    why:"The most common smuggling charge from a vehicle stop.",
    source:"8 U.S.C. § 1324(a)(1)(A)(ii)", verified:"https://www.pbwt.com/second-circuit-blog/upon-further-review-second-circuit-holds-that-defendants-conduct-not-in-furtherance-of-aliens-unlawful-presence-in-united-states" },
  { id:"st-1324-iii", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1324(a)(1)(A)(iii) — harboring", back:"Knowing or in reckless disregard of an alien's unlawful entry or presence, concealing, harboring or shielding from detection (or attempting to) the alien in any place, including any building or means of transportation.",
    why:"Covers stash houses and hiding people in vehicles.",
    source:"8 U.S.C. § 1324(a)(1)(A)(iii)", verified:"https://law.counselstack.com/usc/8/1324" },
  { id:"st-1324-mc", type:"mc", cat:"Offenses", binding:"statute",
    q:"Which § 1324(a)(1)(A) clause covers encouraging or inducing an alien to come to or remain in the U.S.?",
    choices:["(i)","(ii)","(iii)","(iv)"],
    answer:3, explain:"(i) bringing in, (ii) transporting, (iii) harboring, (iv) encouraging/inducing, (v) conspiracy or aiding and abetting.",
    why:"The right subsection goes on the complaint.",
    source:"8 U.S.C. § 1324(a)(1)(A)(i)–(v)", verified:"https://law.counselstack.com/usc/8/1324" },
  { id:"st-1304e", type:"flip", cat:"Offenses", binding:"statute",
    front:"8 U.S.C. § 1304(e) — carrying registration", back:"Every alien 18 and over shall at all times carry and have in personal possession any certificate of alien registration or registration receipt card issued to him. Failure is a misdemeanor: fine up to $100 and/or up to 30 days per offense.",
    why:"Why lawful residents should be able to produce documents on request.",
    source:"8 U.S.C. § 1304(e)", verified:"https://www.govinfo.gov/content/pkg/USCODE-2024-title8/html/USCODE-2024-title8-chap12-subchapII-partVII-sec1304.htm" },

  // ---------------- Customs ----------------
  { id:"st-1581a", type:"flip", cat:"Customs Authority", binding:"statute",
    front:"19 U.S.C. § 1581(a) — customs boarding", back:"Any officer of the customs may at any time go on board any vessel or vehicle at any place in the U.S. or within customs waters to examine the manifest and documents, and examine, inspect and search the vessel or vehicle and any person, trunk, package or cargo aboard. The officer may hail and stop it and use all necessary force to compel compliance.",
    flag:"Statutory breadth doesn't remove Fourth Amendment limits away from the border (see Almeida-Sanchez, Ortiz).",
    why:"The broad customs boarding power. Know its text and its Fourth Amendment limits.",
    source:"19 U.S.C. § 1581(a)", verified:"https://www.law.cornell.edu/uscode/text/19/1581" },

  // ---------------- Which Authority? ----------------
  { id:"st-sc-land", type:"scenario", cat:"Which Authority?",
    setup:"Following foot sign across a farm field 10 miles from the boundary. There's a house and a barn on the property. The owner isn't around.",
    q:"What does § 1357(a)(3) allow?",
    choices:["Enter the fields and the house","Enter the private land to patrol, but not the dwelling","Nothing without the owner's consent","Only with a warrant"],
    answer:1, explain:"Within 25 miles: access to private lands, but not dwellings, to patrol the border.",
    source:"8 U.S.C. § 1357(a)(3)", verified:"https://www.govinfo.gov/link/statute/66/26" },
  { id:"st-sc-distance", type:"scenario", cat:"Which Authority?",
    setup:"You're 60 air miles from the boundary and want to stop a vehicle on roving patrol.",
    q:"What do you need?",
    choices:["Nothing: inside 100 air miles any vehicle may be searched","Reasonable suspicion (Brignoni-Ponce). The 100-mile zone doesn't remove the Fourth Amendment","Probable cause to stop","A checkpoint"],
    answer:1, explain:"287.1 defines where § 1357(a)(3) applies. Brignoni-Ponce and Almeida-Sanchez still set the stop and search standards.",
    source:"8 C.F.R. § 287.1(a)(2); 8 U.S.C. § 1357(a)(3)", verified:"https://www.law.cornell.edu/cfr/text/8/287.1" },
  { id:"st-sc-arrest-interior", type:"scenario", cat:"Which Authority?",
    setup:"Inland, a subject admits being unlawfully present and has a car and a bus ticket out of state tonight. No warrant exists.",
    q:"Which authority supports a warrantless administrative arrest?",
    choices:["§ 1357(a)(1)","§ 1357(a)(2): reason to believe unlawfully present + likely to escape","§ 1304(e)","§ 1357(c)"],
    answer:1, explain:"(a)(2) needs both prongs. The ticket and car support the likelihood of escape. Write them down.",
    source:"8 U.S.C. § 1357(a)(2)", verified:"https://www.law.cornell.edu/uscode/text/8/1357" },
  { id:"st-sc-found-in", type:"scenario", cat:"Which Authority?",
    setup:"Records show a subject you've just encountered was removed two years ago. The subject has no consent to reapply.",
    q:"What is the likely charge?",
    choices:["§ 1325(a) improper entry","§ 1326(a) reentry ('found in')","§ 1324(a)(1)(A)(ii)","§ 1304(e)"],
    answer:1, explain:"A prior removal plus being found in the U.S. without consent = § 1326. Then check (b) for prior convictions.",
    source:"8 U.S.C. § 1326(a)", verified:"https://www.law.cornell.edu/uscode/text/8/1326" },
  { id:"st-sc-driver", type:"scenario", cat:"Which Authority?",
    setup:"A driver picks up four people walking out of the woods just south of the line and drives them toward a city. Their story: 'I'm giving hitchhikers a ride.'",
    q:"Which offense, and what's the key element to develop?",
    choices:["§ 1325, entry","§ 1324(a)(1)(A)(ii) transporting: knowledge or reckless disregard of their status","§ 1326, reentry","§ 1304(e)"],
    answer:1, explain:"Transporting requires knowing or reckless disregard of unlawful status and 'in furtherance'. Document pickup location, timing, payment, phones, and what was said.",
    source:"8 U.S.C. § 1324(a)(1)(A)(ii)", verified:"https://www.pbwt.com/second-circuit-blog/upon-further-review-second-circuit-holds-that-defendants-conduct-not-in-furtherance-of-aliens-unlawful-presence-in-united-states" },
  { id:"st-sc-drugs", type:"scenario", cat:"Which Authority?",
    setup:"During an immigration-status stop you see a firearm and drugs in plain view. The driver is a U.S. citizen.",
    q:"What is your arrest authority for the federal drug felony?",
    choices:["None: citizens are outside immigration authority","§ 1357(a)(5)(B): federal felony, reasonable grounds, on immigration duty, likely escape","§ 1357(a)(2)","§ 1304(e)"],
    answer:1, explain:"(a)(5) covers non-immigration federal offenses: in your presence (A), or felonies with the (B) conditions.",
    source:"8 U.S.C. § 1357(a)(5)", verified:"https://lawofselfdefense.com/statute/8-usc-1357-powers-of-immigration-officers-and-employees/" },
  ],
};
